import Work.GCert.Scalar.Main
import Work.GCert.Data.E8ScalOK
import Work.GCert.Data.B2Ge8

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `E8`: THE CLOSED THEOREMS
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`wht_B2Ge8_of_ids` (label half, price, unit list, rate fact, gx-chain's end theorem) applied to the scalar half
`GXD.E8.scalOK : GS.ScalOK GXD.E8.raw` (kernel checks `scal<i>_ok`, `ychk_ok`; soundness: gx-scalar).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 87624/10^8))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `E8`.** -/
theorem wht_main_B2Ge8 :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 87624/(10:ℝ)^8) W :=
  wht_B2Ge8_of_ids GXD.E8.scalOK.hv GXD.E8.scalOK.hAi GXD.E8.scalOK.hBi GXD.E8.scalOK.hx GXD.E8.scalOK.hy GXD.E8.scalOK.hid

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 8762479/10^10))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `E8`.** -/
theorem wht_main_B2Ge8x :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 8762479/(10:ℝ)^10) W :=
  wht_B2Ge8x_of_ids GXD.E8.scalOK.hv GXD.E8.scalOK.hAi GXD.E8.scalOK.hBi GXD.E8.scalOK.hx GXD.E8.scalOK.hy GXD.E8.scalOK.hid

end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_main_B2Ge8
#print axioms OAI.PowerSaving.WHT.wht_main_B2Ge8x
