import Work.GCert.Chain.End
import Work.GCert.Data.Glue
import Work.GCert.Data.E8Cert
import Work.GCert.Data.InstB2Ge8

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `E8` (h = 9, m = 45): final theorems over a scalar half
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`GX.wht_of_halves` (gx-chain) on the label half `GXD.E8.valid` (kernel checks of `Work/GCert/Data/Gen/E8*`), its
price `GXD.E8.lab_price`, the unit list `BlockAccounting.blocksB2Ge8` (`W = 1263` live roles) and the rate facts
`fold_B2Ge8` (`1 - 87624/10^8`), `fold_B2Ge8x` (`1 - 8762479/10^10`).
The ONLY hypothesis left is the scalar half: `S : GX.Scal (Fin 120) (Fin 783) C` whose gate matrices are the ordered
products of the adds of `raw` (`hMA .. hMBi`), with `8` copies read from the retained registers (`reg`, `hCc`, `hreg`, `hC`);
`wht_B2Ge8_of_ids`, `wht_B2Ge8x_of_ids`: the same from the five identities `hAi hBi hx hy hid` of gx-scalar's matrices
`GS.MA GS.MAi GS.MB GS.MBi GS.Jrm GS.Ccm` of `raw` (the fields of the planned `GS.ScalOK`).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT

variable {C : Type} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin GXD.E8.raw.v) (Fin GXD.E8.raw.R) C)
  {emb : CR.L3 (Fin GXD.E8.raw.v) (Fin GXD.E8.raw.R) → Nat} {un : Nat → CR.L3 (Fin GXD.E8.raw.v) (Fin GXD.E8.raw.R)}
  (cf : GXD.Co → SSC.Coef)

/-- **Walsh-Hadamard transform, whole-block recursion on the bridged word B_2 with the gcert/1 circuit `E8`**,
over any scalar half of `GXD.E8.raw`: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with `1 - 2/10^11`
replaced by `1 - 87624/10^8`. -/
theorem wht_B2Ge8_of_scal (Ro : GLab.Roles GXD.E8.raw.v GXD.E8.raw.R emb un)
    (hMA : S.MA = SSC.matP un (GLab.mic cf (GXD.E8.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMAi : S.MAi = SSC.matPinv un (GLab.mic cf (GXD.E8.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMB : S.MB = SSC.matP un (GLab.mic cf (GXD.E8.raw.gatesB.flatMap GXD.Gate.adds)))
    (hMBi : S.MBi = SSC.matPinv un (GLab.mic cf (GXD.E8.raw.gatesB.flatMap GXD.Gate.adds)))
    (reg : C → Nat) (hCc : ∀ k (q : Fin GXD.E8.raw.R), S.Cc k q ≠ 0 → reg k = 2 * GXD.E8.raw.v + q.val)
    (hreg : ∀ k, reg k ∈ GXD.E8.raw.ret.map Prod.fst) (hC : Fintype.card C = 8) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 87624/(10:ℝ)^8) W :=
  GX.wht_of_halves S (GXD.E8.valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg)
    (by rw [Fintype.card_fin]; decide) 45 1263 (by rw [Fintype.card_fin]; rfl)
    (by rw [Fintype.card_fin, Fintype.card_fin]; rfl) (by norm_num) BlockAccounting.blocksB2Ge8
    (fun φ => by
      rw [GXD.E8.lab_price S Ro cf hMA hMAi hMB hMBi reg hCc hreg hC φ, Fintype.card_fin, Fintype.card_fin]
      exact BridgeRate.B2Ge8.unit_cost φ)
    13 (1 - 87624/(10:ℝ)^8) (by norm_num) (by norm_num) BlockAccounting.fold_B2Ge8

/-- the same from the FIVE scalar identities of gx-scalar's matrices of `GXD.E8.raw` (`Work/GCert/Data/Glue.lean`) -/
theorem wht_B2Ge8_of_ids (hv : 0 < GXD.E8.raw.v)
    (hAi : GS.MAi GXD.E8.raw hv * GS.MA GXD.E8.raw hv = 1) (hBi : GS.MBi GXD.E8.raw hv * GS.MB GXD.E8.raw hv = 1)
    (hx : ∀ (t : Fin GXD.E8.raw.v) (j : GS.Rl GXD.E8.raw), (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) (CR.lX t) j = if CR.lX t = j then 1 else 0)
    (hy : ∀ (i : GS.Rl GXD.E8.raw) (t : Fin GXD.E8.raw.v), (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) i (CR.lY t) = if i = CR.lY t then 1 else 0)
    (hid : ∀ S t : Fin GXD.E8.raw.v, (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) (CR.lY S) (CR.lX t) = if S = t then 1 else 0) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 87624/(10:ℝ)^8) W :=
  wht_B2Ge8_of_scal (GXD.scalOf GXD.E8.raw hv hAi hBi hx hy hid) GS.toCoef (GXD.roles GXD.E8.raw hv)
    (GXD.scalOf_MA _ hv hAi hBi hx hy hid) (GXD.scalOf_MAi _ hv hAi hBi hx hy hid)
    (GXD.scalOf_MB _ hv hAi hBi hx hy hid) (GXD.scalOf_MBi _ hv hAi hBi hx hy hid)
    (GXD.reg GXD.E8.raw) (GXD.reg_slot GXD.E8.raw hv hAi hBi hx hy hid) (GXD.reg_mem GXD.E8.raw)
    (by rw [Fintype.card_fin]; decide)

/-- **Walsh-Hadamard transform, whole-block recursion on the bridged word B_2 with the gcert/1 circuit `E8`**,
over any scalar half of `GXD.E8.raw`: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with `1 - 2/10^11`
replaced by `1 - 8762479/10^10`. -/
theorem wht_B2Ge8x_of_scal (Ro : GLab.Roles GXD.E8.raw.v GXD.E8.raw.R emb un)
    (hMA : S.MA = SSC.matP un (GLab.mic cf (GXD.E8.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMAi : S.MAi = SSC.matPinv un (GLab.mic cf (GXD.E8.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMB : S.MB = SSC.matP un (GLab.mic cf (GXD.E8.raw.gatesB.flatMap GXD.Gate.adds)))
    (hMBi : S.MBi = SSC.matPinv un (GLab.mic cf (GXD.E8.raw.gatesB.flatMap GXD.Gate.adds)))
    (reg : C → Nat) (hCc : ∀ k (q : Fin GXD.E8.raw.R), S.Cc k q ≠ 0 → reg k = 2 * GXD.E8.raw.v + q.val)
    (hreg : ∀ k, reg k ∈ GXD.E8.raw.ret.map Prod.fst) (hC : Fintype.card C = 8) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 8762479/(10:ℝ)^10) W :=
  GX.wht_of_halves S (GXD.E8.valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg)
    (by rw [Fintype.card_fin]; decide) 45 1263 (by rw [Fintype.card_fin]; rfl)
    (by rw [Fintype.card_fin, Fintype.card_fin]; rfl) (by norm_num) BlockAccounting.blocksB2Ge8x
    (fun φ => by
      rw [GXD.E8.lab_price S Ro cf hMA hMAi hMB hMBi reg hCc hreg hC φ, Fintype.card_fin, Fintype.card_fin]
      exact BridgeRate.B2Ge8.unit_cost_x φ)
    40 (1 - 8762479/(10:ℝ)^10) (by norm_num) (by norm_num) BlockAccounting.fold_B2Ge8x

/-- the same from the FIVE scalar identities of gx-scalar's matrices of `GXD.E8.raw` (`Work/GCert/Data/Glue.lean`) -/
theorem wht_B2Ge8x_of_ids (hv : 0 < GXD.E8.raw.v)
    (hAi : GS.MAi GXD.E8.raw hv * GS.MA GXD.E8.raw hv = 1) (hBi : GS.MBi GXD.E8.raw hv * GS.MB GXD.E8.raw hv = 1)
    (hx : ∀ (t : Fin GXD.E8.raw.v) (j : GS.Rl GXD.E8.raw), (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) (CR.lX t) j = if CR.lX t = j then 1 else 0)
    (hy : ∀ (i : GS.Rl GXD.E8.raw) (t : Fin GXD.E8.raw.v), (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) i (CR.lY t) = if i = CR.lY t then 1 else 0)
    (hid : ∀ S t : Fin GXD.E8.raw.v, (GS.MB GXD.E8.raw hv * CR.scatM (GS.Jrm GXD.E8.raw * GS.Ccm GXD.E8.raw)
      * GS.MA GXD.E8.raw hv) (CR.lY S) (CR.lX t) = if S = t then 1 else 0) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 8762479/(10:ℝ)^10) W :=
  wht_B2Ge8x_of_scal (GXD.scalOf GXD.E8.raw hv hAi hBi hx hy hid) GS.toCoef (GXD.roles GXD.E8.raw hv)
    (GXD.scalOf_MA _ hv hAi hBi hx hy hid) (GXD.scalOf_MAi _ hv hAi hBi hx hy hid)
    (GXD.scalOf_MB _ hv hAi hBi hx hy hid) (GXD.scalOf_MBi _ hv hAi hBi hx hy hid)
    (GXD.reg GXD.E8.raw) (GXD.reg_slot GXD.E8.raw hv hAi hBi hx hy hid) (GXD.reg_mem GXD.E8.raw)
    (by rw [Fintype.card_fin]; decide)

end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_B2Ge8_of_scal
#print axioms OAI.PowerSaving.WHT.wht_B2Ge8x_of_scal
#print axioms OAI.PowerSaving.WHT.wht_B2Ge8_of_ids
#print axioms OAI.PowerSaving.WHT.wht_B2Ge8x_of_ids
