import Work.GCert.Scalar.Main
import Work.GCert.Data.P193ScalOK
import Work.GCert.Data.B2Gp193

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `P193`: THE CLOSED THEOREMS
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`wht_B2Gp193_of_ids` (label half, price, unit list, rate fact, gx-chain's end theorem) applied to the scalar half
`GXD.P193.scalOK : GS.ScalOK GXD.P193.raw` (kernel checks `scal<i>_ok`, `ychk_ok`; soundness: gx-scalar).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 74745/10^8))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `P193`.** -/
theorem wht_main_B2Gp193 :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 74745/(10:ℝ)^8) W :=
  wht_B2Gp193_of_ids GXD.P193.scalOK.hv GXD.P193.scalOK.hAi GXD.P193.scalOK.hBi GXD.P193.scalOK.hx GXD.P193.scalOK.hy GXD.P193.scalOK.hid

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 7474547/10^10))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `P193`.** -/
theorem wht_main_B2Gp193x :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 7474547/(10:ℝ)^10) W :=
  wht_B2Gp193x_of_ids GXD.P193.scalOK.hv GXD.P193.scalOK.hAi GXD.P193.scalOK.hBi GXD.P193.scalOK.hx GXD.P193.scalOK.hy GXD.P193.scalOK.hid

end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_main_B2Gp193
#print axioms OAI.PowerSaving.WHT.wht_main_B2Gp193x
