import Work.GCert.Scalar.Main
import Work.GCert.Data.P233ScalOK
import Work.GCert.Data.B2Gp233

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `P233`: THE CLOSED THEOREMS
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`wht_B2Gp233_of_ids` (label half, price, unit list, rate fact, gx-chain's end theorem) applied to the scalar half
`GXD.P233.scalOK : GS.ScalOK GXD.P233.raw` (kernel checks `scal<i>_ok`, `ychk_ok`; soundness: gx-scalar).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 75473/10^8))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `P233`.** -/
theorem wht_main_B2Gp233 :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 75473/(10:ℝ)^8) W :=
  wht_B2Gp233_of_ids GXD.P233.scalOK.hv GXD.P233.scalOK.hAi GXD.P233.scalOK.hBi GXD.P233.scalOK.hx GXD.P233.scalOK.hy GXD.P233.scalOK.hid

/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - 7547361/10^10))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `P233`.** -/
theorem wht_main_B2Gp233x :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 7547361/(10:ℝ)^10) W :=
  wht_B2Gp233x_of_ids GXD.P233.scalOK.hv GXD.P233.scalOK.hAi GXD.P233.scalOK.hBi GXD.P233.scalOK.hx GXD.P233.scalOK.hy GXD.P233.scalOK.hid

end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_main_B2Gp233
#print axioms OAI.PowerSaving.WHT.wht_main_B2Gp233x
