import Work.GCert.Scalar.Main
import Work.GCert.Data.Gen.E8Scal0
import Work.GCert.Data.Gen.E8YChk
/-! # (key: gx-data) gcert/1 certificate `E8` (h = 9): THE SCALAR HALF `scalOK : GS.ScalOK raw`
GENERATED by checks/wht26/gx-data/py/gxgen.py from gcert1-e8-r783.json.gz.  No `sorry`.
Kernel checks `scal<i>_ok` (1 source batches) and `ychk_ok`. -/
namespace GXD.E8
open GXD
theorem scalOK : GS.ScalOK raw where
  hv := by decide
  hs := fun t ht =>
    ⟨0, 120, Nat.zero_le t, Nat.lt_of_lt_of_le ht (by decide), GS.XRun.of_check scal0_ok⟩
  hyc := fun t ht => ⟨0, 120, Nat.zero_le t, Nat.lt_of_lt_of_le ht (by decide), GS.YRun.of_check ychk_ok⟩
end GXD.E8
#print axioms GXD.E8.scalOK
