import Work.BridgeGeom.B2
import Work.FoldRate.Group
import Work.GCert.Data.RateB2Ge8
import Work.GCert.Data.RateB2Ge8x

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `E8`, h = 9: the unit price is the price of the block list

GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.  Arithmetic only (no certificate is imported).

One unit: `W = 1263` live roles (`4 v + R`, `v = 120`, `R = 783`), label dimension `m = 45`, deficit `D = 120`.
`invPrice φ` = the price of the blocks of ONE invocation (the kernel-counted list `GXD.E8.hist`, by rank);
`unitPrice φ = 5 * invPrice φ + v * BG.bankPrice h φ = listCost φ BlockAccounting.blocksB2Ge8` (`unit_cost`).
Whole-block `1 - 87624/10^8` (fails at 87625), ten decimals `1 - 8762479/10^10` (fails at 8762483).
-/

namespace OAI
namespace PowerSaving
namespace BridgeRate
namespace B2Ge8
open Finset Binary Matrix RAM CB FoldRate
noncomputable section

/-- price of the blocks of ONE invocation of `E8` (all roles and scratch copies), by rank -/
def invPrice (φ : ℕ → ℝ) : ℝ := 2091 * φ 1 + 604 * φ 2 + 518 * φ 3 + 140 * φ 4 + 215 * φ 5 + 331 * φ 6 + 43 * φ 7 + 24 * φ 8 + 8 * φ 9

/-- price of ONE unit of the bridged word B_2 -/
def unitPrice (φ : ℕ → ℝ) : ℝ := 5 * invPrice φ + ((120:ℕ):ℝ) * BG.bankPrice 9 φ

/-- **The unit price is the price of the unit block list.** -/
theorem unit_cost (φ : ℕ → ℝ) : unitPrice φ = listCost φ BlockAccounting.blocksB2Ge8 := by
  unfold unitPrice invPrice
  simp only [BG.bankPrice, listCost, BlockAccounting.blocksB2Ge8, List.map_cons, List.map_nil,
    List.sum_cons, List.sum_nil]
  norm_num [bcost]
  try ring

theorem blocks_x : BlockAccounting.blocksB2Ge8 = BlockAccounting.blocksB2Ge8x := rfl

theorem unit_cost_x (φ : ℕ → ℝ) : unitPrice φ = listCost φ BlockAccounting.blocksB2Ge8x := by
  rw [unit_cost, blocks_x]

/-- one unit stands for `W * m - D` unit moves -/
theorem unit_tally : unitPrice (fun r => (r:ℝ)) = ((1263:ℕ):ℝ) * ((45:ℕ):ℝ) - ((120:ℕ):ℝ) := by
  rw [unit_cost]
  exact BlockAccounting.blocksB2Ge8_tally

end
end B2Ge8
end BridgeRate
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.BridgeRate.B2Ge8.unit_cost
#print axioms OAI.PowerSaving.BridgeRate.B2Ge8.unit_tally
