import Work.GCert.Data.Price
import Work.GCert.Data.Gen.P193Hist

/-!
# (key: gx-data) gcert/1 certificate `P193` (h = 22): the price of one invocation

GENERATED by checks/wht26/gx-data/py/gxgen.py from gcert1-p11-pr193.json.gz.  No `sorry`.
`rA_cost`, `rB_cost`, `rF_cost`: the price of the block rank lists of phase A, phase B and the final climbs
(lists `GXD.P193.rA / rB / rF`, counted by the kernel in `Gen.P193Hist`);
`inv_cost`: with the 22 scratch copies (22 * φ 20) the blocks of ONE invocation cost
`invPrice φ` = 29178 * φ 1 + 12398 * φ 2 + 9923 * φ 3 + 4209 * φ 4 + 1950 * φ 5 + 1605 * φ 6 + 706 * φ 7 + 1531 * φ 8 + 429 * φ 9 + 930 * φ 10 + 354 * φ 11 + 1197 * φ 12 + 127 * φ 13 + 742 * φ 14 + 1879 * φ 15 + 88 * φ 16 + 81 * φ 17 + 2653 * φ 18 + 167 * φ 19 + 22 * φ 20;  `inv_moves`: they stand for `R h + 2 v (h - 1) + cst = 262944` unit moves.
-/

namespace GXD.P193
open GXD OAI.PowerSaving.CB

/-- price of the blocks of phase A, from the kernel counts -/
theorem rA_cost (φ : ℕ → ℝ) : rcost φ rA = 9900 * φ 1 + 500 * φ 2 + 2402 * φ 3 + 82 * φ 4 + 242 * φ 5 + 175 * φ 6 + 88 * φ 7 + 68 * φ 8 + 110 * φ 9 + 132 * φ 10 + 10 * φ 11 + 67 * φ 12 + 3 * φ 13 + 19 * φ 15 := by
  rw [GXD.rcost_wsumK φ rA 19 rankBoundA]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, rankA0_ok, rankA1_ok, rankA2_ok, rankA3_ok, rankA4_ok, rankA5_ok, rankA6_ok, rankA7_ok, rankA8_ok, rankA9_ok, rankA10_ok, rankA11_ok, rankA12_ok, rankA13_ok, rankA14_ok, rankA15_ok, rankA16_ok, rankA17_ok, rankA18_ok, rankA19_ok]
  norm_num [bcost]

/-- price of the blocks of phase B, from the kernel counts -/
theorem rB_cost (φ : ℕ → ℝ) : rcost φ rB = 16638 * φ 1 + 10380 * φ 2 + 4111 * φ 3 + 3476 * φ 4 + 1531 * φ 5 + 1137 * φ 6 + 531 * φ 7 + 1346 * φ 8 + 293 * φ 9 + 629 * φ 10 + 343 * φ 11 + 1067 * φ 12 + 123 * φ 13 + 712 * φ 14 + 1860 * φ 15 + 81 * φ 16 + 39 * φ 17 + 2640 * φ 18 := by
  rw [GXD.rcost_wsumK φ rB 19 rankBoundB]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, rankB0_ok, rankB1_ok, rankB2_ok, rankB3_ok, rankB4_ok, rankB5_ok, rankB6_ok, rankB7_ok, rankB8_ok, rankB9_ok, rankB10_ok, rankB11_ok, rankB12_ok, rankB13_ok, rankB14_ok, rankB15_ok, rankB16_ok, rankB17_ok, rankB18_ok, rankB19_ok]
  norm_num [bcost]

/-- price of the blocks of the final climbs, from the kernel counts -/
theorem rF_cost (φ : ℕ → ℝ) : rcost φ rF = 2640 * φ 1 + 1518 * φ 2 + 3410 * φ 3 + 651 * φ 4 + 177 * φ 5 + 293 * φ 6 + 87 * φ 7 + 117 * φ 8 + 26 * φ 9 + 169 * φ 10 + 1 * φ 11 + 63 * φ 12 + 1 * φ 13 + 30 * φ 14 + 7 * φ 16 + 42 * φ 17 + 13 * φ 18 + 167 * φ 19 := by
  rw [GXD.rcost_wsumK φ rF 19 rankBoundF]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, rankF0_ok, rankF1_ok, rankF2_ok, rankF3_ok, rankF4_ok, rankF5_ok, rankF6_ok, rankF7_ok, rankF8_ok, rankF9_ok, rankF10_ok, rankF11_ok, rankF12_ok, rankF13_ok, rankF14_ok, rankF15_ok, rankF16_ok, rankF17_ok, rankF18_ok, rankF19_ok]
  norm_num [bcost]

/-- price of the blocks of ONE invocation (x roles, y roles, slots, scratch copies), by rank -/
def invPrice (φ : ℕ → ℝ) : ℝ := 29178 * φ 1 + 12398 * φ 2 + 9923 * φ 3 + 4209 * φ 4 + 1950 * φ 5 + 1605 * φ 6 + 706 * φ 7 + 1531 * φ 8 + 429 * φ 9 + 930 * φ 10 + 354 * φ 11 + 1197 * φ 12 + 127 * φ 13 + 742 * φ 14 + 1879 * φ 15 + 88 * φ 16 + 81 * φ 17 + 2653 * φ 18 + 167 * φ 19 + 22 * φ 20

/-- **Price of ONE invocation** in the shape of `GX.Lab.cost`: phase A, the scratch copies, phase B, final climbs. -/
theorem inv_cost (φ : ℕ → ℝ) : rcost φ rA + (22 * φ 20) + rcost φ rB + rcost φ rF = invPrice φ := by
  rw [rA_cost, rB_cost, rF_cost]
  unfold invPrice
  ring

theorem inv_moves : invPrice (fun r => (r:ℝ)) = 9412 * 22 + 2 * 1320 * (22 - 1) + 440 := by
  unfold invPrice
  norm_num

theorem inv_count : invPrice (fun _ => (1:ℝ)) = 70169 := by
  unfold invPrice
  norm_num

end GXD.P193
#print axioms GXD.P193.inv_cost
#print axioms GXD.P193.inv_moves
