import Work.GCert.Labels.Main
import Work.GCert.Data.P233Price
import Work.GCert.Data.Gen.P233Tab0
import Work.GCert.Data.Gen.P233Tab1
import Work.GCert.Data.Gen.P233Tab2
import Work.GCert.Data.Gen.P233Tab3
import Work.GCert.Data.Gen.P233Seg0
import Work.GCert.Data.Gen.P233Seg1
import Work.GCert.Data.Gen.P233Seg2
import Work.GCert.Data.Gen.P233Seg3
import Work.GCert.Data.Gen.P233Seg4
import Work.GCert.Data.Gen.P233Seg5
import Work.GCert.Data.Gen.P233SegF
import Work.GCert.Data.Gen.P233End
/-! # (key: gx-data) gcert/1 certificate `P233` (h = 22): THE LABEL HALF and its price
GENERATED by checks/wht26/gx-data/py/gxgen.py from gcert1-p11-pr233-flow.json.gz.  No `sorry`.
`v = 1320` ports, `R = 9412` slots, 22 scratch copies of rank 20, copy cost `cst = 440`, `N = 262944` unit moves.
* `aux : GLab.Aux`, `valid : GLab.Valid raw aux`: frame table (`tab<i>_ok` composed by `tabK_node`), the replays of phase A
  and phase B (`seg<i>_ok` composed by `Run.append`), the final climbs (`segF_ok`, `fin_ok`), the ends (`end_ok`);
* `lab_cost`, `lab_price`: for ANY scalar half `S` the label half `valid.lab S ..` costs
  `rcost rA + card C * bcost 20 + rcost rB + rcost rF` = `invPrice φ` = 29178 * φ 1 + 12667 * φ 2 + 9988 * φ 3 + 3839 * φ 4 + 1976 * φ 5 + 1491 * φ 6 + 642 * φ 7 + 1478 * φ 8 + 404 * φ 9 + 805 * φ 10 + 353 * φ 11 + 1141 * φ 12 + 168 * φ 13 + 725 * φ 14 + 605 * φ 15 + 81 * φ 16 + 39 * φ 17 + 2640 * φ 18 + 1441 * φ 19 + 22 * φ 20
  (`Gen.P233Hist`, `P233Price`) when there are 22 copies. -/
set_option maxRecDepth 100000
namespace GXD.P233
open GXD OAI.PowerSaving OAI.PowerSaving.CB
theorem raw_h : raw.h = 22 := rfl
theorem raw_v : raw.v = 1320 := rfl
theorem raw_R : raw.R = 9412 := rfl
/-- what the label checks read next to `raw` -/
noncomputable def aux : GLab.Aux := ⟨par, st0, st2, st6, st7, fins, rA, rB, rF⟩
theorem fin_ok : GLab.noAdds fins = true := by decide +kernel
theorem cen_ok : (raw.ret.map Prod.fst).all (fun r => Nat.beq (GLab.cdim (par.tab.get (st2.get r))) 20) = true := by
  decide +kernel
theorem tab_ok : GLab.tabK par.h par.tab = true := (GLab.tabK_node _ _ _ (GLab.tabK_node _ _ _ tab0_ok tab1_ok) (GLab.tabK_node _ _ _ tab2_ok tab3_ok))
theorem gatesA_eq : raw.gatesA = seg0 ++ (seg1) := by
  show List.flatten [seg0, seg1] = _
  simp only [List.flatten_cons, List.flatten_nil, List.append_nil]
/-- the replay of phase A, composed from its kernel-checked segments -/
theorem runA : GLab.Run par st0 raw.gatesA st2 rA := by
  rw [gatesA_eq]
  exact GLab.Run.append (GLab.Run.of_seg seg0_ok) (GLab.Run.of_seg seg1_ok)
theorem gatesB_eq : raw.gatesB = seg2 ++ (seg3 ++ (seg4 ++ (seg5))) := by
  show List.flatten [seg2, seg3, seg4, seg5] = _
  simp only [List.flatten_cons, List.flatten_nil, List.append_nil]
/-- the replay of phase B, composed from its kernel-checked segments -/
theorem runB : GLab.Run par st2 raw.gatesB st6 rB := by
  rw [gatesB_eq]
  exact GLab.Run.append (GLab.Run.of_seg seg2_ok) (GLab.Run.append (GLab.Run.of_seg seg3_ok) (GLab.Run.append (GLab.Run.of_seg seg4_ok) (GLab.Run.of_seg seg5_ok)))
/-- **the kernel-checked label facts** of the certificate -/
theorem valid : GLab.Valid raw aux where
  hn := rfl
  tab := tab_ok
  runA := runA
  runB := runB
  runF := GLab.Run.of_seg segF_ok
  fin := fin_ok
  ends := end_ok
theorem cen_dim (r : Nat) (hr : r ∈ raw.ret.map Prod.fst) : GLab.cdim (par.tab.get (st2.get r)) = 20 :=
  Nat.eq_of_beq_eq_true (List.all_eq_true.mp cen_ok r hr)
/-- price of the label half over ANY scalar half -/
theorem lab_cost {C : Type} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin raw.v) (Fin raw.R) C)
    {emb : CR.L3 (Fin raw.v) (Fin raw.R) → Nat} {un : Nat → CR.L3 (Fin raw.v) (Fin raw.R)}
    (Ro : GLab.Roles raw.v raw.R emb un) (cf : Co → SSC.Coef) (hMA) (hMAi) (hMB) (hMBi)
    (reg : C → Nat) (hCc) (hreg) (φ : ℕ → ℝ) :
    (valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg).cost φ
      = rcost φ rA + (Fintype.card C : ℝ) * bcost φ 20 + rcost φ rB + rcost φ rF := by
  obtain ⟨h1, h2, h3, h4⟩ := valid.lab_ranks S Ro cf hMA hMAi hMB hMBi reg hCc hreg
  have h5 : ∀ k, bcost φ (((valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg).cen k).dim) = bcost φ 20 :=
    fun k => by rw [h4 k]; exact congrArg (bcost φ) (cen_dim _ (hreg k))
  rw [GX.Lab.cost, h1, h2, h3, Finset.sum_congr rfl (fun k _ => h5 k), Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
  rfl
/-- **the label half costs one invocation price** (`invPrice`, by rank, from the kernel counts) -/
theorem lab_price {C : Type} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin raw.v) (Fin raw.R) C)
    {emb : CR.L3 (Fin raw.v) (Fin raw.R) → Nat} {un : Nat → CR.L3 (Fin raw.v) (Fin raw.R)}
    (Ro : GLab.Roles raw.v raw.R emb un) (cf : Co → SSC.Coef) (hMA) (hMAi) (hMB) (hMBi)
    (reg : C → Nat) (hCc) (hreg) (hC : Fintype.card C = 22) (φ : ℕ → ℝ) :
    (valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg).cost φ = invPrice φ := by
  rw [lab_cost S Ro cf hMA hMAi hMB hMBi reg hCc hreg φ, hC, ← inv_cost φ]
  norm_num [bcost]
end GXD.P233
#print axioms GXD.P233.valid
#print axioms GXD.P233.lab_price
