import Work.GCert.Scalar.Main
import Work.GCert.Data.Gen.P233Scal0
import Work.GCert.Data.Gen.P233Scal1
import Work.GCert.Data.Gen.P233YChk
/-! # (key: gx-data) gcert/1 certificate `P233` (h = 22): THE SCALAR HALF `scalOK : GS.ScalOK raw`
GENERATED by checks/wht26/gx-data/py/gxgen.py from gcert1-p11-pr233-flow.json.gz.  No `sorry`.
Kernel checks `scal<i>_ok` (2 source batches) and `ychk_ok`. -/
namespace GXD.P233
open GXD
theorem scalOK : GS.ScalOK raw where
  hv := by decide
  hs := fun t ht =>
    if h0 : t < 660 then ⟨0, 660, Nat.zero_le t, h0, GS.XRun.of_check scal0_ok⟩ else
    ⟨660, 660, Nat.le_of_not_lt h0, Nat.lt_of_lt_of_le ht (by decide), GS.XRun.of_check scal1_ok⟩
  hyc := fun t ht => ⟨0, 1320, Nat.zero_le t, Nat.lt_of_lt_of_le ht (by decide), GS.YRun.of_check ychk_ok⟩
end GXD.P233
#print axioms GXD.P233.scalOK
