import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `E8` (h = 9)

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 1263` live roles, label dimension `m = 45`, deficit `D = 120`.

* `blocksB2Ge8x`            the block list (rank, count) of ONE unit;
* `fold_B2Ge8x`             whole-block fact at `1 - 8762479/10^10`, fill parameter `s = 40` (slack 1.86e-10);
* `fold_B2Ge8x_sharp`       `W ≤ moment` at `1 - 8762483/10^10`: fails for every table (excess 3.08e-11);
* `foldRank_B2Ge8x`         per-rank fact at `1 - 5552387/10^10`, `s = 40` (slack 2.91e-09);
* `foldRank_B2Ge8x_sharp`   per-rank: fails for every table at `1 - 5552394/10^10`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `E8` (h = 9, m = 45): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; the kernel-counted list `GXD.E8.hist`), and for each of the v = 120 ports the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 783 slots shared by the five stages. -/
def blocksB2Ge8x : List (ℕ × ℕ) := [(1, 10455), (2, 3020), (3, 2590), (4, 940), (5, 1075), (6, 1655), (7, 215), (8, 360), (9, 40), (16, 240), (20, 240)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Ge8x_rank : (blocksB2Ge8x.map fun b => b.1 * b.2).sum = 1263 * 45 - 120 := by
  norm_num [blocksB2Ge8x]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Ge8x_tally : (blocksB2Ge8x.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((1263:ℕ):ℝ) * ((45:ℕ):ℝ) - ((120:ℕ):ℝ) := by
  norm_num [blocksB2Ge8x]

theorem blocksB2Ge8x_count : (blocksB2Ge8x.map fun b => b.2).sum = 20830 := by
  norm_num [blocksB2Ge8x]

theorem blocksB2Ge8x_proper : ∀ b ∈ blocksB2Ge8x, 1 ≤ b.1 ∧ b.1 < 45 := by
  decide

/-- **whole-block fact** of `blocksB2Ge8x` at exponent `1 - 8762479/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 45, W = 1263).  Relative slack of the rational certificate: 1.86e-10. -/
theorem fold_B2Ge8x :
    ((2:ℝ)^40 - 1) * moment 45 (1 - 8762479/(10:ℝ)^10) blocksB2Ge8x
      + ((1263:ℕ):ℝ) * (T 45 (1 - 8762479/(10:ℝ)^10) (45 - 1) 1 + T 45 (1 - 8762479/(10:ℝ)^10) 1 1)
      < (2:ℝ)^40 * ((1263:ℕ):ℝ) := by
  have hsum : moment 45 (1 - 8762479/(10:ℝ)^10) blocksB2Ge8x
      = T 45 (1 - 8762479/(10:ℝ)^10) 1 10455 + (T 45 (1 - 8762479/(10:ℝ)^10) 2 3020 + (T 45 (1 - 8762479/(10:ℝ)^10) 3 2590 + (T 45 (1 - 8762479/(10:ℝ)^10) 4 940 + (T 45 (1 - 8762479/(10:ℝ)^10) 5 1075 + (T 45 (1 - 8762479/(10:ℝ)^10) 6 1655 + (T 45 (1 - 8762479/(10:ℝ)^10) 7 215 + (T 45 (1 - 8762479/(10:ℝ)^10) 8 360 + (T 45 (1 - 8762479/(10:ℝ)^10) 9 40 + (T 45 (1 - 8762479/(10:ℝ)^10) 16 240 + (T 45 (1 - 8762479/(10:ℝ)^10) 20 240 + 0)))))))))) := rfl
  have b0 : T 45 (1 - 8762479/(10:ℝ)^10) 1 10455 ≤ ((2331095941537:ℝ)/10000000000) :=
    term_le 45 1 10455 (8762479/(10:ℝ)^10) ((951665622443:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 45 (1 - 8762479/(10:ℝ)^10) 2 3020 ≤ ((67294454461:ℝ)/500000000) :=
    term_le 45 2 3020 (8762479/(10:ℝ)^10) ((778378827303:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 45 (1 - 8762479/(10:ℝ)^10) 3 2590 ≤ ((1730768780589:ℝ)/10000000000) :=
    term_le 45 3 2590 (8762479/(10:ℝ)^10) ((169253137569:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 45 (1 - 8762479/(10:ℝ)^10) 4 940 ≤ ((167465903641:ℝ)/2000000000) :=
    term_le 45 4 940 (8762479/(10:ℝ)^10) ((605092032163:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 45 (1 - 8762479/(10:ℝ)^10) 5 1075 ≤ ((598373170031:ℝ)/5000000000) :=
    term_le 45 5 1075 (8762479/(10:ℝ)^10) ((1098612288669:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 45 (1 - 8762479/(10:ℝ)^10) 6 1655 ≤ ((221056609901:ℝ)/1000000000) :=
    term_le 45 6 1655 (8762479/(10:ℝ)^10) ((1967678731:ℝ)/976562500) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 45 (1 - 8762479/(10:ℝ)^10) 7 215 ≤ ((33499019441:ℝ)/1000000000) :=
    term_le 45 7 215 (8762479/(10:ℝ)^10) ((1860752340717:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 45 (1 - 8762479/(10:ℝ)^10) 8 360 ≤ ((640969356673:ℝ)/10000000000) :=
    term_le 45 8 360 (8762479/(10:ℝ)^10) ((431805237023:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 45 (1 - 8762479/(10:ℝ)^10) 9 40 ≤ ((20028225233:ℝ)/2500000000) :=
    term_le 45 9 40 (8762479/(10:ℝ)^10) ((402359478109:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 45 (1 - 8762479/(10:ℝ)^10) 16 240 ≤ ((854106893351:ℝ)/10000000000) :=
    term_le 45 16 240 (8762479/(10:ℝ)^10) ((258518441883:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 45 (1 - 8762479/(10:ℝ)^10) 20 240 ≤ ((1067424883667:ℝ)/10000000000) :=
    term_le 45 20 240 (8762479/(10:ℝ)^10) ((405465108109:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 45 (1 - 8762479/(10:ℝ)^10) 44 1 ≤ ((4888985161:ℝ)/5000000000) :=
    term_le 45 44 1 (8762479/(10:ℝ)^10) ((11236427927:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 6 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 45 (1 - 8762479/(10:ℝ)^10) 1 1 ≤ ((222964701:ℝ)/10000000000) :=
    term_le 45 1 1 (8762479/(10:ℝ)^10) ((951665622443:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^40 - 1) = 1099511627775 := by norm_num
  have e2 : (2:ℝ)^40 = 1099511627776 := by norm_num
  have e3 : ((1263:ℕ):ℝ) = 1263 := by norm_num
  have e4 : T 45 (1 - 8762479/(10:ℝ)^10) (45 - 1) 1 = T 45 (1 - 8762479/(10:ℝ)^10) 44 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 8762483/10^10` the moment of one unit is at least its number of live roles `1263`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 3.08e-11. -/
theorem fold_B2Ge8x_sharp : ((1263:ℕ):ℝ) ≤ moment 45 (1 - 8762483/(10:ℝ)^10) blocksB2Ge8x := by
  have hsum : moment 45 (1 - 8762483/(10:ℝ)^10) blocksB2Ge8x
      = T 45 (1 - 8762483/(10:ℝ)^10) 1 10455 + (T 45 (1 - 8762483/(10:ℝ)^10) 2 3020 + (T 45 (1 - 8762483/(10:ℝ)^10) 3 2590 + (T 45 (1 - 8762483/(10:ℝ)^10) 4 940 + (T 45 (1 - 8762483/(10:ℝ)^10) 5 1075 + (T 45 (1 - 8762483/(10:ℝ)^10) 6 1655 + (T 45 (1 - 8762483/(10:ℝ)^10) 7 215 + (T 45 (1 - 8762483/(10:ℝ)^10) 8 360 + (T 45 (1 - 8762483/(10:ℝ)^10) 9 40 + (T 45 (1 - 8762483/(10:ℝ)^10) 16 240 + (T 45 (1 - 8762483/(10:ℝ)^10) 20 240 + 0)))))))))) := rfl
  have c0 : ((23310959402953:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 1 10455 :=
    term_ge 45 1 10455 (8762483/(10:ℝ)^10) ((3806662489769:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 12 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((13458890893811:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 2 3020 :=
    term_ge 45 2 3020 (8762483/(10:ℝ)^10) ((3113515309209:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((8653843905907:ℝ)/50000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 3 2590 :=
    term_ge 45 3 2590 (8762483/(10:ℝ)^10) ((2708050201101:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((8373295185727:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 4 940 :=
    term_ge 45 4 940 (8762483/(10:ℝ)^10) ((2420368128649:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((11967463406397:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 5 1075 :=
    term_ge 45 5 1075 (8762483/(10:ℝ)^10) ((439444915467:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((22105661001167:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 6 1655 :=
    term_ge 45 6 1655 (8762483/(10:ℝ)^10) ((2014903020541:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((418737743223:ℝ)/12500000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 7 215 :=
    term_ge 45 7 215 (8762483/(10:ℝ)^10) ((930376170357:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((3204846784959:ℝ)/50000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 8 360 :=
    term_ge 45 8 360 (8762483/(10:ℝ)^10) ((1727220948089:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((801129009703:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 9 40 :=
    term_ge 45 9 40 (8762483/(10:ℝ)^10) ((1609437912433:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((8541068936689:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 16 240 :=
    term_ge 45 16 240 (8762483/(10:ℝ)^10) ((1034073767529:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((10674248839919:ℝ)/100000000000) ≤ T 45 (1 - 8762483/(10:ℝ)^10) 20 240 :=
    term_ge 45 20 240 (8762483/(10:ℝ)^10) ((162186043243:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((1263:ℕ):ℝ) = 1263 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 5552387/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 45, W = 1263, D = 120).  Relative slack: 2.91e-09. -/
theorem foldRank_B2Ge8x :
    (2:ℝ)^40 * ((1263:ℕ):ℝ) * (((45:ℕ):ℝ) - ((45:ℕ):ℝ)^(1 - 5552387/(10:ℝ)^10)) < ((2:ℝ)^40 - 1) * ((120:ℕ):ℝ) :=
  FoldRate.rank_fact3 45 1263 120 40 (5552387/(10:ℝ)^10) ((951665622443:ℝ)/250000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 5552394/10^10` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Ge8x_sharp :
    ((120:ℕ):ℝ) ≤ ((1263:ℕ):ℝ) * (((45:ℕ):ℝ) - ((45:ℕ):ℝ)^(1 - 5552394/(10:ℝ)^10)) :=
  FoldRate.rank_fact_sharp 45 1263 120 (5552394/(10:ℝ)^10) ((3806662489769:ℝ)/1000000000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 3 12 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ge8x
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ge8x_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ge8x
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ge8x_sharp
