import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `P233` (h = 22)

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 14692` live roles, label dimension `m = 110`, deficit `D = 3080`.

* `blocksB2Gp233x`            the block list (rank, count) of ONE unit;
* `fold_B2Gp233x`             whole-block fact at `1 - 7547361/10^10`, fill parameter `s = 40` (slack 1.72e-10);
* `fold_B2Gp233x_sharp`       `W ≤ moment` at `1 - 7547365/10^10`: fails for every table (excess 2.04e-10);
* `foldRank_B2Gp233x`         per-rank fact at `1 - 4058344/10^10`, `s = 40` (slack 1.10e-07);
* `foldRank_B2Gp233x_sharp`   per-rank: fails for every table at `1 - 4058349/10^10`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `P233` (h = 22, m = 110): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; the kernel-counted list `GXD.P233.hist`), and for each of the v = 1320 ports the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 9412 slots shared by the five stages. -/
def blocksB2Gp233x : List (ℕ × ℕ) := [(1, 145890), (2, 63335), (3, 49940), (4, 21835), (5, 9880), (6, 7455), (7, 3210), (8, 7390), (9, 2020), (10, 4025), (11, 1765), (12, 5705), (13, 840), (14, 3625), (15, 3025), (16, 405), (17, 195), (18, 13200), (19, 7205), (20, 110), (21, 2640), (42, 2640), (46, 2640)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Gp233x_rank : (blocksB2Gp233x.map fun b => b.1 * b.2).sum = 14692 * 110 - 3080 := by
  norm_num [blocksB2Gp233x]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Gp233x_tally : (blocksB2Gp233x.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((14692:ℕ):ℝ) * ((110:ℕ):ℝ) - ((3080:ℕ):ℝ) := by
  norm_num [blocksB2Gp233x]

theorem blocksB2Gp233x_count : (blocksB2Gp233x.map fun b => b.2).sum = 358975 := by
  norm_num [blocksB2Gp233x]

theorem blocksB2Gp233x_proper : ∀ b ∈ blocksB2Gp233x, 1 ≤ b.1 ∧ b.1 < 110 := by
  decide

/-- **whole-block fact** of `blocksB2Gp233x` at exponent `1 - 7547361/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 110, W = 14692).  Relative slack of the rational certificate: 1.72e-10. -/
theorem fold_B2Gp233x :
    ((2:ℝ)^40 - 1) * moment 110 (1 - 7547361/(10:ℝ)^10) blocksB2Gp233x
      + ((14692:ℕ):ℝ) * (T 110 (1 - 7547361/(10:ℝ)^10) (110 - 1) 1 + T 110 (1 - 7547361/(10:ℝ)^10) 1 1)
      < (2:ℝ)^40 * ((14692:ℕ):ℝ) := by
  have hsum : moment 110 (1 - 7547361/(10:ℝ)^10) blocksB2Gp233x
      = T 110 (1 - 7547361/(10:ℝ)^10) 1 145890 + (T 110 (1 - 7547361/(10:ℝ)^10) 2 63335 + (T 110 (1 - 7547361/(10:ℝ)^10) 3 49940 + (T 110 (1 - 7547361/(10:ℝ)^10) 4 21835 + (T 110 (1 - 7547361/(10:ℝ)^10) 5 9880 + (T 110 (1 - 7547361/(10:ℝ)^10) 6 7455 + (T 110 (1 - 7547361/(10:ℝ)^10) 7 3210 + (T 110 (1 - 7547361/(10:ℝ)^10) 8 7390 + (T 110 (1 - 7547361/(10:ℝ)^10) 9 2020 + (T 110 (1 - 7547361/(10:ℝ)^10) 10 4025 + (T 110 (1 - 7547361/(10:ℝ)^10) 11 1765 + (T 110 (1 - 7547361/(10:ℝ)^10) 12 5705 + (T 110 (1 - 7547361/(10:ℝ)^10) 13 840 + (T 110 (1 - 7547361/(10:ℝ)^10) 14 3625 + (T 110 (1 - 7547361/(10:ℝ)^10) 15 3025 + (T 110 (1 - 7547361/(10:ℝ)^10) 16 405 + (T 110 (1 - 7547361/(10:ℝ)^10) 17 195 + (T 110 (1 - 7547361/(10:ℝ)^10) 18 13200 + (T 110 (1 - 7547361/(10:ℝ)^10) 19 7205 + (T 110 (1 - 7547361/(10:ℝ)^10) 20 110 + (T 110 (1 - 7547361/(10:ℝ)^10) 21 2640 + (T 110 (1 - 7547361/(10:ℝ)^10) 42 2640 + (T 110 (1 - 7547361/(10:ℝ)^10) 46 2640 + 0)))))))))))))))))))))) := rfl
  have b0 : T 110 (1 - 7547361/(10:ℝ)^10) 1 145890 ≤ ((1330986201013:ℝ)/1000000000) :=
    term_le 110 1 145890 (7547361/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 110 (1 - 7547361/(10:ℝ)^10) 2 63335 ≤ ((1155033553559:ℝ)/1000000000) :=
    term_le 110 2 63335 (7547361/(10:ℝ)^10) ((2003666592617:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 26 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 110 (1 - 7547361/(10:ℝ)^10) 3 49940 ≤ ((42678361907:ℝ)/31250000) :=
    term_le 110 3 49940 (7547361/(10:ℝ)^10) ((1800934038563:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 110 (1 - 7547361/(10:ℝ)^10) 4 21835 ≤ ((159197709461:ℝ)/200000000) :=
    term_le 110 4 21835 (7547361/(10:ℝ)^10) ((1657093002337:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 110 (1 - 7547361/(10:ℝ)^10) 5 9880 ≤ ((450139826211:ℝ)/1000000000) :=
    term_le 110 5 9880 (7547361/(10:ℝ)^10) ((38638030667:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 110 (1 - 7547361/(10:ℝ)^10) 6 7455 ≤ ((203765020027:ℝ)/500000000) :=
    term_le 110 6 7455 (7547361/(10:ℝ)^10) ((1454360448283:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 110 (1 - 7547361/(10:ℝ)^10) 7 3210 ≤ ((51174461683:ℝ)/250000000) :=
    term_le 110 7 3210 (7547361/(10:ℝ)^10) ((2754570216739:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 110 (1 - 7547361/(10:ℝ)^10) 8 7390 ≤ ((538518786591:ℝ)/1000000000) :=
    term_le 110 8 7390 (7547361/(10:ℝ)^10) ((1310519412057:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 110 (1 - 7547361/(10:ℝ)^10) 9 2020 ≤ ((165585271839:ℝ)/1000000000) :=
    term_le 110 9 2020 (7547361/(10:ℝ)^10) ((1251627894229:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 110 (1 - 7547361/(10:ℝ)^10) 10 4025 ≤ ((366571904891:ℝ)/1000000000) :=
    term_le 110 10 4025 (7547361/(10:ℝ)^10) ((2997369091:ℝ)/1250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 110 (1 - 7547361/(10:ℝ)^10) 11 1765 ≤ ((176806996213:ℝ)/1000000000) :=
    term_le 110 11 1765 (7547361/(10:ℝ)^10) ((575646273249:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 110 (1 - 7547361/(10:ℝ)^10) 12 5705 ≤ ((124681041417:ℝ)/200000000) :=
    term_le 110 12 5705 (7547361/(10:ℝ)^10) ((1107786858003:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 110 (1 - 7547361/(10:ℝ)^10) 13 840 ≤ ((49716430177:ℝ)/500000000) :=
    term_le 110 13 840 (7547361/(10:ℝ)^10) ((533882752083:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b13 : T 110 (1 - 7547361/(10:ℝ)^10) 14 3625 ≤ ((28880124919:ℝ)/62500000) :=
    term_le 110 14 3625 (7547361/(10:ℝ)^10) ((2061423036179:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b14 : T 110 (1 - 7547361/(10:ℝ)^10) 15 3025 ≤ ((413120767279:ℝ)/1000000000) :=
    term_le 110 15 3025 (7547361/(10:ℝ)^10) ((498107541173:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b15 : T 110 (1 - 7547361/(10:ℝ)^10) 16 405 ≤ ((58994868949:ℝ)/1000000000) :=
    term_le 110 16 405 (7547361/(10:ℝ)^10) ((963945821777:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b16 : T 110 (1 - 7547361/(10:ℝ)^10) 17 195 ≤ ((15089432287:ℝ)/500000000) :=
    term_le 110 17 195 (7547361/(10:ℝ)^10) ((933633510869:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b17 : T 110 (1 - 7547361/(10:ℝ)^10) 18 13200 ≤ ((86518116409:ℝ)/40000000) :=
    term_le 110 18 13200 (7547361/(10:ℝ)^10) ((905054303949:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b18 : T 110 (1 - 7547361/(10:ℝ)^10) 19 7205 ≤ ((1246150489027:ℝ)/1000000000) :=
    term_le 110 19 7205 (7547361/(10:ℝ)^10) ((1756041386627:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b19 : T 110 (1 - 7547361/(10:ℝ)^10) 20 110 ≤ ((20025749263:ℝ)/1000000000) :=
    term_le 110 20 110 (7547361/(10:ℝ)^10) ((21309351153:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b20 : T 110 (1 - 7547361/(10:ℝ)^10) 21 2640 ≤ ((504630298709:ℝ)/1000000000) :=
    term_le 110 21 2640 (7547361/(10:ℝ)^10) ((165595792807:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b21 : T 110 (1 - 7547361/(10:ℝ)^10) 42 2640 ≤ ((201746549519:ℝ)/200000000) :=
    term_le 110 42 2640 (7547361/(10:ℝ)^10) ((962810747511:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b22 : T 110 (1 - 7547361/(10:ℝ)^10) 46 2640 ≤ ((276181670071:ℝ)/250000000) :=
    term_le 110 46 2640 (7547361/(10:ℝ)^10) ((174367793861:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b23 : T 110 (1 - 7547361/(10:ℝ)^10) 109 1 ≤ ((990915921:ℝ)/1000000000) :=
    term_le 110 109 1 (7547361/(10:ℝ)^10) ((1826496713:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 5 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b24 : T 110 (1 - 7547361/(10:ℝ)^10) 1 1 ≤ ((4561609:ℝ)/500000000) :=
    term_le 110 1 1 (7547361/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^40 - 1) = 1099511627775 := by norm_num
  have e2 : (2:ℝ)^40 = 1099511627776 := by norm_num
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  have e4 : T 110 (1 - 7547361/(10:ℝ)^10) (110 - 1) 1 = T 110 (1 - 7547361/(10:ℝ)^10) 109 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 7547365/10^10` the moment of one unit is at least its number of live roles `14692`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 2.04e-10. -/
theorem fold_B2Gp233x_sharp : ((14692:ℕ):ℝ) ≤ moment 110 (1 - 7547365/(10:ℝ)^10) blocksB2Gp233x := by
  have hsum : moment 110 (1 - 7547365/(10:ℝ)^10) blocksB2Gp233x
      = T 110 (1 - 7547365/(10:ℝ)^10) 1 145890 + (T 110 (1 - 7547365/(10:ℝ)^10) 2 63335 + (T 110 (1 - 7547365/(10:ℝ)^10) 3 49940 + (T 110 (1 - 7547365/(10:ℝ)^10) 4 21835 + (T 110 (1 - 7547365/(10:ℝ)^10) 5 9880 + (T 110 (1 - 7547365/(10:ℝ)^10) 6 7455 + (T 110 (1 - 7547365/(10:ℝ)^10) 7 3210 + (T 110 (1 - 7547365/(10:ℝ)^10) 8 7390 + (T 110 (1 - 7547365/(10:ℝ)^10) 9 2020 + (T 110 (1 - 7547365/(10:ℝ)^10) 10 4025 + (T 110 (1 - 7547365/(10:ℝ)^10) 11 1765 + (T 110 (1 - 7547365/(10:ℝ)^10) 12 5705 + (T 110 (1 - 7547365/(10:ℝ)^10) 13 840 + (T 110 (1 - 7547365/(10:ℝ)^10) 14 3625 + (T 110 (1 - 7547365/(10:ℝ)^10) 15 3025 + (T 110 (1 - 7547365/(10:ℝ)^10) 16 405 + (T 110 (1 - 7547365/(10:ℝ)^10) 17 195 + (T 110 (1 - 7547365/(10:ℝ)^10) 18 13200 + (T 110 (1 - 7547365/(10:ℝ)^10) 19 7205 + (T 110 (1 - 7547365/(10:ℝ)^10) 20 110 + (T 110 (1 - 7547365/(10:ℝ)^10) 21 2640 + (T 110 (1 - 7547365/(10:ℝ)^10) 42 2640 + (T 110 (1 - 7547365/(10:ℝ)^10) 46 2640 + 0)))))))))))))))))))))) := rfl
  have c0 : ((53239448009:ℝ)/40000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 1 145890 :=
    term_ge 110 1 145890 (7547365/(10:ℝ)^10) ((4700480365791:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((1155033553639:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 2 63335 :=
    term_ge 110 2 63335 (7547365/(10:ℝ)^10) ((4007333185231:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((136570758147:ℝ)/100000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 3 49940 :=
    term_ge 110 3 49940 (7547365/(10:ℝ)^10) ((3601868077123:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((795988547669:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 4 21835 :=
    term_ge 110 4 21835 (7547365/(10:ℝ)^10) ((3314186004671:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((9002796529:ℝ)/20000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 5 9880 :=
    term_ge 110 5 9880 (7547365/(10:ℝ)^10) ((3091042453357:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((12735313759:ℝ)/31250000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 6 7455 :=
    term_ge 110 6 7455 (7547365/(10:ℝ)^10) ((2908720896563:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((102348923427:ℝ)/500000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 7 3210 :=
    term_ge 110 7 3210 (7547365/(10:ℝ)^10) ((86080319273:ℝ)/31250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((538518786923:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 8 7390 :=
    term_ge 110 8 7390 (7547365/(10:ℝ)^10) ((2621038824111:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((82792635971:ℝ)/500000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 9 2020 :=
    term_ge 110 9 2020 (7547365/(10:ℝ)^10) ((500651157691:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((366571905121:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 10 4025 :=
    term_ge 110 10 4025 (7547365/(10:ℝ)^10) ((2397895272797:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((176806996323:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 11 1765 :=
    term_ge 110 11 1765 (7547365/(10:ℝ)^10) ((2302585092993:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c11 : ((24936208299:ℝ)/40000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 12 5705 :=
    term_ge 110 12 5705 (7547365/(10:ℝ)^10) ((2215573716003:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c12 : ((49716430207:ℝ)/500000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 13 840 :=
    term_ge 110 13 840 (7547365/(10:ℝ)^10) ((2135531008329:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c13 : ((462081998987:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 14 3625 :=
    term_ge 110 14 3625 (7547365/(10:ℝ)^10) ((128838939761:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c14 : ((41312076753:ℝ)/100000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 15 3025 :=
    term_ge 110 15 3025 (7547365/(10:ℝ)^10) ((1992430164689:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 12 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c15 : ((58994868983:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 16 405 :=
    term_ge 110 16 405 (7547365/(10:ℝ)^10) ((1927891643551:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c16 : ((30178864591:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 17 195 :=
    term_ge 110 17 195 (7547365/(10:ℝ)^10) ((373453404347:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c17 : ((540738227871:ℝ)/250000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 18 13200 :=
    term_ge 110 18 13200 (7547365/(10:ℝ)^10) ((362021721579:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c18 : ((62307524487:ℝ)/50000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 19 7205 :=
    term_ge 110 19 7205 (7547365/(10:ℝ)^10) ((13719073333:ℝ)/7812500000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c19 : ((20025749273:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 20 110 :=
    term_ge 110 20 110 (7547365/(10:ℝ)^10) ((1704748092237:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c20 : ((126157574747:ℝ)/250000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 21 2640 :=
    term_ge 110 21 2640 (7547365/(10:ℝ)^10) ((1655957928067:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c21 : ((1008732747961:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 42 2640 :=
    term_ge 110 42 2640 (7547365/(10:ℝ)^10) ((240702686877:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c22 : ((1104726680651:ℝ)/1000000000) ≤ T 110 (1 - 7547365/(10:ℝ)^10) 46 2640 :=
    term_ge 110 46 2640 (7547365/(10:ℝ)^10) ((435919484651:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 4058344/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 110, W = 14692, D = 3080).  Relative slack: 1.10e-07. -/
theorem foldRank_B2Gp233x :
    (2:ℝ)^40 * ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 4058344/(10:ℝ)^10)) < ((2:ℝ)^40 - 1) * ((3080:ℕ):ℝ) :=
  FoldRate.rank_fact3 110 14692 3080 40 (4058344/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 4058349/10^10` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Gp233x_sharp :
    ((3080:ℕ):ℝ) ≤ ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 4058349/(10:ℝ)^10)) :=
  FoldRate.rank_fact_sharp 110 14692 3080 (4058349/(10:ℝ)^10) ((4700480365791:ℝ)/1000000000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp233x
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp233x_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp233x
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp233x_sharp
