import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `P193` (h = 22)

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 14692` live roles, label dimension `m = 110`, deficit `D = 3080`.

* `blocksB2Gp193x`            the block list (rank, count) of ONE unit;
* `fold_B2Gp193x`             whole-block fact at `1 - 7474547/10^10`, fill parameter `s = 40` (slack 2.37e-12);
* `fold_B2Gp193x_sharp`       `W ≤ moment` at `1 - 7474550/10^10`: fails for every table (excess 1.40e-10);
* `foldRank_B2Gp193x`         per-rank fact at `1 - 4058344/10^10`, `s = 40` (slack 1.10e-07);
* `foldRank_B2Gp193x_sharp`   per-rank: fails for every table at `1 - 4058349/10^10`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `P193` (h = 22, m = 110): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; the kernel-counted list `GXD.P193.hist`), and for each of the v = 1320 ports the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 9412 slots shared by the five stages. -/
def blocksB2Gp193x : List (ℕ × ℕ) := [(1, 145890), (2, 61990), (3, 49615), (4, 23685), (5, 9750), (6, 8025), (7, 3530), (8, 7655), (9, 2145), (10, 4650), (11, 1770), (12, 5985), (13, 635), (14, 3710), (15, 9395), (16, 440), (17, 405), (18, 13265), (19, 835), (20, 110), (21, 2640), (42, 2640), (46, 2640)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Gp193x_rank : (blocksB2Gp193x.map fun b => b.1 * b.2).sum = 14692 * 110 - 3080 := by
  norm_num [blocksB2Gp193x]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Gp193x_tally : (blocksB2Gp193x.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((14692:ℕ):ℝ) * ((110:ℕ):ℝ) - ((3080:ℕ):ℝ) := by
  norm_num [blocksB2Gp193x]

theorem blocksB2Gp193x_count : (blocksB2Gp193x.map fun b => b.2).sum = 361405 := by
  norm_num [blocksB2Gp193x]

theorem blocksB2Gp193x_proper : ∀ b ∈ blocksB2Gp193x, 1 ≤ b.1 ∧ b.1 < 110 := by
  decide

/-- **whole-block fact** of `blocksB2Gp193x` at exponent `1 - 7474547/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 110, W = 14692).  Relative slack of the rational certificate: 2.37e-12. -/
theorem fold_B2Gp193x :
    ((2:ℝ)^40 - 1) * moment 110 (1 - 7474547/(10:ℝ)^10) blocksB2Gp193x
      + ((14692:ℕ):ℝ) * (T 110 (1 - 7474547/(10:ℝ)^10) (110 - 1) 1 + T 110 (1 - 7474547/(10:ℝ)^10) 1 1)
      < (2:ℝ)^40 * ((14692:ℕ):ℝ) := by
  have hsum : moment 110 (1 - 7474547/(10:ℝ)^10) blocksB2Gp193x
      = T 110 (1 - 7474547/(10:ℝ)^10) 1 145890 + (T 110 (1 - 7474547/(10:ℝ)^10) 2 61990 + (T 110 (1 - 7474547/(10:ℝ)^10) 3 49615 + (T 110 (1 - 7474547/(10:ℝ)^10) 4 23685 + (T 110 (1 - 7474547/(10:ℝ)^10) 5 9750 + (T 110 (1 - 7474547/(10:ℝ)^10) 6 8025 + (T 110 (1 - 7474547/(10:ℝ)^10) 7 3530 + (T 110 (1 - 7474547/(10:ℝ)^10) 8 7655 + (T 110 (1 - 7474547/(10:ℝ)^10) 9 2145 + (T 110 (1 - 7474547/(10:ℝ)^10) 10 4650 + (T 110 (1 - 7474547/(10:ℝ)^10) 11 1770 + (T 110 (1 - 7474547/(10:ℝ)^10) 12 5985 + (T 110 (1 - 7474547/(10:ℝ)^10) 13 635 + (T 110 (1 - 7474547/(10:ℝ)^10) 14 3710 + (T 110 (1 - 7474547/(10:ℝ)^10) 15 9395 + (T 110 (1 - 7474547/(10:ℝ)^10) 16 440 + (T 110 (1 - 7474547/(10:ℝ)^10) 17 405 + (T 110 (1 - 7474547/(10:ℝ)^10) 18 13265 + (T 110 (1 - 7474547/(10:ℝ)^10) 19 835 + (T 110 (1 - 7474547/(10:ℝ)^10) 20 110 + (T 110 (1 - 7474547/(10:ℝ)^10) 21 2640 + (T 110 (1 - 7474547/(10:ℝ)^10) 42 2640 + (T 110 (1 - 7474547/(10:ℝ)^10) 46 2640 + 0)))))))))))))))))))))) := rfl
  have b0 : T 110 (1 - 7474547/(10:ℝ)^10) 1 145890 ≤ ((16636758090767:ℝ)/12500000000) :=
    term_le 110 1 145890 (7474547/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 110 (1 - 7474547/(10:ℝ)^10) 2 61990 ≤ ((22609438945563:ℝ)/20000000000) :=
    term_le 110 2 61990 (7474547/(10:ℝ)^10) ((2003666592617:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 26 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 110 (1 - 7474547/(10:ℝ)^10) 3 49615 ≤ ((135678423202471:ℝ)/100000000000) :=
    term_le 110 3 49615 (7474547/(10:ℝ)^10) ((1800934038563:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 110 (1 - 7474547/(10:ℝ)^10) 4 23685 ≤ ((43170446048157:ℝ)/50000000000) :=
    term_le 110 4 23685 (7474547/(10:ℝ)^10) ((1657093002337:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 110 (1 - 7474547/(10:ℝ)^10) 5 9750 ≤ ((44420693582197:ℝ)/100000000000) :=
    term_le 110 5 9750 (7474547/(10:ℝ)^10) ((38638030667:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 110 (1 - 7474547/(10:ℝ)^10) 6 8025 ≤ ((43867998737293:ℝ)/100000000000) :=
    term_le 110 6 8025 (7474547/(10:ℝ)^10) ((1454360448283:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 110 (1 - 7474547/(10:ℝ)^10) 7 3530 ≤ ((2250993477097:ℝ)/10000000000) :=
    term_le 110 7 3530 (7474547/(10:ℝ)^10) ((2754570216739:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 110 (1 - 7474547/(10:ℝ)^10) 8 7655 ≤ ((55781903078171:ℝ)/100000000000) :=
    term_le 110 8 7655 (7474547/(10:ℝ)^10) ((1310519412057:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 110 (1 - 7474547/(10:ℝ)^10) 9 2145 ≤ ((17582868029823:ℝ)/100000000000) :=
    term_le 110 9 2145 (7474547/(10:ℝ)^10) ((1251627894229:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 110 (1 - 7474547/(10:ℝ)^10) 10 4650 ≤ ((10587140349809:ℝ)/25000000000) :=
    term_le 110 10 4650 (7474547/(10:ℝ)^10) ((2997369091:ℝ)/1250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 110 (1 - 7474547/(10:ℝ)^10) 11 1770 ≤ ((17730489316207:ℝ)/100000000000) :=
    term_le 110 11 1770 (7474547/(10:ℝ)^10) ((575646273249:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 110 (1 - 7474547/(10:ℝ)^10) 12 5985 ≤ ((65399123107589:ℝ)/100000000000) :=
    term_le 110 12 5985 (7474547/(10:ℝ)^10) ((1107786858003:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 110 (1 - 7474547/(10:ℝ)^10) 13 635 ≤ ((3758266936203:ℝ)/50000000000) :=
    term_le 110 13 635 (7474547/(10:ℝ)^10) ((533882752083:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b13 : T 110 (1 - 7474547/(10:ℝ)^10) 14 3710 ≤ ((47290992642379:ℝ)/100000000000) :=
    term_le 110 14 3710 (7474547/(10:ℝ)^10) ((2061423036179:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b14 : T 110 (1 - 7474547/(10:ℝ)^10) 15 9395 ≤ ((128304571925681:ℝ)/100000000000) :=
    term_le 110 15 9395 (7474547/(10:ℝ)^10) ((498107541173:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b15 : T 110 (1 - 7474547/(10:ℝ)^10) 16 440 ≤ ((6409229123791:ℝ)/100000000000) :=
    term_le 110 16 440 (7474547/(10:ℝ)^10) ((963945821777:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b16 : T 110 (1 - 7474547/(10:ℝ)^10) 17 405 ≤ ((1253566561349:ℝ)/20000000000) :=
    term_le 110 17 405 (7474547/(10:ℝ)^10) ((933633510869:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b17 : T 110 (1 - 7474547/(10:ℝ)^10) 18 13265 ≤ ((217357516651669:ℝ)/100000000000) :=
    term_le 110 18 13265 (7474547/(10:ℝ)^10) ((905054303949:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b18 : T 110 (1 - 7474547/(10:ℝ)^10) 19 835 ≤ ((14441670418763:ℝ)/100000000000) :=
    term_le 110 19 835 (7474547/(10:ℝ)^10) ((1756041386627:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b19 : T 110 (1 - 7474547/(10:ℝ)^10) 20 110 ≤ ((2002550068509:ℝ)/100000000000) :=
    term_le 110 20 110 (7474547/(10:ℝ)^10) ((21309351153:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b20 : T 110 (1 - 7474547/(10:ℝ)^10) 21 2640 ≤ ((25231210703361:ℝ)/50000000000) :=
    term_le 110 21 2640 (7474547/(10:ℝ)^10) ((165595792807:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b21 : T 110 (1 - 7474547/(10:ℝ)^10) 42 2640 ≤ ((100872567578631:ℝ)/100000000000) :=
    term_le 110 42 2640 (7474547/(10:ℝ)^10) ((962810747511:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b22 : T 110 (1 - 7474547/(10:ℝ)^10) 46 2640 ≤ ((22094393345401:ℝ)/20000000000) :=
    term_le 110 46 2640 (7474547/(10:ℝ)^10) ((174367793861:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b23 : T 110 (1 - 7474547/(10:ℝ)^10) 109 1 ≤ ((198183171:ℝ)/200000000) :=
    term_le 110 109 1 (7474547/(10:ℝ)^10) ((1826496713:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 5 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b24 : T 110 (1 - 7474547/(10:ℝ)^10) 1 1 ≤ ((456145263:ℝ)/50000000000) :=
    term_le 110 1 1 (7474547/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^40 - 1) = 1099511627775 := by norm_num
  have e2 : (2:ℝ)^40 = 1099511627776 := by norm_num
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  have e4 : T 110 (1 - 7474547/(10:ℝ)^10) (110 - 1) 1 = T 110 (1 - 7474547/(10:ℝ)^10) 109 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 7474550/10^10` the moment of one unit is at least its number of live roles `14692`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 1.40e-10. -/
theorem fold_B2Gp193x_sharp : ((14692:ℕ):ℝ) ≤ moment 110 (1 - 7474550/(10:ℝ)^10) blocksB2Gp193x := by
  have hsum : moment 110 (1 - 7474550/(10:ℝ)^10) blocksB2Gp193x
      = T 110 (1 - 7474550/(10:ℝ)^10) 1 145890 + (T 110 (1 - 7474550/(10:ℝ)^10) 2 61990 + (T 110 (1 - 7474550/(10:ℝ)^10) 3 49615 + (T 110 (1 - 7474550/(10:ℝ)^10) 4 23685 + (T 110 (1 - 7474550/(10:ℝ)^10) 5 9750 + (T 110 (1 - 7474550/(10:ℝ)^10) 6 8025 + (T 110 (1 - 7474550/(10:ℝ)^10) 7 3530 + (T 110 (1 - 7474550/(10:ℝ)^10) 8 7655 + (T 110 (1 - 7474550/(10:ℝ)^10) 9 2145 + (T 110 (1 - 7474550/(10:ℝ)^10) 10 4650 + (T 110 (1 - 7474550/(10:ℝ)^10) 11 1770 + (T 110 (1 - 7474550/(10:ℝ)^10) 12 5985 + (T 110 (1 - 7474550/(10:ℝ)^10) 13 635 + (T 110 (1 - 7474550/(10:ℝ)^10) 14 3710 + (T 110 (1 - 7474550/(10:ℝ)^10) 15 9395 + (T 110 (1 - 7474550/(10:ℝ)^10) 16 440 + (T 110 (1 - 7474550/(10:ℝ)^10) 17 405 + (T 110 (1 - 7474550/(10:ℝ)^10) 18 13265 + (T 110 (1 - 7474550/(10:ℝ)^10) 19 835 + (T 110 (1 - 7474550/(10:ℝ)^10) 20 110 + (T 110 (1 - 7474550/(10:ℝ)^10) 21 2640 + (T 110 (1 - 7474550/(10:ℝ)^10) 42 2640 + (T 110 (1 - 7474550/(10:ℝ)^10) 46 2640 + 0)))))))))))))))))))))) := rfl
  have c0 : ((665470322971:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 1 145890 :=
    term_ge 110 1 145890 (7474550/(10:ℝ)^10) ((4700480365791:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((565235973477:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 2 61990 :=
    term_ge 110 2 61990 (7474550/(10:ℝ)^10) ((4007333185231:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((1356784232023:ℝ)/1000000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 3 49615 :=
    term_ge 110 3 49615 (7474550/(10:ℝ)^10) ((3601868077123:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((431704460547:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 4 23685 :=
    term_ge 110 4 23685 (7474550/(10:ℝ)^10) ((3314186004671:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((44420693593:ℝ)/100000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 5 9750 :=
    term_ge 110 5 9750 (7474550/(10:ℝ)^10) ((3091042453357:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((87735997501:ℝ)/200000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 6 8025 :=
    term_ge 110 6 8025 (7474550/(10:ℝ)^10) ((2908720896563:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((112549673893:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 7 3530 :=
    term_ge 110 7 3530 (7474550/(10:ℝ)^10) ((86080319273:ℝ)/31250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((557819030987:ℝ)/1000000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 8 7655 :=
    term_ge 110 8 7655 (7474550/(10:ℝ)^10) ((2621038824111:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((87914340183:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 9 2145 :=
    term_ge 110 9 2145 (7474550/(10:ℝ)^10) ((500651157691:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((423485614161:ℝ)/1000000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 10 4650 :=
    term_ge 110 10 4650 (7474550/(10:ℝ)^10) ((2397895272797:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((88652446617:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 11 1770 :=
    term_ge 110 11 1770 (7474550/(10:ℝ)^10) ((2302585092993:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c11 : ((130798246269:ℝ)/200000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 12 5985 :=
    term_ge 110 12 5985 (7474550/(10:ℝ)^10) ((2215573716003:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c12 : ((15033067751:ℝ)/200000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 13 635 :=
    term_ge 110 13 635 (7474550/(10:ℝ)^10) ((2135531008329:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c13 : ((23645496331:ℝ)/50000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 14 3710 :=
    term_ge 110 14 3710 (7474550/(10:ℝ)^10) ((128838939761:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c14 : ((320761429947:ℝ)/250000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 15 9395 :=
    term_ge 110 15 9395 (7474550/(10:ℝ)^10) ((1992430164689:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 12 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c15 : ((1001442051:ℝ)/15625000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 16 440 :=
    term_ge 110 16 440 (7474550/(10:ℝ)^10) ((1927891643551:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c16 : ((62678328093:ℝ)/1000000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 17 405 :=
    term_ge 110 17 405 (7474550/(10:ℝ)^10) ((373453404347:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c17 : ((1086787583699:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 18 13265 :=
    term_ge 110 18 13265 (7474550/(10:ℝ)^10) ((362021721579:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c18 : ((28883340849:ℝ)/200000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 19 835 :=
    term_ge 110 19 835 (7474550/(10:ℝ)^10) ((13719073333:ℝ)/7812500000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c19 : ((20025500693:ℝ)/1000000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 20 110 :=
    term_ge 110 20 110 (7474550/(10:ℝ)^10) ((1704748092237:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c20 : ((63078026783:ℝ)/125000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 21 2640 :=
    term_ge 110 21 2640 (7474550/(10:ℝ)^10) ((1655957928067:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c21 : ((126090709507:ℝ)/125000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 42 2640 :=
    term_ge 110 42 2640 (7474550/(10:ℝ)^10) ((240702686877:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c22 : ((552359833771:ℝ)/500000000) ≤ T 110 (1 - 7474550/(10:ℝ)^10) 46 2640 :=
    term_ge 110 46 2640 (7474550/(10:ℝ)^10) ((435919484651:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 4058344/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 110, W = 14692, D = 3080).  Relative slack: 1.10e-07. -/
theorem foldRank_B2Gp193x :
    (2:ℝ)^40 * ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 4058344/(10:ℝ)^10)) < ((2:ℝ)^40 - 1) * ((3080:ℕ):ℝ) :=
  FoldRate.rank_fact3 110 14692 3080 40 (4058344/(10:ℝ)^10) ((2350240182897:ℝ)/500000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 4058349/10^10` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Gp193x_sharp :
    ((3080:ℕ):ℝ) ≤ ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 4058349/(10:ℝ)^10)) :=
  FoldRate.rank_fact_sharp 110 14692 3080 (4058349/(10:ℝ)^10) ((4700480365791:ℝ)/1000000000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp193x
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp193x_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp193x
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp193x_sharp
