import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `P193` (h = 22)

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 14692` live roles, label dimension `m = 110`, deficit `D = 3080`.

* `blocksB2Gp193`            the block list (rank, count) of ONE unit;
* `fold_B2Gp193`             whole-block fact at `1 - 74745/10^8`, fill parameter `s = 13` (slack 7.27e-09);
* `fold_B2Gp193_sharp`       `W ≤ moment` at `1 - 74746/10^8`: fails for every table (excess 1.29e-08);
* `foldRank_B2Gp193`         per-rank fact at `1 - 40578/10^8`, `s = 13` (slack 1.20e-05);
* `foldRank_B2Gp193_sharp`   per-rank: fails for every table at `1 - 40584/10^8`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `P193` (h = 22, m = 110): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; the kernel-counted list `GXD.P193.hist`), and for each of the v = 1320 ports the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 9412 slots shared by the five stages. -/
def blocksB2Gp193 : List (ℕ × ℕ) := [(1, 145890), (2, 61990), (3, 49615), (4, 23685), (5, 9750), (6, 8025), (7, 3530), (8, 7655), (9, 2145), (10, 4650), (11, 1770), (12, 5985), (13, 635), (14, 3710), (15, 9395), (16, 440), (17, 405), (18, 13265), (19, 835), (20, 110), (21, 2640), (42, 2640), (46, 2640)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Gp193_rank : (blocksB2Gp193.map fun b => b.1 * b.2).sum = 14692 * 110 - 3080 := by
  norm_num [blocksB2Gp193]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Gp193_tally : (blocksB2Gp193.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((14692:ℕ):ℝ) * ((110:ℕ):ℝ) - ((3080:ℕ):ℝ) := by
  norm_num [blocksB2Gp193]

theorem blocksB2Gp193_count : (blocksB2Gp193.map fun b => b.2).sum = 361405 := by
  norm_num [blocksB2Gp193]

theorem blocksB2Gp193_proper : ∀ b ∈ blocksB2Gp193, 1 ≤ b.1 ∧ b.1 < 110 := by
  decide

/-- **whole-block fact** of `blocksB2Gp193` at exponent `1 - 74745/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 110, W = 14692).  Relative slack of the rational certificate: 7.27e-09. -/
theorem fold_B2Gp193 :
    ((2:ℝ)^13 - 1) * moment 110 (1 - 74745/(10:ℝ)^8) blocksB2Gp193
      + ((14692:ℕ):ℝ) * (T 110 (1 - 74745/(10:ℝ)^8) (110 - 1) 1 + T 110 (1 - 74745/(10:ℝ)^8) 1 1)
      < (2:ℝ)^13 * ((14692:ℕ):ℝ) := by
  have hsum : moment 110 (1 - 74745/(10:ℝ)^8) blocksB2Gp193
      = T 110 (1 - 74745/(10:ℝ)^8) 1 145890 + (T 110 (1 - 74745/(10:ℝ)^8) 2 61990 + (T 110 (1 - 74745/(10:ℝ)^8) 3 49615 + (T 110 (1 - 74745/(10:ℝ)^8) 4 23685 + (T 110 (1 - 74745/(10:ℝ)^8) 5 9750 + (T 110 (1 - 74745/(10:ℝ)^8) 6 8025 + (T 110 (1 - 74745/(10:ℝ)^8) 7 3530 + (T 110 (1 - 74745/(10:ℝ)^8) 8 7655 + (T 110 (1 - 74745/(10:ℝ)^8) 9 2145 + (T 110 (1 - 74745/(10:ℝ)^8) 10 4650 + (T 110 (1 - 74745/(10:ℝ)^8) 11 1770 + (T 110 (1 - 74745/(10:ℝ)^8) 12 5985 + (T 110 (1 - 74745/(10:ℝ)^8) 13 635 + (T 110 (1 - 74745/(10:ℝ)^8) 14 3710 + (T 110 (1 - 74745/(10:ℝ)^8) 15 9395 + (T 110 (1 - 74745/(10:ℝ)^8) 16 440 + (T 110 (1 - 74745/(10:ℝ)^8) 17 405 + (T 110 (1 - 74745/(10:ℝ)^8) 18 13265 + (T 110 (1 - 74745/(10:ℝ)^8) 19 835 + (T 110 (1 - 74745/(10:ℝ)^8) 20 110 + (T 110 (1 - 74745/(10:ℝ)^8) 21 2640 + (T 110 (1 - 74745/(10:ℝ)^8) 42 2640 + (T 110 (1 - 74745/(10:ℝ)^8) 46 2640 + 0)))))))))))))))))))))) := rfl
  have b0 : T 110 (1 - 74745/(10:ℝ)^8) 1 145890 ≤ ((66547030893:ℝ)/50000000) :=
    term_le 110 1 145890 (74745/(10:ℝ)^8) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 110 (1 - 74745/(10:ℝ)^8) 2 61990 ≤ ((113047192599:ℝ)/100000000) :=
    term_le 110 2 61990 (74745/(10:ℝ)^8) ((2003666592617:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 26 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 110 (1 - 74745/(10:ℝ)^8) 3 49615 ≤ ((67839210453:ℝ)/50000000) :=
    term_le 110 3 49615 (74745/(10:ℝ)^8) ((1800934038563:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 110 (1 - 74745/(10:ℝ)^8) 4 23685 ≤ ((674538209:ℝ)/781250) :=
    term_le 110 4 23685 (74745/(10:ℝ)^8) ((1657093002337:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 110 (1 - 74745/(10:ℝ)^8) 5 9750 ≤ ((44420692937:ℝ)/100000000) :=
    term_le 110 5 9750 (74745/(10:ℝ)^8) ((38638030667:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 110 (1 - 74745/(10:ℝ)^8) 6 8025 ≤ ((21933999069:ℝ)/50000000) :=
    term_le 110 6 8025 (74745/(10:ℝ)^8) ((1454360448283:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 110 (1 - 74745/(10:ℝ)^8) 7 3530 ≤ ((281374181:ℝ)/1250000) :=
    term_le 110 7 3530 (74745/(10:ℝ)^8) ((2754570216739:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 110 (1 - 74745/(10:ℝ)^8) 8 7655 ≤ ((55781902391:ℝ)/100000000) :=
    term_le 110 8 7655 (74745/(10:ℝ)^8) ((1310519412057:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 110 (1 - 74745/(10:ℝ)^8) 9 2145 ≤ ((17582867823:ℝ)/100000000) :=
    term_le 110 9 2145 (74745/(10:ℝ)^8) ((1251627894229:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 110 (1 - 74745/(10:ℝ)^8) 10 4650 ≤ ((21174280461:ℝ)/50000000) :=
    term_le 110 10 4650 (74745/(10:ℝ)^8) ((2997369091:ℝ)/1250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 110 (1 - 74745/(10:ℝ)^8) 11 1770 ≤ ((141843913:ℝ)/800000) :=
    term_le 110 11 1770 (74745/(10:ℝ)^8) ((575646273249:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 110 (1 - 74745/(10:ℝ)^8) 12 5985 ≤ ((65399122427:ℝ)/100000000) :=
    term_le 110 12 5985 (74745/(10:ℝ)^8) ((1107786858003:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 110 (1 - 74745/(10:ℝ)^8) 13 635 ≤ ((7516533797:ℝ)/100000000) :=
    term_le 110 13 635 (74745/(10:ℝ)^8) ((533882752083:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b13 : T 110 (1 - 74745/(10:ℝ)^8) 14 3710 ≤ ((9458198437:ℝ)/20000000) :=
    term_le 110 14 3710 (74745/(10:ℝ)^8) ((2061423036179:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b14 : T 110 (1 - 74745/(10:ℝ)^8) 15 9395 ≤ ((5132182829:ℝ)/4000000) :=
    term_le 110 15 9395 (74745/(10:ℝ)^8) ((498107541173:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b15 : T 110 (1 - 74745/(10:ℝ)^8) 16 440 ≤ ((3204614533:ℝ)/50000000) :=
    term_le 110 16 440 (74745/(10:ℝ)^8) ((963945821777:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b16 : T 110 (1 - 74745/(10:ℝ)^8) 17 405 ≤ ((391739547:ℝ)/6250000) :=
    term_le 110 17 405 (74745/(10:ℝ)^8) ((933633510869:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b17 : T 110 (1 - 74745/(10:ℝ)^8) 18 13265 ≤ ((217357514803:ℝ)/100000000) :=
    term_le 110 18 13265 (74745/(10:ℝ)^8) ((905054303949:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b18 : T 110 (1 - 74745/(10:ℝ)^8) 19 835 ≤ ((144416703:ℝ)/1000000) :=
    term_le 110 19 835 (74745/(10:ℝ)^8) ((1756041386627:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b19 : T 110 (1 - 74745/(10:ℝ)^8) 20 110 ≤ ((2002550053:ℝ)/100000000) :=
    term_le 110 20 110 (74745/(10:ℝ)^8) ((21309351153:ℝ)/12500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b20 : T 110 (1 - 74745/(10:ℝ)^8) 21 2640 ≤ ((25231210507:ℝ)/50000000) :=
    term_le 110 21 2640 (74745/(10:ℝ)^8) ((165595792807:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b21 : T 110 (1 - 74745/(10:ℝ)^8) 42 2640 ≤ ((100872567123:ℝ)/100000000) :=
    term_le 110 42 2640 (74745/(10:ℝ)^8) ((962810747511:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b22 : T 110 (1 - 74745/(10:ℝ)^8) 46 2640 ≤ ((4418878651:ℝ)/4000000) :=
    term_le 110 46 2640 (74745/(10:ℝ)^8) ((174367793861:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b23 : T 110 (1 - 74745/(10:ℝ)^8) 109 1 ≤ ((49545793:ℝ)/50000000) :=
    term_le 110 109 1 (74745/(10:ℝ)^8) ((1826496713:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 5 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b24 : T 110 (1 - 74745/(10:ℝ)^8) 1 1 ≤ ((912291:ℝ)/100000000) :=
    term_le 110 1 1 (74745/(10:ℝ)^8) ((2350240182897:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^13 - 1) = 8191 := by norm_num
  have e2 : (2:ℝ)^13 = 8192 := by norm_num
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  have e4 : T 110 (1 - 74745/(10:ℝ)^8) (110 - 1) 1 = T 110 (1 - 74745/(10:ℝ)^8) 109 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 74746/10^8` the moment of one unit is at least its number of live roles `14692`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 1.29e-08. -/
theorem fold_B2Gp193_sharp : ((14692:ℕ):ℝ) ≤ moment 110 (1 - 74746/(10:ℝ)^8) blocksB2Gp193 := by
  have hsum : moment 110 (1 - 74746/(10:ℝ)^8) blocksB2Gp193
      = T 110 (1 - 74746/(10:ℝ)^8) 1 145890 + (T 110 (1 - 74746/(10:ℝ)^8) 2 61990 + (T 110 (1 - 74746/(10:ℝ)^8) 3 49615 + (T 110 (1 - 74746/(10:ℝ)^8) 4 23685 + (T 110 (1 - 74746/(10:ℝ)^8) 5 9750 + (T 110 (1 - 74746/(10:ℝ)^8) 6 8025 + (T 110 (1 - 74746/(10:ℝ)^8) 7 3530 + (T 110 (1 - 74746/(10:ℝ)^8) 8 7655 + (T 110 (1 - 74746/(10:ℝ)^8) 9 2145 + (T 110 (1 - 74746/(10:ℝ)^8) 10 4650 + (T 110 (1 - 74746/(10:ℝ)^8) 11 1770 + (T 110 (1 - 74746/(10:ℝ)^8) 12 5985 + (T 110 (1 - 74746/(10:ℝ)^8) 13 635 + (T 110 (1 - 74746/(10:ℝ)^8) 14 3710 + (T 110 (1 - 74746/(10:ℝ)^8) 15 9395 + (T 110 (1 - 74746/(10:ℝ)^8) 16 440 + (T 110 (1 - 74746/(10:ℝ)^8) 17 405 + (T 110 (1 - 74746/(10:ℝ)^8) 18 13265 + (T 110 (1 - 74746/(10:ℝ)^8) 19 835 + (T 110 (1 - 74746/(10:ℝ)^8) 20 110 + (T 110 (1 - 74746/(10:ℝ)^8) 21 2640 + (T 110 (1 - 74746/(10:ℝ)^8) 42 2640 + (T 110 (1 - 74746/(10:ℝ)^8) 46 2640 + 0)))))))))))))))))))))) := rfl
  have c0 : ((3327351693:ℝ)/2500000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 1 145890 :=
    term_ge 110 1 145890 (74746/(10:ℝ)^8) ((4700480365791:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((706544981:ℝ)/625000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 2 61990 :=
    term_ge 110 2 61990 (74746/(10:ℝ)^8) ((4007333185231:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((3391960641:ℝ)/2500000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 3 49615 :=
    term_ge 110 3 49615 (74746/(10:ℝ)^8) ((3601868077123:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((4317044677:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 4 23685 :=
    term_ge 110 4 23685 (74746/(10:ℝ)^8) ((3314186004671:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((4442069427:ℝ)/10000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 5 9750 :=
    term_ge 110 5 9750 (74746/(10:ℝ)^8) ((3091042453357:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((2193399969:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 6 8025 :=
    term_ge 110 6 8025 (74746/(10:ℝ)^8) ((2908720896563:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((562748377:ℝ)/2500000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 7 3530 :=
    term_ge 110 7 3530 (74746/(10:ℝ)^8) ((86080319273:ℝ)/31250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((2789095191:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 8 7655 :=
    term_ge 110 8 7655 (74746/(10:ℝ)^8) ((2621038824111:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((70331473:ℝ)/400000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 9 2145 :=
    term_ge 110 9 2145 (74746/(10:ℝ)^8) ((500651157691:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((33084814:ℝ)/78125) ≤ T 110 (1 - 74746/(10:ℝ)^8) 10 4650 :=
    term_ge 110 10 4650 (74746/(10:ℝ)^8) ((2397895272797:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((221631119:ℝ)/1250000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 11 1770 :=
    term_ge 110 11 1770 (74746/(10:ℝ)^8) ((2302585092993:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c11 : ((1307982477:ℝ)/2000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 12 5985 :=
    term_ge 110 12 5985 (74746/(10:ℝ)^8) ((2215573716003:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c12 : ((150330679:ℝ)/2000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 13 635 :=
    term_ge 110 13 635 (74746/(10:ℝ)^8) ((2135531008329:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c13 : ((2364549657:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 14 3710 :=
    term_ge 110 14 3710 (74746/(10:ℝ)^8) ((128838939761:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c14 : ((513218293:ℝ)/400000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 15 9395 :=
    term_ge 110 15 9395 (74746/(10:ℝ)^8) ((1992430164689:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 12 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c15 : ((320461459:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 16 440 :=
    term_ge 110 16 440 (74746/(10:ℝ)^8) ((1927891643551:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c16 : ((313391643:ℝ)/5000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 17 405 :=
    term_ge 110 17 405 (74746/(10:ℝ)^8) ((373453404347:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c17 : ((2173575187:ℝ)/1000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 18 13265 :=
    term_ge 110 18 13265 (74746/(10:ℝ)^8) ((362021721579:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c18 : ((288833411:ℝ)/2000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 19 835 :=
    term_ge 110 19 835 (74746/(10:ℝ)^8) ((13719073333:ℝ)/7812500000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c19 : ((6257969:ℝ)/312500) ≤ T 110 (1 - 74746/(10:ℝ)^8) 20 110 :=
    term_ge 110 20 110 (74746/(10:ℝ)^8) ((1704748092237:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c20 : ((630780273:ℝ)/1250000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 21 2640 :=
    term_ge 110 21 2640 (74746/(10:ℝ)^8) ((1655957928067:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c21 : ((10087256809:ℝ)/10000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 42 2640 :=
    term_ge 110 42 2640 (74746/(10:ℝ)^8) ((240702686877:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c22 : ((11047196723:ℝ)/10000000) ≤ T 110 (1 - 74746/(10:ℝ)^8) 46 2640 :=
    term_ge 110 46 2640 (74746/(10:ℝ)^8) ((435919484651:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((14692:ℕ):ℝ) = 14692 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 40578/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 110, W = 14692, D = 3080).  Relative slack: 1.20e-05. -/
theorem foldRank_B2Gp193 :
    (2:ℝ)^13 * ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 40578/(10:ℝ)^8)) < ((2:ℝ)^13 - 1) * ((3080:ℕ):ℝ) :=
  FoldRate.rank_fact3 110 14692 3080 13 (40578/(10:ℝ)^8) ((2350240182897:ℝ)/500000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 40584/10^8` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Gp193_sharp :
    ((3080:ℕ):ℝ) ≤ ((14692:ℕ):ℝ) * (((110:ℕ):ℝ) - ((110:ℕ):ℝ)^(1 - 40584/(10:ℝ)^8)) :=
  FoldRate.rank_fact_sharp 110 14692 3080 (40584/(10:ℝ)^8) ((4700480365791:ℝ)/1000000000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp193
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Gp193_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp193
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Gp193_sharp
