import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `E8` (h = 9)

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 1263` live roles, label dimension `m = 45`, deficit `D = 120`.

* `blocksB2Ge8`            the block list (rank, count) of ONE unit;
* `fold_B2Ge8`             whole-block fact at `1 - 87624/10^8`, fill parameter `s = 13` (slack 7.83e-09);
* `fold_B2Ge8_sharp`       `W ≤ moment` at `1 - 87625/10^8`: fails for every table (excess 4.13e-09);
* `foldRank_B2Ge8`         per-rank fact at `1 - 55517/10^8`, `s = 13` (slack 1.53e-06);
* `foldRank_B2Ge8_sharp`   per-rank: fails for every table at `1 - 55524/10^8`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `E8` (h = 9, m = 45): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; the kernel-counted list `GXD.E8.hist`), and for each of the v = 120 ports the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 783 slots shared by the five stages. -/
def blocksB2Ge8 : List (ℕ × ℕ) := [(1, 10455), (2, 3020), (3, 2590), (4, 940), (5, 1075), (6, 1655), (7, 215), (8, 360), (9, 40), (16, 240), (20, 240)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Ge8_rank : (blocksB2Ge8.map fun b => b.1 * b.2).sum = 1263 * 45 - 120 := by
  norm_num [blocksB2Ge8]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Ge8_tally : (blocksB2Ge8.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((1263:ℕ):ℝ) * ((45:ℕ):ℝ) - ((120:ℕ):ℝ) := by
  norm_num [blocksB2Ge8]

theorem blocksB2Ge8_count : (blocksB2Ge8.map fun b => b.2).sum = 20830 := by
  norm_num [blocksB2Ge8]

theorem blocksB2Ge8_proper : ∀ b ∈ blocksB2Ge8, 1 ≤ b.1 ∧ b.1 < 45 := by
  decide

/-- **whole-block fact** of `blocksB2Ge8` at exponent `1 - 87624/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 45, W = 1263).  Relative slack of the rational certificate: 7.83e-09. -/
theorem fold_B2Ge8 :
    ((2:ℝ)^13 - 1) * moment 45 (1 - 87624/(10:ℝ)^8) blocksB2Ge8
      + ((1263:ℕ):ℝ) * (T 45 (1 - 87624/(10:ℝ)^8) (45 - 1) 1 + T 45 (1 - 87624/(10:ℝ)^8) 1 1)
      < (2:ℝ)^13 * ((1263:ℕ):ℝ) := by
  have hsum : moment 45 (1 - 87624/(10:ℝ)^8) blocksB2Ge8
      = T 45 (1 - 87624/(10:ℝ)^8) 1 10455 + (T 45 (1 - 87624/(10:ℝ)^8) 2 3020 + (T 45 (1 - 87624/(10:ℝ)^8) 3 2590 + (T 45 (1 - 87624/(10:ℝ)^8) 4 940 + (T 45 (1 - 87624/(10:ℝ)^8) 5 1075 + (T 45 (1 - 87624/(10:ℝ)^8) 6 1655 + (T 45 (1 - 87624/(10:ℝ)^8) 7 215 + (T 45 (1 - 87624/(10:ℝ)^8) 8 360 + (T 45 (1 - 87624/(10:ℝ)^8) 9 40 + (T 45 (1 - 87624/(10:ℝ)^8) 16 240 + (T 45 (1 - 87624/(10:ℝ)^8) 20 240 + 0)))))))))) := rfl
  have b0 : T 45 (1 - 87624/(10:ℝ)^8) 1 10455 ≤ ((4662191743:ℝ)/20000000) :=
    term_le 45 1 10455 (87624/(10:ℝ)^8) ((951665622443:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 45 (1 - 87624/(10:ℝ)^8) 2 3020 ≤ ((6729445281:ℝ)/50000000) :=
    term_le 45 2 3020 (87624/(10:ℝ)^8) ((778378827303:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 45 (1 - 87624/(10:ℝ)^8) 3 2590 ≤ ((4326921859:ℝ)/25000000) :=
    term_le 45 3 2590 (87624/(10:ℝ)^8) ((169253137569:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 45 (1 - 87624/(10:ℝ)^8) 4 940 ≤ ((4186647511:ℝ)/50000000) :=
    term_le 45 4 940 (87624/(10:ℝ)^8) ((605092032163:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 45 (1 - 87624/(10:ℝ)^8) 5 1075 ≤ ((11967463193:ℝ)/100000000) :=
    term_le 45 5 1075 (87624/(10:ℝ)^8) ((1098612288669:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 45 (1 - 87624/(10:ℝ)^8) 6 1655 ≤ ((22105660639:ℝ)/100000000) :=
    term_le 45 6 1655 (87624/(10:ℝ)^8) ((1967678731:ℝ)/976562500) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 45 (1 - 87624/(10:ℝ)^8) 7 215 ≤ ((669980379:ℝ)/20000000) :=
    term_le 45 7 215 (87624/(10:ℝ)^8) ((1860752340717:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 45 (1 - 87624/(10:ℝ)^8) 8 360 ≤ ((160242337:ℝ)/2500000) :=
    term_le 45 8 360 (87624/(10:ℝ)^8) ((431805237023:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 45 (1 - 87624/(10:ℝ)^8) 9 40 ≤ ((801129:ℝ)/100000) :=
    term_le 45 9 40 (87624/(10:ℝ)^8) ((402359478109:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 45 (1 - 87624/(10:ℝ)^8) 16 240 ≤ ((133454201:ℝ)/1562500) :=
    term_le 45 16 240 (87624/(10:ℝ)^8) ((258518441883:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 45 (1 - 87624/(10:ℝ)^8) 20 240 ≤ ((10674248769:ℝ)/100000000) :=
    term_le 45 20 240 (87624/(10:ℝ)^8) ((405465108109:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 45 (1 - 87624/(10:ℝ)^8) 44 1 ≤ ((12222463:ℝ)/12500000) :=
    term_le 45 44 1 (87624/(10:ℝ)^8) ((11236427927:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 6 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 45 (1 - 87624/(10:ℝ)^8) 1 1 ≤ ((2229647:ℝ)/100000000) :=
    term_le 45 1 1 (87624/(10:ℝ)^8) ((951665622443:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^13 - 1) = 8191 := by norm_num
  have e2 : (2:ℝ)^13 = 8192 := by norm_num
  have e3 : ((1263:ℕ):ℝ) = 1263 := by norm_num
  have e4 : T 45 (1 - 87624/(10:ℝ)^8) (45 - 1) 1 = T 45 (1 - 87624/(10:ℝ)^8) 44 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 87625/10^8` the moment of one unit is at least its number of live roles `1263`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 4.13e-09. -/
theorem fold_B2Ge8_sharp : ((1263:ℕ):ℝ) ≤ moment 45 (1 - 87625/(10:ℝ)^8) blocksB2Ge8 := by
  have hsum : moment 45 (1 - 87625/(10:ℝ)^8) blocksB2Ge8
      = T 45 (1 - 87625/(10:ℝ)^8) 1 10455 + (T 45 (1 - 87625/(10:ℝ)^8) 2 3020 + (T 45 (1 - 87625/(10:ℝ)^8) 3 2590 + (T 45 (1 - 87625/(10:ℝ)^8) 4 940 + (T 45 (1 - 87625/(10:ℝ)^8) 5 1075 + (T 45 (1 - 87625/(10:ℝ)^8) 6 1655 + (T 45 (1 - 87625/(10:ℝ)^8) 7 215 + (T 45 (1 - 87625/(10:ℝ)^8) 8 360 + (T 45 (1 - 87625/(10:ℝ)^8) 9 40 + (T 45 (1 - 87625/(10:ℝ)^8) 16 240 + (T 45 (1 - 87625/(10:ℝ)^8) 20 240 + 0)))))))))) := rfl
  have c0 : ((116554797769:ℝ)/500000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 1 10455 :=
    term_ge 45 1 10455 (87625/(10:ℝ)^8) ((3806662489769:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 12 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((2691778193:ℝ)/20000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 2 3020 :=
    term_ge 45 2 3020 (87625/(10:ℝ)^8) ((3113515309209:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((86538439457:ℝ)/500000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 3 2590 :=
    term_ge 45 3 2590 (87625/(10:ℝ)^8) ((2708050201101:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((83732952201:ℝ)/1000000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 4 940 :=
    term_ge 45 4 940 (87625/(10:ℝ)^8) ((2420368128649:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((11967463451:ℝ)/100000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 5 1075 :=
    term_ge 45 5 1075 (87625/(10:ℝ)^8) ((439444915467:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((13816038173:ℝ)/62500000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 6 1655 :=
    term_ge 45 6 1655 (87625/(10:ℝ)^8) ((2014903020541:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((33499019563:ℝ)/1000000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 7 215 :=
    term_ge 45 7 215 (87625/(10:ℝ)^8) ((930376170357:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((64096935887:ℝ)/1000000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 8 360 :=
    term_ge 45 8 360 (87625/(10:ℝ)^8) ((1727220948089:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((4005645059:ℝ)/500000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 9 40 :=
    term_ge 45 9 40 (87625/(10:ℝ)^8) ((1609437912433:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((85410689517:ℝ)/1000000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 16 240 :=
    term_ge 45 16 240 (87625/(10:ℝ)^8) ((1034073767529:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((53371244273:ℝ)/500000000) ≤ T 45 (1 - 87625/(10:ℝ)^8) 20 240 :=
    term_ge 45 20 240 (87625/(10:ℝ)^8) ((162186043243:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((1263:ℕ):ℝ) = 1263 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 55517/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 45, W = 1263, D = 120).  Relative slack: 1.53e-06. -/
theorem foldRank_B2Ge8 :
    (2:ℝ)^13 * ((1263:ℕ):ℝ) * (((45:ℕ):ℝ) - ((45:ℕ):ℝ)^(1 - 55517/(10:ℝ)^8)) < ((2:ℝ)^13 - 1) * ((120:ℕ):ℝ) :=
  FoldRate.rank_fact3 45 1263 120 13 (55517/(10:ℝ)^8) ((951665622443:ℝ)/250000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 55524/10^8` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Ge8_sharp :
    ((120:ℕ):ℝ) ≤ ((1263:ℕ):ℝ) * (((45:ℕ):ℝ) - ((45:ℕ):ℝ)^(1 - 55524/(10:ℝ)^8)) :=
  FoldRate.rank_fact_sharp 45 1263 120 (55524/(10:ℝ)^8) ((3806662489769:ℝ)/1000000000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 3 12 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ge8
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ge8_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ge8
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ge8_sharp
