import OAI.Computability.FourierTransform.Goal

/-
Modified copy of five definitions of lean/OAI/Computability/FourierTransform/Goal.lean of
github.com/openai/math (commit fd4aeeb, Apache-2.0; lines 30, 35, 75-78, 80, 82), generated by
`tools/fourier/mkchain_e8.py`. Changed for this repository:
  * the exponent `1 - 1/(10^(13:ℕ))` is replaced by `1 - 8762478/(10^(10:ℕ))`;
  * the five names have the suffix `E8` (OpenAI's own definitions keep their names and values).
Everything else they mention (`paperTime`, `nlogn`, `DFTProgram`, `ConvProgram`) is OpenAI's own,
imported unmodified.
-/

namespace OAI

namespace PowerSaving
noncomputable section
open RAM RAM.Ty Filter Asymptotics

def decimalExponentE8 : ℝ := 1 - 8762478/(10^(10:ℕ))

def decimalTimeE8 (n : ℕ) : ℝ := (n:ℝ) * (Real.log (n:ℝ)) ^ decimalExponentE8

/-- Thm 1 (intro main) and decimal corollary estimates. -/
def TimeBoundsE8 (W : ℕ → ℕ) : Prop :=
  let W' := fun n : ℕ => (W n : ℝ)
  W' =O[atTop] paperTime ∧ W' =O[atTop] decimalTimeE8 ∧ W' =o[atTop] nlogn

def DFTGoalE8 : Prop := ∃ order solve W, DFTProgram order solve W ∧ TimeBoundsE8 W

def ConvGoalE8 : Prop := ∃ order solve W, ConvProgram order solve W ∧ TimeBoundsE8 W

end
end PowerSaving

end OAI
