import Work.FourierE8.Asymptotics
import OAI.Computability.FourierTransform.RegisterBounds
import Work.FourierE8.Goal

/-
Modified copy of lean/OAI/Computability/FourierTransform/Main.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain_e8.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `E8`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaE8 = 1 - 8762479/10^10` and `hillsE8` (Work/FourierE8/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsE8_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `E8` versions from Work/FourierE8/Goal.lean (exponent `1 - 8762478/10^10`);
  * imports point to the copies.
  * literal `let d : ℝ := 2/(10:ℝ)^11` -> `let d : ℝ := 8762479/(10:ℝ)^10` (alpha_thetaE8: the local constant d must equal 1 - alphaE8)
  * `theorem transform_mainE8 : DFTGoalE8 :=`: docstring added
  * `theorem convolution_mainE8 : ConvGoalE8 :=`: docstring added
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/-!
Exact uniform Fourier transforms and convolution.

The construction formalizes the exact arithmetic algorithms of
*An explicit power saving for the exact discrete Fourier transform* (OpenAI).
The finite phase network originates in the complex construction of
*Integer multiplication below n log n*.

`transform_mainE8` and `convolution_mainE8` give fixed finite RAM programs, including
preparation and index work, polynomial storage bounds, and a canonical root whose
order is computed from the input length. Each includes the paper exponent, decimal
power saving, and little-o bound. The `_order` variants also specify the root order.

The implementation uses a smaller concrete tensor network (32 binary coordinates
per factor, 4060 triples, and a `2^50` role envelope) with a stronger saving that
implies the stated paper constants. The general rational-algebra extraction,
symbolic certificate search, circuit printer, and bounded-printer uniformization
from the synthesis appendix are outside this formalization.
-/
namespace PowerSaving
open RAM Bench Selection Filter Asymptotics Real
noncomputable section
namespace Skies

lemma multiplier_rangeE8 : 1 < paperMultiplier ∧ paperMultiplier < paperM := by
  norm_num [paperMultiplier,paperM,paperDelta,paperW]

lemma theta_ltE8 : theta < 1 := by
  have h := multiplier_rangeE8
  have hg : 0<log paperM := Real.log_pos (lt_trans h.1 h.2)
  rw [theta,div_lt_iff₀ hg,one_mul]
  exact Real.log_lt_log (by linarith) h.2

lemma alpha_thetaE8 : alphaE8 < theta := by
  let d : ℝ := 8762479/(10:ℝ)^10
  have hp : 0<d := by dsimp [d]; norm_num
  have hm : 2 ≤ paperM := by norm_num [paperM]
  have hx : 0<paperMultiplier := lt_trans zero_lt_one multiplier_rangeE8.1
  have hu : 0<paperM := by linarith
  have h2 := (Real.log_le_log (by norm_num : 0 < (2:ℝ)) hm)
  have he := log2_minE8
  have hh : 0<log paperM := by linarith
  have hk := Real.log_le_sub_one_of_pos (show 0<paperM/paperMultiplier by positivity)
  rw [log_div hu.ne' hx.ne'] at hk
  have H : paperM/paperMultiplier-1 < d*(2/3) := by
    norm_num [d,paperM,paperMultiplier,paperW,paperDelta]
  rw [theta,lt_div_iff₀ hh]
  change (1-d)*log paperM < log paperMultiplier
  have H' := mul_le_mul_of_nonneg_left (he.trans h2) hp.le
  have hy := hk.trans_lt (lt_of_lt_of_le H H')
  rw [sub_mul,one_mul]
  linarith only [hy]

lemma decimal_rangeE8 : alphaE8 < decimalExponentE8 ∧ decimalExponentE8 < 1 := by
  norm_num [decimalExponentE8,alphaE8]

def speedE8 (v : ℝ) (n : ℕ) := (n:ℝ)*(TmE8 n)^v

lemma flight_littleE8 {v : ℝ} (h : alphaE8 < v) :
    flightE8 =o[atTop] speedE8 v := by
  rw [isLittleO_iff]
  intro c hc
  filter_upwards [TtopE8.eventually_ge_atTop 1,dwarfE8 TtopE8 2
    (p:=v-alphaE8) (sub_pos.mpr h) hc] with n hn hh
  have he : 0<TmE8 n := by linarith
  change ‖(n:ℝ)*TmE8 n^alphaE8*QmE8 n^2‖ ≤ c*‖(n:ℝ)*TmE8 n^v‖
  rw [Real.norm_of_nonneg (by positivity),Real.norm_of_nonneg (by positivity)]
  calc
    _ ≤ ((n:ℝ)*TmE8 n^alphaE8)*(c*TmE8 n^(v-alphaE8)) :=
      mul_le_mul_of_nonneg_left hh (by positivity)
    _ = c*((n:ℝ)*(TmE8 n^alphaE8*TmE8 n^(v-alphaE8))) := by ring
    _ = _ := by rw [← rpow_add he, show alphaE8 + (v-alphaE8)=v by ring] -- a+(v-a)

lemma speed_littleE8 {u v : ℝ} (h : u < v) :
    speedE8 u =o[atTop] speedE8 v := by
  rw [isLittleO_iff]
  intro c hc
  filter_upwards [TtopE8.eventually_ge_atTop 1,dwarfE8 TtopE8 0
    (p:=v-u) (sub_pos.mpr h) hc] with n hn hh
  have he : 0<TmE8 n := by linarith
  change ‖(n:ℝ)*TmE8 n^u‖ ≤ c*‖(n:ℝ)*TmE8 n^v‖
  rw [Real.norm_of_nonneg (by positivity),Real.norm_of_nonneg (by positivity)]
  have hh' : 1 ≤ c * TmE8 n^(v-u) := by simpa only [pow_zero] using hh
  calc
    _ = ((n:ℝ)*TmE8 n^u)*1 := by ring
    _ ≤ ((n:ℝ)*TmE8 n^u)*(c*TmE8 n^(v-u)) := mul_le_mul_of_nonneg_left hh' (by positivity)
    _ = c*((n:ℝ)*(TmE8 n^u*TmE8 n^(v-u))) := by ring
    _ = _ := by rw [← rpow_add he, show u+(v-u)=v by ring]

theorem decimal_littleE8 : decimalTimeE8 =o[atTop] nlogn := by
  have H := speed_littleE8 decimal_rangeE8.2
  have h : speedE8 1 = nlogn := funext fun n => by rw [speedE8,Real.rpow_one]; rfl
  rw [h] at H; exact H

lemma speed_paperE8 : speedE8 theta =O[atTop] paperTime := by
  rw [isBigO_iff]
  refine ⟨1,?_⟩
  filter_upwards [TtopE8.eventually_ge_atTop 1,QtopE8.eventually_ge_atTop 1] with n hn hh
  have he : 0<TmE8 n := by linarith
  have he' : 0<QmE8 n := by linarith
  change ‖(n:ℝ)*TmE8 n^theta‖ ≤ 1*‖(n:ℝ)*TmE8 n^theta*QmE8 n^(4-theta)‖
  rw [Real.norm_of_nonneg (by positivity),Real.norm_of_nonneg (by positivity),one_mul]
  have hb := Real.one_le_rpow hh (show 0 ≤ 4-theta by linarith [theta_ltE8])
  exact le_mul_of_one_le_right (by positivity) hb

lemma time_boundE8 {N} (h : ∀ n:ℕ,n ≤ N n ∧ N n ≤ 2*n) (a b : RationE8) :
    TimeBoundsE8 (lunchE8 a b N) := by
  have H := lunch_bigE8 a b h
  have hp := H.trans_isLittleO (flight_littleE8 alpha_thetaE8)
  have hd := H.trans_isLittleO (flight_littleE8 decimal_rangeE8.1)
  have ht : (fun n => (lunchE8 a b N n:ℝ)) =O[atTop] decimalTimeE8 := hd.isBigO
  exact ⟨hp.isBigO.trans speed_paperE8,ht,ht.trans_isLittleO decimal_littleE8⟩

end Skies

/-! Main results. Provide formula for the order besides the existential specification. -/
theorem transform_main_orderE8 : ∃ order solve W,
    DFTProgram order solve W ∧ TimeBoundsE8 W ∧
    ∀ n, 0<n → (run order n).val = receipt n ∧ (run order n).val < 8*n^3 := by
  obtain ⟨o,s,a,b,hp,ho⟩ := flagshipOneE8
  exact ⟨o,s,lunchE8 a b id,hp,Skies.time_boundE8 (N:=id) (fun n => ⟨le_rfl,by dsimp; omega⟩)
    a b,fun n hn => ⟨ho n hn,(ho n hn).symm ▸ (receipt_bound n hn).2⟩⟩

theorem convolution_main_orderE8 : ∃ order solve W,
    ConvProgram order solve W ∧ TimeBoundsE8 W ∧
    ∀ n, 0<n → (run order n).val = receipt (2*n-1) ∧ (run order n).val < 8*(2*n-1)^3 := by
  obtain ⟨o,s,a,b,hp,ho⟩ := flagshipBothE8
  have h (n : ℕ) : n ≤ stretchE8 n ∧ stretchE8 n ≤ 2*n := by unfold stretchE8; omega
  exact ⟨o,s,lunchE8 a b stretchE8,hp,Skies.time_boundE8 h a b,fun n hn =>
    ⟨ho n hn,(ho n hn).symm ▸ (receipt_bound _ (stretch_posE8 hn)).2⟩⟩

/-- **The discrete Fourier transform of every length in `O(n (log n)^(1 - 8762478/10^10))`.**
OpenAI's `transform_main` (one fixed program, OpenAI's own `DFTProgram`, `paperTime` and `nlogn`)
with the decimal exponent `1 - 1/10^13` replaced by `decimalExponentE8 = 1 - 8762478/10^10`
(Work/FourierE8/Goal.lean). Sibling of the Walsh-Hadamard theorem `wht_main_block_B2Ge8x`: both
follow from one kernel program, `RAM.hillsE8_program` (Work/FourierE8/Seam.lean). -/
theorem transform_mainE8 : DFTGoalE8 :=
  let ⟨o,s,W,h,g,_⟩ := transform_main_orderE8
  ⟨o,s,W,h,g⟩

/-- **Convolution of every length with the same bounds** (OpenAI's `convolution_main`, same change). -/
theorem convolution_mainE8 : ConvGoalE8 :=
  let ⟨o,s,W,h,g,_⟩ := convolution_main_orderE8
  ⟨o,s,W,h,g⟩

lemma matrix_definitionE8 (n : ℕ) (x : Vec n) : dft n x = Matrix.mulVec (dftMatrix n) x :=
  rfl

end
end PowerSaving

end OAI
