import Work.FourierE8.ConvolutionProgram

/-
Modified copy of lean/OAI/Computability/FourierTransform/UniformBounds.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain_e8.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `E8`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaE8 = 1 - 8762479/10^10` and `hillsE8` (Work/FourierE8/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsE8_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `E8` versions from Work/FourierE8/Goal.lean (exponent `1 - 8762478/10^10`);
  * imports point to the copies.
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/- Static allowance to programs. -/
namespace PowerSaving
open RAM Ty Selection Spectral Slant
noncomputable section

namespace RAM.Bench
universe U
variable {ι : Type U} {κ : Type*} {m : Bool} {b : Bench m ι}
  {n : ι→ℕ} {t : Ty}

lemma fairwind_smallE8 (N : ι→ℕ) (hn : ∀ i,0<N i) (d : ℕ) :
    Small N fun i => fairwindE8 d (N i) := by
  have H := Small.self N
  have hX i := barge_spec (N i) (hn i)
  have h4 := (Small.const _ 4).mul H
  have hu := h4.mono (fun (i : ι) => stack_le (N i) (hn i))
  have hk : Small N fun i => harvestN (N i) :=
    (((Small.const _ 16).mul (hu.add (Small.const _ 4))).pow 2)
  have hh := ((Small.const _ 8).mul hk).mono
    (fun i => Nat.lt_two_pow_self.le.trans (orderE_small (N i)))
  have hi := ((((Small.const _ 20000000).mul ((hh.add (Small.const _ 1)).pow 2)).add
    (Small.const _ 7))).mono (fun i => score_le (orderE (N i)))
  have hp : Small N fun i => hillsE8 (barge (N i)).l :=
    (hu.add (Small.const _ 1)).mono fun i => (hillsE8_le _).trans
      (Nat.add_le_add_right (hX i).count _)
  have hj := (hi.add (Small.const _ 1)).mul
    ((h4.mono fun i => (hX i).upper.le).mul hp)
  have hl := H.add hj |>.add ((hu.add (Small.const _ 2)).pow d)
  exact hl.add (((H.add (Small.const _ 2)).pow d).mono fun i => by split <;> omega)

-- package extracted charges
abbrev SizesE8 := {n : ℕ // 0<n}
abbrev entryE8 : SizesE8→ℕ := Subtype.val

structure RationE8 where
  d : ℕ
  c : ℕ
  p : ℕ
def calorieE8 (a : RationE8) (n : ℕ) := a.c*(fairwindE8 a.d n+1)

lemma BreezyE8.ration {x : ι→T t} (h : b.BreezyE8 n t x) :
    ∃ (s : Prog m b.tray t) (a : RationE8), ∀ i,
      (run s (b.env i)).OK (x i) (calorieE8 a (n i)) ((b.size i+2)^a.p) := by
  obtain ⟨d,hd⟩ := h
  obtain ⟨s,c,p,hc⟩ := Can.unfold_bound hd
  exact ⟨s,⟨d,c,p⟩,hc⟩

def lunchE8 (a b : RationE8) (N : ℕ→ℕ) (n : ℕ) :=
  calorieE8 a (N n)+1+calorieE8 b (N n)

lemma storehouseE8 (N : ℕ→ℕ) (h : ∀ n,0<n → 0<N n) (g : Small entryE8 (fun i => N (entryE8 i)))
    (a b : RationE8) : ∃ c : ℕ, ∀ n : ℕ, 0<n →
    let cap := (n+2)^c
    lunchE8 a b N n + 10*(n+2) ≤ cap ∧ (n+2)^a.p ≤ cap ∧ (n+2)^b.p ≤ cap ∧
    receipt (N n) ≤ cap := by
  let M i := N (entryE8 i)
  have H (a : RationE8) : Small entryE8 (fun i => calorieE8 a (M i)) :=
    (Small.const _ a.c).mul (((fairwind_smallE8 M (fun i => h _ i.property) a.d).trans g).add
      (Small.const _ 1))
  have hu := (Small.self entryE8).add (Small.const _ 2)
  have hh := (Small.const _ 10).mul hu
  have hp := ((Small.const _ 8).mul (g.pow 3)).mono
    (fun i => (receipt_bound _ (h _ i.property)).2.le)
  have ht := ((((H a).add (Small.const _ 1)).add (H b)).add hh)
  obtain ⟨c,hc⟩ := (((ht.max (hu.pow a.p)).max (hu.pow b.p)).max hp)
  refine ⟨c,fun n hn => ?_⟩
  specialize hc (⟨n,hn⟩:SizesE8)
  have hx :
      max (max (max (lunchE8 a b N n + 10*(n+2)) ((n+2)^a.p)) ((n+2)^b.p)) (receipt (N n)) ≤
        (n+2)^c := hc
  have h1 := max_le_iff.mp hx
  have h2 := max_le_iff.mp h1.1
  have h3 := max_le_iff.mp h2.1
  exact ⟨h3.1,h3.2,h2.2,h1.2⟩

-- order environments
def onlyLengthE8 : Bench false SizesE8 := ⟨entryE8,w,entryE8⟩
lemma onlyLength_numE8 : onlyLengthE8.Nick entryE8 := ⟨Can.id,Small.self _⟩

lemma orders1E8 : ∃ (s : Prog false w w) (a : RationE8), ∀ n,0<n →
    (run s n).OK (receipt n) (calorieE8 a n) ((n+2)^a.p) := by
  obtain ⟨s,a,ha⟩ := (onlyLength_numE8.landOrderE8 (fun i => i.property)).ration
  exact ⟨s,a,fun i hi => ha ⟨i,hi⟩⟩
lemma orders2E8 : ∃ (s : Prog false w w) (a : RationE8), ∀ n,0<n →
    (run s n).OK (receipt (stretchE8 n)) (calorieE8 a (stretchE8 n)) ((n+2)^a.p) := by
  have H : onlyLengthE8.Nick fun i => stretchE8 (entryE8 i) :=
    ((Nick.wc 2).mul onlyLength_numE8).sub (Nick.wc 1)
  obtain ⟨s,a,ha⟩ := (H.landOrderE8 (fun i => stretch_posE8 i.property)).ration
  exact ⟨s,a,fun i hi => ha ⟨i,hi⟩⟩

def towerOneE8 : Bench false (SizesE8×Line) :=
  ⟨fun i => entryE8 i.1,dftInKind,fun i =>
    (entryE8 i.1, root (receipt (entryE8 i.1)),Tape.tab (entryE8 i.1) i.2)⟩

lemma executeOneE8 : ∃ (s : Prog false dftInKind dftOutKind) (a : RationE8),
    ∀ (n : ℕ),0<n → ∀ x : Vec n,
    (run s (n, root (receipt n), (⟨n,x⟩ : Tape ℂ))).OK
      (⟨n, dft n x⟩ : Tape ℂ) (calorieE8 a n) ((n+2)^a.p) := by
  let K := towerOneE8
  have ht : K.Moves (fun _ => 0) dftInKind K.env := envNow K
  let n (i : SizesE8 × Line) := entryE8 i.1
  have hk : K.Nick n := ⟨ht.fst,Small.self _⟩
  have H := hk.landE8 (fun i => i.1.property) (ht.snd.fst) false (x:=Prod.snd) (cl:=Paint.left)
    (ht.snd.snd)
  obtain ⟨s,a,ha⟩ := H.ration
  refine ⟨s,a,fun n hn x => ?_⟩
  specialize ha ((⟨n,hn⟩:SizesE8),extendLine x)
  change (run s (n,root (receipt n),(⟨n,front n (extendLine x)⟩:Tape ℂ))).OK
    (⟨n,front n (freq n (pr false n) (extendLine x))⟩ : Tape ℂ) _ _ at ha
  rw [← dft_front n,front_exact] at ha
  exact ha

def towerBothE8 : Bench true (SizesE8×Line×Line) :=
  ⟨fun i => entryE8 i.1,convInKind,fun i =>
    (entryE8 i.1, root (receipt (stretchE8 (entryE8 i.1))),Tape.tab (entryE8 i.1) i.2.1,
      Tape.tab (entryE8 i.1) i.2.2)⟩

lemma executeBothE8 : ∃ (s : Prog true convInKind convOutKind) (a : RationE8),
    ∀ (n : ℕ),0<n → ∀ x y : Vec n,
    (run s (n, root (receipt (stretchE8 n)), (⟨n,x⟩ : Tape ℂ),(⟨n,y⟩ : Tape ℂ))).OK
      (⟨stretchE8 n, conv n x y⟩ : Tape ℂ) (calorieE8 a (stretchE8 n)) ((n+2)^a.p) := by
  let K := towerBothE8
  have ht : K.Moves (fun _ => 0) convInKind K.env := envNow K
  let n (i : SizesE8 × Line×Line) := entryE8 i.1
  have hk : K.Nick n := ⟨ht.fst,Small.self _⟩
  have H := fusingE8 hk (fun i => i.1.property) (x:=fun i => i.2.1) (y:=fun i => i.2.2)
    ht.snd.snd.fst ht.snd.snd.snd ht.snd.fst
  obtain ⟨s,a,ha⟩ := H.ration
  refine ⟨s,a,fun n hn x y => ?_⟩
  specialize ha ((⟨n,hn⟩:SizesE8),extendLine x,extendLine y)
  change (run s (n,root (receipt (stretchE8 n)),
    (⟨n,front n (extendLine x)⟩:Tape ℂ),(⟨n,front n (extendLine y)⟩:Tape ℂ))).OK
    (⟨2*n-1,front (2*n-1)
      (cyclic (2*n-1) (padline n (extendLine y)) (padline n (extendLine x)))⟩ : Tape ℂ) _ _ at ha
  rw [cyclic_pad_front,front_exact,front_exact] at ha
  exact ha

theorem flagshipOneE8 : ∃ order solve a b,
    DFTProgram order solve (lunchE8 a b id) ∧
    ∀ n, 0<n → (run order n).val = receipt n := by
  obtain ⟨o,a,ho⟩ := orders1E8
  obtain ⟨s,b,hs⟩ := executeOneE8
  obtain ⟨c,hc⟩ := storehouseE8 id (fun _ h => h) (Small.self entryE8) a b
  refine ⟨o,s,a,b,⟨c,fun n hn => ?_⟩,fun n hn => (ho n hn).result⟩
  obtain ⟨hu,hA,hB,hR⟩ := hc n hn
  have H := ho n hn
  have HH := receipt_bound n hn
  have he := H.result
  refine ⟨hu,H.bound.trans hA,H.valid,he.symm ▸ HH.1,he.symm ▸ ?_,he.symm ▸ hR,fun x => ?_⟩
  · exact HH.2.trans_le (by omega)
  dsimp only
  rw [he]
  have hj := hs n hn x
  exact ⟨hj.valid,hj.bound.trans hB,add_le_add (add_le_add_left H.time 1) hj.time,hj.result⟩

theorem flagshipBothE8 : ∃ order solve a b,
    ConvProgram order solve (lunchE8 a b stretchE8) ∧
    ∀ n, 0<n → (run order n).val = receipt (stretchE8 n) := by
  obtain ⟨o,a,ho⟩ := orders2E8
  obtain ⟨s,b,hs⟩ := executeBothE8
  obtain ⟨c,hc⟩ := storehouseE8 stretchE8 (fun _ h => stretch_posE8 h)
    (((Small.const _ 2).mul (Small.self entryE8)).sub (Q:=fun _ => 1)) a b
  refine ⟨o,s,a,b,⟨c,fun n hn => ?_⟩,fun n hn => (ho n hn).result⟩
  obtain ⟨hu,hA,hB,hR⟩ := hc n hn
  have H := ho n hn
  have HH := receipt_bound _ (stretch_posE8 hn)
  have he := H.result
  refine ⟨hu,H.bound.trans hA,H.valid,he.symm ▸ HH.1,he.symm ▸ ?_,he.symm ▸ hR,fun x y => ?_⟩
  · exact HH.2.trans_le (by unfold stretchE8; omega)
  dsimp only
  rw [he]
  have hj := hs n hn x y
  exact ⟨hj.valid,hj.bound.trans hB,add_le_add (add_le_add_left H.time 1) hj.time,hj.result⟩

end RAM.Bench
end
end PowerSaving

end OAI
