import OAI.Computability.FourierTransform.RootPreparation
import Work.FourierE8.WorkingCompiler

/-
Modified copy of lean/OAI/Computability/FourierTransform/WorkingPreparation.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain_e8.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `E8`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaE8 = 1 - 8762479/10^10` and `hillsE8` (Work/FourierE8/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsE8_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `E8` versions from Work/FourierE8/Goal.lean (exponent `1 - 8762478/10^10`);
  * imports point to the copies.
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/- Binary powers for the index and coefficient preparatory scan, and application of
synchronized working transform. -/
namespace PowerSaving.RAM
open Ty Selection Grove Spectral
noncomputable section

namespace Bench
universe U V
variable {ι : Type U} {κ : Type V} {m : Bool} {b : Bench m ι} {q : Bench m κ}
  {n k S : ι→ℕ} {t : Ty}

-- count halving powers
abbrev shiftTyE8 := p w (p sc sc)
def shiftPE8 (n : ℕ) (x : ℂ) : ℕ→T shiftTyE8
  | 0 => (n,x,1)
  | j+1 =>
    let (s,u,b) := shiftPE8 n x j
    (s/2,u*u, if s%2=0 then b else b*u)

namespace shiftPE8
lemma stepP (n : ℕ) (x : ℂ) (j : ℕ) :
    shiftPE8 n x (j+1)=((shiftPE8 n x j).1/2,(shiftPE8 n x j).2.1*(shiftPE8 n x j).2.1,
      if (shiftPE8 n x j).1%2=0 then (shiftPE8 n x j).2.2
      else (shiftPE8 n x j).2.2*(shiftPE8 n x j).2.1) := rfl

lemma real (n : ℕ) (x : ℂ) (j : ℕ) :
    (shiftPE8 n x j).2.2 * (shiftPE8 n x j).2.1^(shiftPE8 n x j).1=x^n := by
  induction j with
  | zero => exact one_mul _
  | succ j ih =>
    let s : ℕ := (shiftPE8 n x j).1
    let a := (shiftPE8 n x j).2.1
    let b := (shiftPE8 n x j).2.2
    rw [stepP]; rw [← ih]
    change (if s%2=0 then b else b*a)*(a*a)^(s/2)=b*a^s
    rw [← pow_two,← pow_mul]
    split
    · rename_i H; rw [show 2*(s/2)=s by omega]
    · rename_i H; rw [mul_assoc,show a * a ^ (2*(s/2)) = a^s by
        simpa only [pow_succ'] using
          (show a^(2*(s/2)+1)=a^s by rw [show 2*(s/2)+1=s by omega])]
lemma countP (n : ℕ) (x : ℂ) (j : ℕ) :
    (shiftPE8 n x j).1=n/2^j := by
  induction j with
  | zero => simp [shiftPE8]
  | succ j ih => rw [stepP]; simp [ih,Nat.div_div_eq_div_mul,pow_succ]

lemma endP (n : ℕ) (x : ℂ) (j : ℕ) (h : n<2^j) :
    (shiftPE8 n x j).2.2=x^n := by
  simpa only [countP, Nat.div_eq_of_lt h, pow_zero,mul_one] using real n x j
end shiftPE8

lemma halvePE8 (h : b.Grain S k) (g : b.Grain S n) (hs : Small S n)
    (hh : ∀ i,k i<2^n i) {x : ι→ℂ} (hp : b.Dry S sc x) :
    b.Dry S sc fun i => x i^k i := by
  let V (i : ι) (j) := shiftPE8 (k i) (x i) j
  have ht := Dry.token b n S V (t:=shiftTyE8)
  have hk : (b.climbs n shiftTyE8 V).Grain (fun i => S i.i) fun i => (V i.i i.j).1 :=
    ⟨ht.fst,(h.small.reindex _).mono fun i => by
      simp only [V,shiftPE8.countP]; apply Nat.div_le_self⟩
  have hx := ht.snd.fst
  have hy := ht.snd.snd
  have HU := cycleG g hs V (h.dry.pair (hp.pair Dry.one))
    ((hk.div (Grain.wc 2)).dry.pair ((hx.mul hx).pair
      ((hk.residue (Grain.wc 2)).dry.branch hy (hy.mul hx))))
  exact HU.snd.snd.congr fun i => shiftPE8.endP _ _ _ (hh i)

namespace Neaps

lemma n_ltE8 (h : b.Neaps S n) (i) :
    n i < 2^S i := by
  have hh := stack_above (n i)
  rw [h.stack_eq] at hh
  omega

def layersPE8 (S : ℕ) : ℕ := 3*S+4
lemma layersGE8 (h : b.Neaps S n) :
    b.Grain S fun i => layersPE8 (S i) :=
  (((Grain.wc 3).mul (h.tidal.grain S)).add (Grain.wc 4))
lemma layersSE8 (S : ι→ℕ) : Small S fun i => layersPE8 (S i) :=
  ((Small.const _ 3).mul (Small.self S)).add (Small.const _ 4)
lemma layersBoundE8 (h : b.Neaps S n) (i) :
    8*(n i)^3 < 2^layersPE8 (S i) := by
  have he : 0<n i := h.pos _
  rw [layersPE8,pow_add,Nat.mul_comm 3,pow_mul]
  calc
    _ ≤ 8*((2^S i)^3) := by gcongr; exact (h.n_ltE8 i).le
    _ < _ := by
      have hh : 0 < (2^S i)^3 := by positivity
      norm_num
      omega

lemma extractPE8 (h : b.Neaps S n) (g : ∀ i,Ports (n i)) (u : b.Grain S k)
    (hk : ∀ i,k i ∣ express (n i))
    (hz : b.Dry S sc fun i => root (receipt (n i))) :
    b.Dry S sc fun i => root (k i) := by
  have hp : ∀ i,k i∣receipt (n i) := fun i => by
    simpa [receipt,g i] using hk i
  have H := halvePE8 (h.receiptG.div u) h.layersGE8 (layersSE8 _) (x:=fun i => root (receipt (n i)))
    (fun i => lt_trans (lt_of_le_of_lt (Nat.div_le_self ..)
      (receipt_bound _ (h.pos _)).2) (h.layersBoundE8 i)) hz
  exact H.congr fun i => root_factor (receipt_bound _ (h.pos _)).1 (hp i)

lemma etaPE8 (h : b.Neaps S n) (g : ∀ i,Ports (n i))
    (hz : b.Dry S sc fun i => root (receipt (n i))) :
    b.Dry S sc fun i => root (2*n i) :=
  h.extractPE8 g ((Grain.wc 2).mul (h.num.grain S)) (fun i => express_eta (n i)) hz

lemma mediumPE8 (h : b.Neaps S n) (g : ∀ i,Ports (n i))
    (hz : b.Dry S sc fun i => root (receipt (n i))) :
    b.Dry S sc fun i => root (barge (n i)).vol :=
  h.extractPE8 g h.bargeL.volL (fun _ => express_volume _) hz

lemma ratioSqE8 {a b n : ℕ} (h : a<4*n) (g : 2 ≤ b) :
    (a/b)*(a/b) ≤ 8*n^3 := by
  have H : (a/b)*2 ≤ a := le_trans (Nat.mul_le_mul_left _ g)
    (Nat.div_mul_le_self a b)
  have hh : a/b ≤ 2*n := by omega
  calc
    _ ≤ (2*n)*(2*n) := Nat.mul_le_mul hh hh
    _ = n^2*4 := by ring
    _ ≤ n^2*(8*n) := Nat.mul_le_mul_left _ (by omega)
    _ = 8*n^3 := by ring

lemma ladeGrainE8 {X : ι→Cart} {e : ι→ℕ}
    (h : b.Lade S X) (g : Small b.size e) (hk : ∀ i, ∀ j<(X i).l, (X i).q j ≤ e i) :
    (b.scan fun i => (X i).l).Grain (fun i => S i.i) fun i => (X i.i).q i.j := by
  let L i := (X i).l
  have H := h.dataL.transfer (Instant.scan b L)
  refine ⟨Dry.pick (t:=w) (k:=During.j) (n:=fun i : During L => L i.i)
    (x:=fun i j => (X i.i).q j) H (chopG h.dimL).dry During.hj,
    (g.reindex _).mono (fun i => hk _ i.j i.hj)⟩

lemma kilnPE8 (h : b.Neaps S n) (g : ∀ i,Ports (n i))
    {z : ι→ℂ} (hu : b.Dry S sc z)
    (hz : b.Dry S sc fun i => root (receipt (n i))) :
    b.Dry S forgeTyE8 fun i =>
      forgeE8 (barge (n i)).l (orderE (n i)) (barge (n i)).q (z i) := by
  let X i := barge (n i)
  let e i := orderE (n i)
  let L i := (X i).l
  have hh (i) := barge_spec (n i) (h.pos _)
  have H := h.bargeL
  have hI : b.Dry S sc fun i => Complex.I :=
    (h.extractPE8 g (Grain.wc 4) (fun i => express_I (n i)) hz).congr (fun _ => root_four)
  let Y i := e i+1
  have hY : b.Grain S Y := h.orderG.add (Grain.wc 1)
  have hSY : Small S Y := h.orderS.add (Small.const _ 1)
  have F := Instant.scan b Y
  have hj := chopG hY
  have hE : Small (b.scan Y).size (fun i => 2^i.j) :=
    ((h.powOrderS.trans h.tidal.small).reindex _).mono (fun i =>
      Nat.pow_le_pow_right (by omega) (Nat.le_of_lt_succ i.hj))
  have hk := hj.twoPow ((hSY.reindex _).mono fun i => i.hj.le) hE
  have hv := arrayG hY hSY (fun _ => halosE8) (t:=sc)
    ((h.transfer F).extractPE8 (fun i => g i.i) hk
      (fun i => express_halo _ _ (Nat.le_of_lt_succ i.hj)) (hz.transfer F))
  have G := Instant.scan b L
  let A (i : During L) := (X i.i).vol
  let B (i : During L) := (X i.i).q i.j
  have hb : (b.scan L).Grain (fun i => S i.i) B :=
    ladeGrainE8 (X:=X) H h.powOrderG.small (fun i => (hh i).sizes)
  have Ha : (b.scan L).Grain (fun i => S i.i) A := H.volL.transfer G
  have HG := h.transfer G
  have HE (i : During L) : (A i / B i)*(A i / B i) < 2 ^ layersPE8 (S i.i) := by
    have He : 2 ≤ B i := (hh _).square.isles.good i.j i.hj
    have Hh : A i < 4*n i.i := (hh _).upper
    exact lt_of_le_of_lt (ratioSqE8 Hh He) (HG.layersBoundE8 i)
  have HD := halvePE8 ((Ha.div hb).mul (Ha.div hb)) HG.layersGE8 (layersSE8 _) HE (hu.transfer G)
  have HS := arrayG H.dimL H.countS
    (fun i j => spray (z i) (extent (X i).q (X i).l) ((X i).q j)) (t:=sc)
    (HD.congr fun i => by rw [spray,show extent (X i.i).q (X i.i).l=(X i.i).vol
      from (hh _).square.agrees.symm])
  exact H.dimL.dry.pair (h.orderG.dry.pair (H.dataL.pair (hI.pair (hv.pair HS))))

-- adjusted budget name
end Neaps

open Slant
def legE8 (n : ℕ) := (score (orderE n)+1)*((barge n).vol*hillsE8 (barge n).l)

theorem Neaps.streamPE8 (h : b.Neaps S n) (g : ∀ i,Ports (n i))
    (hz : b.Dry S sc fun i => root (receipt (n i)))
    {z : ι→ℂ} (hu : b.Dry S sc z)
    (hp : ∀ i, IsPrimitiveRoot (z i) (barge (n i)).vol)
    {x : ι→Line} {cl} (hx : b.Moves (fun _ => 0) (a (c cl)) fun i =>
      Tape.tab (barge (n i)).vol (x i)) :
    ∃ d : ℕ,b.Moves (fun i => legE8 (n i)+(S i+2)^d)
      (a (c cl)) fun i => Tape.tab (barge (n i)).vol
        (freq (barge (n i)).vol (z i) (x i)) := by
  let X i := barge (n i)
  have hX i := barge_spec (n i) (h.pos _)
  have he i : (X i).vol=extent (X i).q (X i).l := (hX _).square.agrees
  have hh := effuseE8 (r:=fun i => (X i).q) (l:=fun i => (X i).l) (fun i => (hX _).square.isles)
    (fun i => (hX _).sizes) (fun i => he i ▸ hp i) h.bargeL.countS h.powOrderS h.tidal.small
    (h.bargeL.volume.mono (fun i => (he i).symm.le)) (b:=b) (x:=x)
    (h.kilnPE8 g hu hz) (hx.congr fun i => congrArg (fun d => Tape.tab d (x i)) (he i))
  obtain ⟨d,hd⟩ := hh
  refine ⟨d, (hd.weaken (Dom.of_le fun i => ?_)).congr fun i => ?_⟩
  · simp only [legE8, ← he]; exact le_rfl
  · simp only [← he, X]

end Bench
end
end PowerSaving.RAM

end OAI
