import OAI.Computability.FourierTransform.PowerTables
import Work.Fourier233.WorkingPreparation

/-
Modified copy of lean/OAI/Computability/FourierTransform/ArbitraryLength.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain233.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `Y`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaY = 1 - 7547361/10^10` and `hillsY` (Work/Fourier233/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsY_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `Y` versions from Work/Fourier233/Goal.lean (exponent `1 - 7547360/10^10`);
  * imports point to the copies.
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/- The working length chirp algorithm. Broad branch. -/
namespace PowerSaving.RAM
open Ty Selection Spectral
noncomputable section
namespace Bench
universe U V
variable {ι : Type U} {κ : Type V} {m : Bool} {b : Bench m ι} {q : Bench m κ}
  {s t : Ty} {S n N : ι→ℕ} {ret : Bool}

def surfY (d n s : ℕ) := n+legY n+(s+2)^d
lemma surf_degY (s n : ℕ) {c d : ℕ} (h : c≤d) : surfY c n s ≤ surfY d n s :=
  Nat.add_le_add_left (Small.pow_mono_degree _ h) _

def SwiftY (b : Bench m ι) (n S : ι→ℕ) (t : Ty) (x : ι→T t) : Prop :=
  ∃ d : ℕ,b.Moves (fun i => surfY d (n i) (S i)) t x

namespace SwiftY
variable {x y : ι→T t}
lemma of_moves {W} (h : b.Moves W t x) (g : Dom n W) :
    b.SwiftY n S t x :=
  ⟨0,h.weaken ((Dom.of_le fun i => by unfold surfY; omega).trans g)⟩
lemma of_dry (h : b.Dry S t x) : b.SwiftY n S t x :=
  let ⟨d,hd⟩ := h
  ⟨d, hd.mono fun _ => Nat.le_add_left _ _⟩
lemma pair {v : ι→T s} (h : b.SwiftY n S t x) (g : b.SwiftY n S s v) :
    b.SwiftY n S (p t s) fun i => (x i,v i) :=
  let ⟨d,hd⟩ := h
  let ⟨l,hl⟩ := g
  ⟨d+l, (hd.weaken (Dom.of_le fun i => surf_degY (S i) (n i) (by omega))).pair
    (hl.weaken (Dom.of_le fun i => surf_degY (S i) (n i) (by omega)))⟩
lemma bind {v : ι→T s} (h : b.SwiftY n S t x) (g : (b.extend t x).SwiftY n S s v) :
    b.SwiftY n S s v :=
  let ⟨d,hd⟩ := h
  let ⟨l,hl⟩ := g
  ⟨d+l, caseM (hd.weaken (Dom.of_le fun i => surf_degY (S i) (n i) (by omega)))
    (hl.weaken (Dom.of_le fun i => surf_degY (S i) (n i) (by omega)))⟩
end SwiftY

def tailVolY (n : ℕ) : ℕ := (barge n).vol

structure CruiseY (b : Bench m ι) (n S N : ι→ℕ) : Prop where
  dims : b.Neaps S n
  port : ∀ i, Ports (n i)
  rootP : b.Dry S sc fun i => root (receipt (n i))
  ac : ∀ i, tailVolY (n i)=N i
  sizeL : b.Nick N

lemma signPY (ret : Bool) (h : ∀ i,0<n i) (g : b.Dry S sc fun i => root (n i)) :
    b.Dry S sc fun i => pr ret (n i) := by
  cases ret
  · exact g
  · exact g.inv fun i => (root_primitive _ (h i)).ne_zero (Nat.ne_of_gt (h i))

lemma table_scaleY {x y : ι→Line} {cl} (h : b.Nick N)
    (hx : b.Moves (fun _ => 0) (a sc) fun i => Tape.tab (N i) (x i))
    (hy : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (N i) (y i)) :
    b.Moves N (a (c cl)) fun i => Tape.tab (N i) fun j => x i j*y i j := by
  have F := Instant.scan b N
  refine arrayNow h _ ((Moves.pick (t:=sc) (n:=fun i : During N => N i.i)
    (k:=During.j) (fun i j => x i.i j) (hx.transfer F) (chop h).close During.hj).mul
    (Moves.pick (t:=c cl) (n:=fun i : During N => N i.i) (k:=During.j) (fun i j => y i.i j)
      (hy.transfer F) (chop h).close During.hj))

namespace CruiseY
variable {cl : Paint} {x y : ι→Line}

lemma transfer {S n N : κ→ℕ} (h : q.CruiseY n S N) {f} (g : b.Instant q f) :
    b.CruiseY (fun i => n (f i)) (fun i => S (f i)) (fun i => N (f i)) :=
  ⟨h.dims.transfer g,fun _ => h.port _,h.rootP.transfer g,fun _ => h.ac _,h.sizeL.transfer g⟩

lemma volume_ge (h : b.CruiseY n S N) (i) : 2*n i ≤ N i :=
  h.ac i ▸ (barge_spec _ (h.dims.pos i)).lower
lemma volume_lt (h : b.CruiseY n S N) (i) : N i < 4*n i :=
  h.ac i ▸ (barge_spec _ (h.dims.pos i)).upper
lemma volume_pos (h : b.CruiseY n S N) (i) : 0<N i := by
  have hh := h.volume_ge i; have hk := h.dims.pos i; omega

lemma dom (h : b.CruiseY n S N) : Dom n N :=
  ⟨4,fun i => by have := h.volume_lt i; omega⟩

lemma flood (h : b.CruiseY n S N) (r : Bool)
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (N i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i => Tape.tab (N i) (freq (N i) (pr r (N i)) (x i)) := by
  let z (i) := pr r (N i)
  have H (i) : (barge (n i)).vol=N i := h.ac i
  have hu := signPY r h.volume_pos ((h.dims.mediumPY h.port h.rootP).congr fun i =>
    congrArg root (H i))
  obtain ⟨d,hd⟩ := h.dims.streamPY h.port h.rootP (z:=z) (x:=x) hu
    (fun i => (H i).symm ▸ show IsPrimitiveRoot (z i) (N i) from primitive_pr _ (h.volume_pos i) r)
    (hx.congr fun i => congrArg (fun u => Tape.tab u (x i)) (H i).symm)
  refine ⟨d,?_⟩
  refine (hd.weaken (Dom.of_le fun i => ?_)).congr fun i => ?_
  · unfold surfY; omega
  · rw [H]

lemma flood' (h : b.CruiseY n S N) (r : Bool) (hx : b.SwiftY n S (a (c cl)) fun i =>
    Tape.tab (N i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i => Tape.tab (N i) (freq (N i) (pr r (N i)) (x i)) := by
  let V (i : ι) : T (a (c cl)) := Tape.tab (N i) (x i)
  exact hx.bind ((h.transfer (Instant.extend b V)).flood r (x:=x) (cherry b V (t:=a (c cl))))

lemma posts (h : b.CruiseY n S N) (r : Bool) :
    b.SwiftY n S (a sc) fun i => tablePow (pr r (2*n i)) (S i) := by
  let z (i) : T sc := pr r (2*n i)
  have hh : b.SwiftY n S sc z :=
    SwiftY.of_dry (signPY r (fun i => by have := h.dims.pos i; omega)
      (h.dims.etaPY h.port h.rootP))
  have F := Instant.extend b z (t:=sc)
  exact hh.bind (SwiftY.of_moves (pylon (h.dims.tidal.transfer F)
    (g:=h.dims.stackPow) (cherry b z (t:=sc))) ⟨4,fun i => by
    dsimp only [id]
    have hh : 2^S i ≤ 4*n i := h.dims.stack_eq i ▸ stack_pow (n i) (h.dims.pos i); omega⟩)

lemma pearl (h : b.CruiseY n S N) (r : Bool)
    (hp : b.Moves (fun _ => 0) (a sc) fun i => tablePow (pr r (2*n i)) (S i))
    {k} (hk : b.Nick k) :
    b.Moves (fun _ => 0) sc fun i => epschirp (pr r (2*n i)) (k i) :=
  square_pow h.dims.stackPow hp ((Nick.wc 2).mul h.dims.num)
    (fun i => ⟨by have := h.dims.pos i; omega,h.dims.stack_eq i ▸ (stack_above (n i)).le⟩)
    (fun i => (primitive_pr (2*n i) (by have := h.dims.pos i; omega) r).pow_eq_one) hk

-- two prep arrays
lemma risen (h : b.CruiseY n S N) (r : Bool)
    (hp : b.Moves (fun _ => 0) (a sc) fun i => tablePow (pr r (2*n i)) (S i))
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (n i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i => Tape.tab (N i) (chirp_seed (n i) (pr r (2*n i)) (x i)) := by
  have F := Instant.scan b N
  have hh := h.transfer F
  have hj := chop h.sizeL
  have H := (hh.pearl r (hp.transfer F) hj).mul (pick_all (t:=c cl)
    (n:=fun i : During N => n i.i) (fun (i : During N) j => x i.i j) (hx.transfer F) hj)
  refine SwiftY.of_moves (arrayNow h.sizeL _ (H.congr fun i => ?_)) h.dom
  simp only [chirp_seed,mul_ite]; congr 1
  exact mul_zero _

lemma fallen (h : b.CruiseY n S N) (r : Bool)
    (hp : b.Moves (fun _ => 0) (a sc) fun i => tablePow (pr r (2*n i)) (S i)) :
    b.SwiftY n S (a sc) fun i => Tape.tab (N i) (fall (n i) (N i) (pr r (2*n i))) := by
  let z i := pr r (2*n i)
  have F := Instant.scan b N
  have hh := h.transfer F
  have hj := chop h.sizeL
  have hg := hh.sizeL.sub hj
  have hk := (((hj.cmp hh.dims.num).branch hg hj)).congr
    (y:=fun i => legdist (n i.i) (N i.i) i.j) (fun i => by
    by_cases e : i.j < n i.i <;> simp [legdist,e])
  refine SwiftY.of_moves (arrayNow h.sizeL _ ((hh.pearl r (hp.transfer F) hk).inv fun i => ?_)) h.dom
  have Hu : 0<2*n i.i := by have := h.dims.pos i.i; omega
  exact pow_ne_zero _ ((primitive_pr _ Hu r).ne_zero (Nat.ne_of_gt Hu))

lemma pyramid (h : b.CruiseY n S N) (r : Bool)
    (hp : b.Moves (fun _ => 0) (a sc) fun i => tablePow (pr r (2*n i)) (S i))
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (n i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i =>
      Tape.tab (N i) (fetchC (N i) (pr false (N i))
        (fall (n i) (N i) (pr r (2*n i)))
        (chirp_seed (n i) (pr r (2*n i)) (x i))) := by
  let z i := pr r (2*n i)
  let A i := freq (N i) (pr false (N i)) (fall (n i) (N i) (z i))
  let B i := freq (N i) (pr false (N i)) (chirp_seed (n i) (z i) (x i))
  let V (i) : T (p (a sc) (a (c cl))) := (Tape.tab (N i) (A i),Tape.tab (N i) (B i))
  have H := (h.flood' false (h.fallen r hp)).pair (h.flood' false (h.risen r hp hx))
  have F := Instant.extend b V
  have hk := cherry b V (W:=fun _ => 0)
  exact h.flood' true (x:=fun i => pointC (N i) (pr false (N i))
        (fall (n i) (N i) (z i)) (chirp_seed (n i) (z i) (x i)))
    (H.bind (SwiftY.of_moves (table_scaleY (h.sizeL.transfer F) (x:=A) (y:=B) hk.fst hk.snd) h.dom))

lemma singing (h : b.CruiseY n S N) (r : Bool)
    (hp : b.Moves (fun _ => 0) (a sc) fun i => tablePow (pr r (2*n i)) (S i))
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (n i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i =>
      Tape.tab (n i) (freq (n i) (pr r (n i)) (x i)) := by
  let z i := pr r (2*n i)
  let B i := fetchC (N i) (pr false (N i)) (fall (n i) (N i) (z i))
    (chirp_seed (n i) (z i) (x i))
  have H := SwiftY.pair (h.pyramid r hp hx) (SwiftY.of_moves h.sizeL.numeralM h.dom)
  let V (i : ι) : T (p (a (c cl)) sc) := (Tape.tab (N i) (B i),(N i:ℂ))
  have F := Instant.extend b V
  have G := Instant.scan (b.extend _ V) n
  have hh := h.transfer (G.next F)
  have hk := Moves.transfer (cherry b V (W:=fun _ => 0)) G
  have hj := h.dims.num.transfer F
  have HL := chop hj
  have HS := Moves.pick (n:=fun i : During n => N i.i) (k:=During.j) (t:=c cl)
    (fun i => B i.i) hk.fst HL.close (fun i => by
      have hh := h.volume_ge i.i; have hk := i.hj; omega)
  have hd := (hh.pearl r (hp.transfer (G.next F)) HL).mul
    ((hk.snd.inv fun i => Nat.cast_ne_zero.mpr (Nat.ne_of_gt (h.volume_pos i.i))).mul HS)
  exact H.bind (SwiftY.of_moves (arrayNow hj _ (hd.congr fun i =>
    chirps _ _ (h.dims.pos i.i) (h.volume_ge i.i) r _ _ i.hj)) (Dom.self n))

lemma deliver (h : b.CruiseY n S N) (r : Bool)
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (n i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i =>
      Tape.tab (n i) (freq (n i) (pr r (n i)) (x i)) := by
  let V i := tablePow (pr r (2*n i)) (S i)
  have F := Instant.extend b V (t:=a sc)
  exact (h.posts r).bind ((h.transfer F).singing r (cherry b V (t:=a sc)) (hx.transfer F))

end CruiseY

lemma Neaps.swiftY (h : b.Neaps S n) (g : ∀ i,Ports (n i))
    (hz : b.Dry S sc fun i => root (receipt (n i))) (r : Bool)
    {x : ι→Line} {cl} (hx : b.Moves (fun _ => 0) (a (c cl)) fun i =>
      Tape.tab (n i) (x i)) :
    b.SwiftY n S (a (c cl)) fun i =>
      Tape.tab (n i) (freq (n i) (pr r (n i)) (x i)) := by
  let N i := tailVolY (n i)
  have F := Instant.extend b N (t:=w)
  have hh : (b.extend w N).CruiseY n S N :=
    ⟨h.transfer F,g,hz.transfer F,fun i => rfl,⟨cherry b N (t:=w),h.bargeL.volume⟩⟩
  exact (SwiftY.of_dry h.bargeL.volL.dry).bind (hh.deliver r (hx.transfer F))

end Bench
end
end PowerSaving.RAM

end OAI
