import Work.Fourier233.SynchronizedAlgorithm
import OAI.Computability.FourierTransform.ChineseRemainder

/-
Modified copy of lean/OAI/Computability/FourierTransform/WorkingTransform.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain233.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `Y`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaY = 1 - 7547361/10^10` and `hillsY` (Work/Fourier233/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsY_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `Y` versions from Work/Fourier233/Goal.lean (exponent `1 - 7547360/10^10`);
  * imports point to the copies.
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/-! CRT and tensor schedule. -/
namespace PowerSaving.RAM
open Grove Slant Ty Spectral
noncomputable section
universe U V

namespace Bench
variable {m : Bool} {ι : Type U} {κ : Type V} {b : Bench m ι} {q : Bench m κ}
  {cl : Paint} {l d : ι→ℕ} {r : ι→Axes} {u : ι→ℕ→Reel} {x : ι→Line}

abbrev dualWordY := p w w
def chartY (r : Axes) (l : ℕ) (j : ℕ) : T dualWordY := (extent r l,ford r l j)

namespace Fen

open Forks

lemma chartTY (h : b.Fen l r) (hh : ∀ i, Isles (r i) (l i)) :
    b.Moves (fun i => extent (r i) (l i)) (a dualWordY) fun i =>
      Tape.tab (extent (r i) (l i)) (chartY (r i) (l i)) := by
  let S i := chartY (r i)
  refine h.visit S ((Moves.wc 1).pair (Moves.wc 0)) ?_
  let D := Fen.stalk b l r dualWordY S
  have F := Fen.stalkFeeds b l r dualWordY S
  have hv := h.stalkReads S
  have hb := h.midst.reindex (During.i (n:=routes l r))
  have ha : D.Nick fun i => extent (r i.i.i) i.i.j :=
    ⟨hv.2.2.fst,hb⟩
  have hk := h.part.transfer F
  have he := ha.mul hk
  have hm : D.Nick fun i => ford (r i.i.i) i.i.j (tUp i) := by
    refine ⟨hv.2.2.snd,hb.mono ?_⟩
    intro i
    exact ((ford_rel ((hh i.i.i).cut i.i.hj.le)).bd _ (h.smaller _)).le
  exact he.close.pair (((hm.mul hk).add (hv.2.1.mul ha)).residue he).close
end Fen

namespace ThicketY
variable {z : ι → ℂ}

private lemma via (h : b.ThicketY l d r u) (hh : ∀ i, Isles (r i) (l i))
    (hz : ∀ i, IsPrimitiveRoot (z i) (extent (r i) (l i)))
    (hg : ∀ i, ∀ j<l i, Creates (u i j) (r i j)
      (winds _ (spray (z i) (extent (r i) (l i)) (r i j))))
    (hI : b.Moves (fun _ => 0) sc fun _ => Complex.I)
    (hF : b.Moves (fun _ => 0) (a dualWordY) fun i =>
      Tape.tab (extent (r i) (l i)) (chartY (r i) (l i)))
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (extent (r i) (l i)) (x i)) :
    b.Moves (fun i => (d i+1)*(extent (r i) (l i)*hillsY (l i))) (a (c cl))
      fun i => Tape.tab (extent (r i) (l i)) (freq (extent (r i) (l i)) (z i) (x i)) := by
  let n i := extent (r i) (l i)
  let W i := (d i+1)*(n i*hillsY (l i))
  let C i := ford (r i) (l i)
  let y i j := x i (C i j)
  let A i := Tape.tab (n i) (y i)
  let V i := freq (n i) (z i) (x i)
  let Z i := Tape.tab (n i) fun j => V i (C i j)
  let M i := fun j => gale (spray (z i) (n i) (r i j))
  have H : Dom W n := Dom.of_le fun i => le_trans (Nat.le_mul_of_pos_right _
    (hillsY_pos _)) (Nat.le_mul_of_pos_left _ (Nat.succ_pos _))
  have hn : b.Nick n := ⟨hx.len h.fen.span,h.fen.span⟩
  have hhC i : Reloc (n i) (C i) := ford_rel (hh i)
  have hp := chop hn
  have F := Instant.scan b n
  have hc := (Moves.pick (t:=dualWordY) (n:=fun i : During n => n i.i) _ (hF.transfer F) hp.close During.hj).snd
  have hy : b.Moves W (a (c cl)) A := by
    have hx' := Moves.pick (t:=c cl) (n:=fun i : During n => n i.i)
      (fun i => x i.i) (hx.transfer F) hc (fun i => (hhC i.i).bd _ i.hj)
    exact (arrayNow (t:=c cl) hn y hx').weaken H
  have hz' : b.Moves W (a (c cl)) Z := by
    let D := b.extend (a (c cl)) A
    have G := Instant.extend b A (t:=a (c cl))
    have ht := (h.transfer G).stream (x:=y) (hI.transfer G) (cherry b A (t:=a (c cl))) M hg
    refine caseM hy ((ht.congr ?_).weaken ?_)
    · intro i
      exact tapeCongrY (n i) _ _ fun j hj => graft_ford (hh _) (hz _) _ j hj
    · exact Dom.of_le (fun i => Nat.mul_le_mul_right (n i*hillsY (l i)) (Nat.le_succ (d i)))
  let B := b.extend (a (c cl)) Z
  have G := Instant.extend b (t:=a (c cl)) Z
  have he : B.Nick n := hn.transfer G
  have I1 := Instant.scan B n
  have I2 : (B.scan n).Instant (b.scan n) id :=
    Instant.select (I1.next G) (chop he).close
  have ht := Moves.pick (b:=B.scan n) (t:=c cl) (n:=fun i => n i.i) (fun i j => V i.i (C i.i j))
    ((cherry b Z (W:=fun _=>0) (t:=a (c cl))).transfer I1) (chop he).close During.hj
  have hg' := scatterNow (t:=c cl) he (fun i j => (C i j,V i (C i j))) ((hc.transfer I2).pair ht)
  refine caseM hz' ((hg'.weaken H).congr ?_)
  intro i; rw [(hhC i).sow (fun j => V i (C i j)) _]
  exact tapeCongrY (n i) _ _ fun j hj => congr_arg (V i) ((hhC i).seeks hj).2

theorem traverse (h : b.ThicketY l d r u) (hh : ∀ i, Isles (r i) (l i))
    (hz : ∀ i, IsPrimitiveRoot (z i) (extent (r i) (l i)))
    (hg : ∀ i, ∀ j<l i, Creates (u i j) (r i j)
      (winds _ (spray (z i) (extent (r i) (l i)) (r i j))))
    (hI : b.Moves (fun _ => 0) sc fun _ => Complex.I)
    (hx : b.Moves (fun _ => 0) (a (c cl)) fun i => Tape.tab (extent (r i) (l i)) (x i)) :
    b.Moves (fun i => (d i+1)*(extent (r i) (l i)*hillsY (l i))) (a (c cl))
      fun i => Tape.tab (extent (r i) (l i)) (freq (extent (r i) (l i)) (z i) (x i)) := by
  let n i := extent (r i) (l i)
  let A i := Tape.tab (n i) (chartY (r i) (l i))
  have F := Instant.extend b A (t:=a dualWordY)
  have ht := via (h.transfer F) (z:=z) hh hz hg
    (hI.transfer F) (cherry b A (t:=a dualWordY)) (x:=x) (hx.transfer F)
  refine caseM ((h.fen.chartTY hh).weaken ?_) ht
  exact Dom.of_le fun i => le_trans (Nat.le_mul_of_pos_right (n i)
    (hillsY_pos (l i))) (Nat.le_mul_of_pos_left _ (Nat.succ_pos _))

end ThicketY

end Bench
end
end PowerSaving.RAM

end OAI
