import Work.CarrierCheck.B2
import Work.CarrierCheck.InstB2Ke16

/-!
# (key: carrier-check) Bridged word B_2 with the carrier certificate `Cr2h16` (h = 16): final theorems

GENERATED by checks/wht12/carrier-check/py/crate.py (pattern of `Work/BridgeGeom/B2L16.lean`).  No `sorry`.

The network is `SSC.CCert.Valid.bridge2_bcert` (`Work.CarrierCheck.B2`): `BG.bridge2_bcert_geom` (label space
`L5 (Fin h)` of dimension `m = 80`, one unit per orthogonal matrix of the label space with `9362` live roles,
five erase-wrapped invocations on ONE shared set of `R = 7122` dirty helper slots) applied to the invocation
package `CarrierCr2h16.inv` = the carrier invocation theorem `CR.Phased.inv` (`Work.Carrier`) on the carrier
certificate `SSC.Cr2h16.cert`, accepted by the three kernel checks of `Work.CarrierCheck`.

* `B2Ke16.certificate_block`        the block certificate, price `card Γ * BridgeRate.B2Ke16.unitPrice φ`;
* `WHT.wht_main_B2Ke16`             whole-block recursion, `1 - 53992/10^8`;
* `WHT.wht_main_perRank_B2Ke16`     per-rank recursion, `1 - 31553/10^8`;
* `WHT.wht_main_B2Ke16x`            whole-block, fuller table (`s = 40`): `1 - 5399225/10^10`;
* `WHT.wht_main_perRank_B2Ke16x`    per-rank, fuller table: `1 - 3155781/10^10`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving

namespace B2Ke16
open Finset Binary Matrix RAM SS CB RF BR BG
noncomputable section

/-- the kernel-checked carrier certificate -/
abbrev cert : SSC.CCert := CarrierCr2h16.cert

theorem card_label : Fintype.card (L5 (Fin cert.p.h)) = 80 := by
  rw [card_L5, Fintype.card_fin]
  rfl

/-- **Block certificate of the bridged word B_2** (carrier certificate `Cr2h16`, h = 16). -/
theorem certificate_block :
    ∃ (Γ : Type) (_ : Fintype Γ) (_ : DecidableEq Γ), 1 ≤ Fintype.card Γ ∧
      BCert (L5 (Fin cert.p.h))
        (Sum.inl : BLive Γ (Fin cert.v) (Fin cert.R) →
          BRole Γ (Fin cert.v) (Fin cert.R) (Fin cert.ret.length))
        (fun φ => (Fintype.card Γ : ℝ) * BridgeRate.B2Ke16.unitPrice φ) :=
  CarrierCr2h16.valid.bridge2_bcert SSC.Cr2h16.scalarCheck_ok

theorem card_live (Γ : Type) [Fintype Γ] :
    Fintype.card (BLive Γ (Fin cert.v) (Fin cert.R))
      = Fintype.card Γ * (4 * cert.v + cert.R) := by
  rw [card_BLive, Fintype.card_fin, Fintype.card_fin]

end

end B2Ke16

namespace WHT
open BlockWHT

/-- **Walsh-Hadamard transform, whole-block recursion on the bridged word B_2 with the carrier certificate `Cr2h16`**: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with
`1 - 2/10^11` replaced by `1 - 53992/10^8`. -/
theorem wht_main_B2Ke16 :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 53992/(10:ℝ)^8) W := by
  obtain ⟨Γ, i1, i2, hG, h⟩ := B2Ke16.certificate_block
  exact BridgeRate.B2Ke16.wht_of_bcert B2Ke16.card_label Sum.inl Sum.inl_injective
    (Fintype.card Γ) hG (B2Ke16.card_live Γ) _ h (fun φ => rfl)

/-- **Walsh-Hadamard transform, per-rank recursion on the same network**: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with
`1 - 2/10^11` replaced by `1 - 31553/10^8`. -/
theorem wht_main_perRank_B2Ke16 :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 31553/(10:ℝ)^8) W := by
  obtain ⟨Γ, i1, i2, hG, h⟩ := B2Ke16.certificate_block
  exact BridgeRate.B2Ke16.wht_perRank_of_bcert B2Ke16.card_label Sum.inl Sum.inl_injective
    (Fintype.card Γ) hG (B2Ke16.card_live Γ) _ h (fun φ => rfl)

/-- **Walsh-Hadamard transform, whole-block recursion on the same network, fuller table (fill parameter `s = 40`)**: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with
`1 - 2/10^11` replaced by `1 - 5399225/10^10`. -/
theorem wht_main_B2Ke16x :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 5399225/(10:ℝ)^10) W := by
  obtain ⟨Γ, i1, i2, hG, h⟩ := B2Ke16.certificate_block
  exact BridgeRate.B2Ke16.wht_of_bcert_x B2Ke16.card_label Sum.inl Sum.inl_injective
    (Fintype.card Γ) hG (B2Ke16.card_live Γ) _ h (fun φ => rfl)

/-- **Walsh-Hadamard transform, per-rank recursion, fuller table**: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with
`1 - 2/10^11` replaced by `1 - 3155781/10^10`. -/
theorem wht_main_perRank_B2Ke16x :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - 3155781/(10:ℝ)^10) W := by
  obtain ⟨Γ, i1, i2, hG, h⟩ := B2Ke16.certificate_block
  exact BridgeRate.B2Ke16.wht_perRank_of_bcert_x B2Ke16.card_label Sum.inl Sum.inl_injective
    (Fintype.card Γ) hG (B2Ke16.card_live Γ) _ h (fun φ => rfl)

end WHT

end PowerSaving
end OAI
#print axioms OAI.PowerSaving.B2Ke16.certificate_block
#print axioms OAI.PowerSaving.WHT.wht_main_B2Ke16
#print axioms OAI.PowerSaving.WHT.wht_main_perRank_B2Ke16
#print axioms OAI.PowerSaving.WHT.wht_main_B2Ke16x
#print axioms OAI.PowerSaving.WHT.wht_main_perRank_B2Ke16x
#check @OAI.PowerSaving.WHT.wht_main_B2Ke16x
