import Work.CarrierCheck.Inv
import Work.CarrierCheck.Gen.Cr2h16Hist
import Work.CarrierCheck.Gen.Cr2h16Lab
import Work.CarrierCheck.Gen.Cr2h16Shape
import Work.CarrierCheck.Gen.Cr2h16Scal

/-!
# (key: carrier-check) Carrier certificate `Cr2h16` (h = 16): interface for network instances

GENERATED by checks/wht12/carrier-check/py/ccgen.py from c2-combine-best-h16.json.  No `sorry`.

`v = 560` triples, `R = 7122` helper slots per invocation, 16 scratch copies, copy cost `cst = 241`.
Everything a network instance needs from the certificate `SSC.Cr2h16.cert`:

* `cert`, `valid : cert.Valid`                 (kernel checks `labelCheck`, `shapeCheck`);
* `cert_h`, `cert_v`, `cert_R`, `cert_nc`      (`rfl`);
* `inv : BR.Inv (Fin cert.p.h) (Fin cert.v) (Fin cert.R) (Fin cert.ret.length)`   the invocation package of the
  bridged network: kernel check `scalarCheck` + the carrier invocation theorem (`CR.Phased.inv`);
* `inv_tv`      its lines;
* `inv_cost`    its price = the blocks of ALL roles of ONE invocation (x roles, y roles, helper slots, scratch
                copies), for every price list, from the kernel-counted histogram (`Gen.Cr2h16Hist`);
* `invBlocks`, `inv_cost_list`   the same as a `(rank, count)` list;
* `inv_moves`   these blocks stand for `R h + 2 v (h - 1) + cst = 130993` unit moves;
* `inv_count`   there are `37286` of them.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving

namespace CarrierCr2h16
open Finset Binary Matrix RAM SS CB BR
noncomputable section

/-- the kernel-checked carrier certificate -/
abbrev cert : SSC.CCert := SSC.Cr2h16.cert

/-- the certificate is valid (kernel checks `labelCheck`, `shapeCheck`) -/
theorem valid : cert.Valid :=
  SSC.CCert.Valid.of_checks SSC.Cr2h16.labelCheck_ok SSC.Cr2h16.shapeCheck_ok

theorem cert_h : cert.p.h = 16 := rfl
theorem cert_v : cert.v = 560 := rfl
theorem cert_R : cert.R = 7122 := rfl
theorem cert_nc : cert.ret.length = 16 := rfl

/-- **the invocation package of the certificate** (kernel check `scalarCheck` + `CR.Phased.inv`) -/
def inv : BR.Inv (Fin cert.p.h) (Fin cert.v) (Fin cert.R) (Fin cert.ret.length) :=
  valid.inv SSC.Cr2h16.scalarCheck_ok

theorem inv_tv : inv.tv = cert.tv := rfl

/-- price of the rank list of one invocation, from the kernel-evaluated counts -/
theorem ranks_cost (φ : ℕ → ℝ) :
    rcost φ cert.invRanks = 10267 * φ 1 + 13137 * φ 2 + 2965 * φ 3 + 3110 * φ 4 + 1262 * φ 5 + 751 * φ 6 + 434 * φ 7 + 223 * φ 8 + 425 * φ 9 + 1235 * φ 10 + 2011 * φ 11 + 598 * φ 12 + 162 * φ 13 + 690 * φ 14 + 15 * φ 15 + 1 * φ 16 := by
  rw [SSC.CCert.rcost_sumW cert φ 16 SSC.Cr2h16.rankBound_ok]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, SSC.Cr2h16.rank0_ok, SSC.Cr2h16.rank1_ok, SSC.Cr2h16.rank2_ok, SSC.Cr2h16.rank3_ok, SSC.Cr2h16.rank4_ok, SSC.Cr2h16.rank5_ok, SSC.Cr2h16.rank6_ok, SSC.Cr2h16.rank7_ok, SSC.Cr2h16.rank8_ok, SSC.Cr2h16.rank9_ok, SSC.Cr2h16.rank10_ok, SSC.Cr2h16.rank11_ok, SSC.Cr2h16.rank12_ok, SSC.Cr2h16.rank13_ok, SSC.Cr2h16.rank14_ok, SSC.Cr2h16.rank15_ok, SSC.Cr2h16.rank16_ok]
  norm_num [bcost]

/-- **Price of ONE invocation**: the blocks of all its roles (x, y, helper slots, scratch copies). -/
theorem inv_cost (φ : ℕ → ℝ) :
    inv.cost φ = 10267 * φ 1 + 13137 * φ 2 + 2965 * φ 3 + 3110 * φ 4 + 1262 * φ 5 + 751 * φ 6 + 434 * φ 7 + 223 * φ 8 + 425 * φ 9 + 1235 * φ 10 + 2011 * φ 11 + 598 * φ 12 + 162 * φ 13 + 690 * φ 14 + 15 * φ 15 + 1 * φ 16 := by
  have e : inv.cost φ = rcost φ cert.invRanks := valid.inv_cost SSC.Cr2h16.scalarCheck_ok φ
  rw [e, ranks_cost φ]

/-- the blocks of one invocation, as `(rank, count)` -/
def invBlocks : List (ℕ × ℕ) := [(1, 10267), (2, 13137), (3, 2965), (4, 3110), (5, 1262), (6, 751), (7, 434), (8, 223), (9, 425), (10, 1235), (11, 2011), (12, 598), (13, 162), (14, 690), (15, 15), (16, 1)]

theorem inv_cost_list (φ : ℕ → ℝ) :
    inv.cost φ = (invBlocks.map fun b => (b.2 : ℝ) * φ b.1).sum := by
  rw [inv_cost φ]
  simp only [invBlocks, List.map_cons, List.map_nil, List.sum_cons, List.sum_nil]
  norm_num
  try ring

/-- the blocks of one invocation stand for `R h + 2 v (h - 1) + cst` unit moves, `cst = 241` -/
theorem inv_moves : inv.cost (fun r => (r:ℝ)) = 7122 * 16 + 2 * 560 * (16 - 1) + 241 := by
  rw [inv_cost]
  norm_num

/-- number of blocks of one invocation -/
theorem inv_count : inv.cost (fun _ => (1:ℝ)) = 37286 := by
  rw [inv_cost]
  norm_num

end

end CarrierCr2h16

end PowerSaving
end OAI
#print axioms OAI.PowerSaving.CarrierCr2h16.valid
#print axioms OAI.PowerSaving.CarrierCr2h16.inv
#print axioms OAI.PowerSaving.CarrierCr2h16.inv_cost
#print axioms OAI.PowerSaving.CarrierCr2h16.inv_moves
#check @OAI.PowerSaving.CarrierCr2h16.inv
#check @OAI.PowerSaving.CarrierCr2h16.inv_cost
