import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: carrier-check) Rate lemmas for one unit of the bridged word B_2 with the carrier certificate `Cr2h16`

GENERATED by checks/wht12/carrier-check/py/crate.py with the text generators of
checks/wht9/bridge-rate/py (used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 9362` live roles, label dimension `m = 80`, deficit `D = 1035`.

* `blocksB2Ke16`            the block list (rank, count) of ONE unit;
* `fold_B2Ke16`             whole-block fact at `1 - 53992/10^8`, fill parameter `s = 13` (slack 2.14e-09);
* `fold_B2Ke16_sharp`       `W ≤ moment` at `1 - 53993/10^8`: fails for every table (excess 1.88e-08);
* `foldRank_B2Ke16`         per-rank fact at `1 - 31553/10^8`, `s = 13` (slack 3.03e-05);
* `foldRank_B2Ke16_sharp`   per-rank: fails for every table at `1 - 31558/10^8`.

That a Lean word has `G` times this list as its block histogram is NOT proved here (see `Work.CarrierCheck.B2Ke16`).
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the CARRIER helper circuit `Cr2h16` (h = 16, m = 80): five invocations (ALL blocks of one invocation: x roles, y roles, helper slots, scratch copies; the kernel-counted ranks of `CarrierCr2h16.inv_cost`), and for each of the v = 560 classes the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 7122 helper slots shared by the five stages. -/
def blocksB2Ke16 : List (ℕ × ℕ) := [(1, 51335), (2, 65685), (3, 14825), (4, 16670), (5, 6310), (6, 3755), (7, 2170), (8, 1115), (9, 2125), (10, 6175), (11, 10055), (12, 2990), (13, 810), (14, 3450), (15, 1195), (16, 5), (30, 1120), (34, 1120)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Ke16_rank : (blocksB2Ke16.map fun b => b.1 * b.2).sum = 9362 * 80 - 1035 := by
  norm_num [blocksB2Ke16]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Ke16_tally : (blocksB2Ke16.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((9362:ℕ):ℝ) * ((80:ℕ):ℝ) - ((1035:ℕ):ℝ) := by
  norm_num [blocksB2Ke16]

theorem blocksB2Ke16_count : (blocksB2Ke16.map fun b => b.2).sum = 190910 := by
  norm_num [blocksB2Ke16]

theorem blocksB2Ke16_proper : ∀ b ∈ blocksB2Ke16, 1 ≤ b.1 ∧ b.1 < 80 := by
  decide

/-- **whole-block fact** of `blocksB2Ke16` at exponent `1 - 53992/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 80, W = 9362).  Relative slack of the rational certificate: 2.14e-09. -/
theorem fold_B2Ke16 :
    ((2:ℝ)^13 - 1) * moment 80 (1 - 53992/(10:ℝ)^8) blocksB2Ke16
      + ((9362:ℕ):ℝ) * (T 80 (1 - 53992/(10:ℝ)^8) (80 - 1) 1 + T 80 (1 - 53992/(10:ℝ)^8) 1 1)
      < (2:ℝ)^13 * ((9362:ℕ):ℝ) := by
  have hsum : moment 80 (1 - 53992/(10:ℝ)^8) blocksB2Ke16
      = T 80 (1 - 53992/(10:ℝ)^8) 1 51335 + (T 80 (1 - 53992/(10:ℝ)^8) 2 65685 + (T 80 (1 - 53992/(10:ℝ)^8) 3 14825 + (T 80 (1 - 53992/(10:ℝ)^8) 4 16670 + (T 80 (1 - 53992/(10:ℝ)^8) 5 6310 + (T 80 (1 - 53992/(10:ℝ)^8) 6 3755 + (T 80 (1 - 53992/(10:ℝ)^8) 7 2170 + (T 80 (1 - 53992/(10:ℝ)^8) 8 1115 + (T 80 (1 - 53992/(10:ℝ)^8) 9 2125 + (T 80 (1 - 53992/(10:ℝ)^8) 10 6175 + (T 80 (1 - 53992/(10:ℝ)^8) 11 10055 + (T 80 (1 - 53992/(10:ℝ)^8) 12 2990 + (T 80 (1 - 53992/(10:ℝ)^8) 13 810 + (T 80 (1 - 53992/(10:ℝ)^8) 14 3450 + (T 80 (1 - 53992/(10:ℝ)^8) 15 1195 + (T 80 (1 - 53992/(10:ℝ)^8) 16 5 + (T 80 (1 - 53992/(10:ℝ)^8) 30 1120 + (T 80 (1 - 53992/(10:ℝ)^8) 34 1120 + 0))))))))))))))))) := rfl
  have b0 : T 80 (1 - 53992/(10:ℝ)^8) 1 51335 ≤ ((12864149889:ℝ)/20000000) :=
    term_le 80 1 51335 (53992/(10:ℝ)^8) ((175281065387:ℝ)/40000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 80 (1 - 53992/(10:ℝ)^8) 2 65685 ≤ ((41134971999:ℝ)/25000000) :=
    term_le 80 2 65685 (53992/(10:ℝ)^8) ((737775890823:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 80 (1 - 53992/(10:ℝ)^8) 3 14825 ≤ ((3480774561:ℝ)/6250000) :=
    term_le 80 3 14825 (53992/(10:ℝ)^8) ((3283414346007:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 80 (1 - 53992/(10:ℝ)^8) 4 16670 ≤ ((41742462023:ℝ)/50000000) :=
    term_le 80 4 16670 (53992/(10:ℝ)^8) ((599146454711:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 80 (1 - 53992/(10:ℝ)^8) 5 6310 ≤ ((39496581213:ℝ)/100000000) :=
    term_le 80 5 6310 (53992/(10:ℝ)^8) ((2772588722241:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 80 (1 - 53992/(10:ℝ)^8) 6 3755 ≤ ((28201913859:ℝ)/100000000) :=
    term_le 80 6 3755 (53992/(10:ℝ)^8) ((2590267165447:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 80 (1 - 53992/(10:ℝ)^8) 7 2170 ≤ ((9506245423:ℝ)/50000000) :=
    term_le 80 7 2170 (53992/(10:ℝ)^8) ((121805824281:ℝ)/50000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 80 (1 - 53992/(10:ℝ)^8) 8 1115 ≤ ((11163870433:ℝ)/100000000) :=
    term_le 80 8 1115 (53992/(10:ℝ)^8) ((575646273249:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 80 (1 - 53992/(10:ℝ)^8) 9 2125 ≤ ((23934466893:ℝ)/100000000) :=
    term_le 80 9 2125 (53992/(10:ℝ)^8) ((2184802057339:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 80 (1 - 53992/(10:ℝ)^8) 10 6175 ≤ ((15454841911:ℝ)/20000000) :=
    term_le 80 10 6175 (53992/(10:ℝ)^8) ((2079441541681:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 80 (1 - 53992/(10:ℝ)^8) 11 10055 ≤ ((138404439449:ℝ)/100000000) :=
    term_le 80 11 10055 (53992/(10:ℝ)^8) ((1984131361877:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 80 (1 - 53992/(10:ℝ)^8) 12 2990 ≤ ((44895963081:ℝ)/100000000) :=
    term_le 80 12 2990 (53992/(10:ℝ)^8) ((1897119984887:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 80 (1 - 53992/(10:ℝ)^8) 13 810 ≤ ((2635083951:ℝ)/20000000) :=
    term_le 80 13 810 (53992/(10:ℝ)^8) ((908538638607:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b13 : T 80 (1 - 53992/(10:ℝ)^8) 14 3450 ≤ ((15107960871:ℝ)/25000000) :=
    term_le 80 14 3450 (53992/(10:ℝ)^8) ((87148465253:ℝ)/50000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b14 : T 80 (1 - 53992/(10:ℝ)^8) 15 1195 ≤ ((1401656889:ℝ)/6250000) :=
    term_le 80 15 1195 (53992/(10:ℝ)^8) ((1673976433573:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b15 : T 80 (1 - 53992/(10:ℝ)^8) 16 5 ≤ ((20017387:ℝ)/20000000) :=
    term_le 80 16 5 (53992/(10:ℝ)^8) ((402359478109:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b16 : T 80 (1 - 53992/(10:ℝ)^8) 30 1120 ≤ ((42022247803:ℝ)/100000000) :=
    term_le 80 30 1120 (53992/(10:ℝ)^8) ((980829253013:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b17 : T 80 (1 - 53992/(10:ℝ)^8) 34 1120 ≤ ((9524399173:ℝ)/20000000) :=
    term_le 80 34 1120 (53992/(10:ℝ)^8) ((855666110059:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b18 : T 80 (1 - 53992/(10:ℝ)^8) 79 1 ≤ ((98750671:ℝ)/100000000) :=
    term_le 80 79 1 (53992/(10:ℝ)^8) ((12283967:ℝ)/976562500) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 6 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b19 : T 80 (1 - 53992/(10:ℝ)^8) 1 1 ≤ ((1252961:ℝ)/100000000) :=
    term_le 80 1 1 (53992/(10:ℝ)^8) ((175281065387:ℝ)/40000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^13 - 1) = 8191 := by norm_num
  have e2 : (2:ℝ)^13 = 8192 := by norm_num
  have e3 : ((9362:ℕ):ℝ) = 9362 := by norm_num
  have e4 : T 80 (1 - 53992/(10:ℝ)^8) (80 - 1) 1 = T 80 (1 - 53992/(10:ℝ)^8) 79 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 53993/10^8` the moment of one unit is at least its number of live roles `9362`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 1.88e-08. -/
theorem fold_B2Ke16_sharp : ((9362:ℕ):ℝ) ≤ moment 80 (1 - 53993/(10:ℝ)^8) blocksB2Ke16 := by
  have hsum : moment 80 (1 - 53993/(10:ℝ)^8) blocksB2Ke16
      = T 80 (1 - 53993/(10:ℝ)^8) 1 51335 + (T 80 (1 - 53993/(10:ℝ)^8) 2 65685 + (T 80 (1 - 53993/(10:ℝ)^8) 3 14825 + (T 80 (1 - 53993/(10:ℝ)^8) 4 16670 + (T 80 (1 - 53993/(10:ℝ)^8) 5 6310 + (T 80 (1 - 53993/(10:ℝ)^8) 6 3755 + (T 80 (1 - 53993/(10:ℝ)^8) 7 2170 + (T 80 (1 - 53993/(10:ℝ)^8) 8 1115 + (T 80 (1 - 53993/(10:ℝ)^8) 9 2125 + (T 80 (1 - 53993/(10:ℝ)^8) 10 6175 + (T 80 (1 - 53993/(10:ℝ)^8) 11 10055 + (T 80 (1 - 53993/(10:ℝ)^8) 12 2990 + (T 80 (1 - 53993/(10:ℝ)^8) 13 810 + (T 80 (1 - 53993/(10:ℝ)^8) 14 3450 + (T 80 (1 - 53993/(10:ℝ)^8) 15 1195 + (T 80 (1 - 53993/(10:ℝ)^8) 16 5 + (T 80 (1 - 53993/(10:ℝ)^8) 30 1120 + (T 80 (1 - 53993/(10:ℝ)^8) 34 1120 + 0))))))))))))))))) := rfl
  have c0 : ((6432075221:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 1 51335 :=
    term_ge 80 1 51335 (53993/(10:ℝ)^8) ((273876664667:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((16453989399:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 2 65685 :=
    term_ge 80 2 65685 (53993/(10:ℝ)^8) ((115277482941:ℝ)/31250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((2784619739:ℝ)/5000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 3 14825 :=
    term_ge 80 3 14825 (53993/(10:ℝ)^8) ((820853586501:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((2087123163:ℝ)/2500000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 4 16670 :=
    term_ge 80 4 16670 (53993/(10:ℝ)^8) ((187233267097:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((394965823:ℝ)/1000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 5 6310 :=
    term_ge 80 5 6310 (53993/(10:ℝ)^8) ((1386294361119:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((1410095729:ℝ)/5000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 6 3755 :=
    term_ge 80 6 3755 (53993/(10:ℝ)^8) ((647566791361:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((190124913:ℝ)/1000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 7 2170 :=
    term_ge 80 7 2170 (53993/(10:ℝ)^8) ((2436116485617:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((279096767:ℝ)/2500000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 8 1115 :=
    term_ge 80 8 1115 (53993/(10:ℝ)^8) ((2302585092993:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((2393446741:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 9 2125 :=
    term_ge 80 9 2125 (53993/(10:ℝ)^8) ((273100257167:ℝ)/125000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((1545484223:ℝ)/2000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 10 6175 :=
    term_ge 80 10 6175 (53993/(10:ℝ)^8) ((1039720770839:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((6920222109:ℝ)/5000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 11 10055 :=
    term_ge 80 11 10055 (53993/(10:ℝ)^8) ((992065680937:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c11 : ((561199549:ℝ)/1250000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 12 2990 :=
    term_ge 80 12 2990 (53993/(10:ℝ)^8) ((474279996221:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c12 : ((1317541999:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 13 810 :=
    term_ge 80 13 810 (53993/(10:ℝ)^8) ((1817077277211:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c13 : ((6043184453:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 14 3450 :=
    term_ge 80 14 3450 (53993/(10:ℝ)^8) ((1742969305057:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c14 : ((2242651059:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 15 1195 :=
    term_ge 80 15 1195 (53993/(10:ℝ)^8) ((167397643357:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c15 : ((10008693:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 16 5 :=
    term_ge 80 16 5 (53993/(10:ℝ)^8) ((1609437912433:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c16 : ((4202224821:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 30 1120 :=
    term_ge 80 30 1120 (53993/(10:ℝ)^8) ((98082925301:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c17 : ((4762199627:ℝ)/10000000) ≤ T 80 (1 - 53993/(10:ℝ)^8) 34 1120 :=
    term_ge 80 34 1120 (53993/(10:ℝ)^8) ((106958263757:ℝ)/125000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((9362:ℕ):ℝ) = 9362 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 31553/10^8`, fill parameter `s = 13`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 80, W = 9362, D = 1035).  Relative slack: 3.03e-05. -/
theorem foldRank_B2Ke16 :
    (2:ℝ)^13 * ((9362:ℕ):ℝ) * (((80:ℕ):ℝ) - ((80:ℕ):ℝ)^(1 - 31553/(10:ℝ)^8)) < ((2:ℝ)^13 - 1) * ((1035:ℕ):ℝ) :=
  FoldRate.rank_fact3 80 9362 1035 13 (31553/(10:ℝ)^8) ((175281065387:ℝ)/40000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 31558/10^8` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Ke16_sharp :
    ((1035:ℕ):ℝ) ≤ ((9362:ℕ):ℝ) * (((80:ℕ):ℝ) - ((80:ℕ):ℝ)^(1 - 31558/(10:ℝ)^8)) :=
  FoldRate.rank_fact_sharp 80 9362 1035 (31558/(10:ℝ)^8) ((273876664667:ℝ)/62500000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ke16
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ke16_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ke16
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ke16_sharp
