import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: carrier-check) Rate lemmas for one unit of the bridged word B_2 with the carrier certificate `Cr2h16`

GENERATED by checks/wht12/carrier-check/py/crate.py with the text generators of
checks/wht9/bridge-rate/py (used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = 9362` live roles, label dimension `m = 80`, deficit `D = 1035`.

* `blocksB2Ke16x`            the block list (rank, count) of ONE unit;
* `fold_B2Ke16x`             whole-block fact at `1 - 5399225/10^10`, fill parameter `s = 40` (slack 1.67e-10);
* `fold_B2Ke16x_sharp`       `W ≤ moment` at `1 - 5399227/10^10`: fails for every table (excess 1.36e-10);
* `foldRank_B2Ke16x`         per-rank fact at `1 - 3155781/10^10`, `s = 40` (slack 8.94e-08);
* `foldRank_B2Ke16x_sharp`   per-rank: fails for every table at `1 - 3155783/10^10`.

That a Lean word has `G` times this list as its block histogram is NOT proved here (see `Work.CarrierCheck.B2Ke16`).
-/

set_option maxRecDepth 4000

namespace OAI.PowerSaving.BlockAccounting
open Finset

/-- Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the CARRIER helper circuit `Cr2h16` (h = 16, m = 80): five invocations (ALL blocks of one invocation: x roles, y roles, helper slots, scratch copies; the kernel-counted ranks of `CarrierCr2h16.inv_cost`), and for each of the v = 560 classes the idle climbs of its two twins (2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = 7122 helper slots shared by the five stages. -/
def blocksB2Ke16x : List (ℕ × ℕ) := [(1, 51335), (2, 65685), (3, 14825), (4, 16670), (5, 6310), (6, 3755), (7, 2170), (8, 1115), (9, 2125), (10, 6175), (11, 10055), (12, 2990), (13, 810), (14, 3450), (15, 1195), (16, 5), (30, 1120), (34, 1120)]

/-- total rank of one unit (= number of unit moves it stands for): `W * m - D` -/
theorem blocksB2Ke16x_rank : (blocksB2Ke16x.map fun b => b.1 * b.2).sum = 9362 * 80 - 1035 := by
  norm_num [blocksB2Ke16x]

/-- the same as a price: the unit list at the price list `r ↦ r` (shape of `hPid` in `RAM.engine_program_group_perRank`) -/
theorem blocksB2Ke16x_tally : (blocksB2Ke16x.map fun b => (b.2:ℝ) * ((b.1:ℕ):ℝ)).sum = ((9362:ℕ):ℝ) * ((80:ℕ):ℝ) - ((1035:ℕ):ℝ) := by
  norm_num [blocksB2Ke16x]

theorem blocksB2Ke16x_count : (blocksB2Ke16x.map fun b => b.2).sum = 190910 := by
  norm_num [blocksB2Ke16x]

theorem blocksB2Ke16x_proper : ∀ b ∈ blocksB2Ke16x, 1 ≤ b.1 ∧ b.1 < 80 := by
  decide

/-- **whole-block fact** of `blocksB2Ke16x` at exponent `1 - 5399225/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_list` (u = 80, W = 9362).  Relative slack of the rational certificate: 1.67e-10. -/
theorem fold_B2Ke16x :
    ((2:ℝ)^40 - 1) * moment 80 (1 - 5399225/(10:ℝ)^10) blocksB2Ke16x
      + ((9362:ℕ):ℝ) * (T 80 (1 - 5399225/(10:ℝ)^10) (80 - 1) 1 + T 80 (1 - 5399225/(10:ℝ)^10) 1 1)
      < (2:ℝ)^40 * ((9362:ℕ):ℝ) := by
  have hsum : moment 80 (1 - 5399225/(10:ℝ)^10) blocksB2Ke16x
      = T 80 (1 - 5399225/(10:ℝ)^10) 1 51335 + (T 80 (1 - 5399225/(10:ℝ)^10) 2 65685 + (T 80 (1 - 5399225/(10:ℝ)^10) 3 14825 + (T 80 (1 - 5399225/(10:ℝ)^10) 4 16670 + (T 80 (1 - 5399225/(10:ℝ)^10) 5 6310 + (T 80 (1 - 5399225/(10:ℝ)^10) 6 3755 + (T 80 (1 - 5399225/(10:ℝ)^10) 7 2170 + (T 80 (1 - 5399225/(10:ℝ)^10) 8 1115 + (T 80 (1 - 5399225/(10:ℝ)^10) 9 2125 + (T 80 (1 - 5399225/(10:ℝ)^10) 10 6175 + (T 80 (1 - 5399225/(10:ℝ)^10) 11 10055 + (T 80 (1 - 5399225/(10:ℝ)^10) 12 2990 + (T 80 (1 - 5399225/(10:ℝ)^10) 13 810 + (T 80 (1 - 5399225/(10:ℝ)^10) 14 3450 + (T 80 (1 - 5399225/(10:ℝ)^10) 15 1195 + (T 80 (1 - 5399225/(10:ℝ)^10) 16 5 + (T 80 (1 - 5399225/(10:ℝ)^10) 30 1120 + (T 80 (1 - 5399225/(10:ℝ)^10) 34 1120 + 0))))))))))))))))) := rfl
  have b0 : T 80 (1 - 5399225/(10:ℝ)^10) 1 51335 ≤ ((128641500299:ℝ)/200000000) :=
    term_le 80 1 51335 (5399225/(10:ℝ)^10) ((175281065387:ℝ)/40000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b1 : T 80 (1 - 5399225/(10:ℝ)^10) 2 65685 ≤ ((164539889513:ℝ)/100000000) :=
    term_le 80 2 65685 (5399225/(10:ℝ)^10) ((737775890823:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 25 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b2 : T 80 (1 - 5399225/(10:ℝ)^10) 3 14825 ≤ ((278461967163:ℝ)/500000000) :=
    term_le 80 3 14825 (5399225/(10:ℝ)^10) ((3283414346007:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 24 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b3 : T 80 (1 - 5399225/(10:ℝ)^10) 4 16670 ≤ ((417424623353:ℝ)/500000000) :=
    term_le 80 4 16670 (5399225/(10:ℝ)^10) ((599146454711:ℝ)/200000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 23 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b4 : T 80 (1 - 5399225/(10:ℝ)^10) 5 6310 ≤ ((98741453717:ℝ)/250000000) :=
    term_le 80 5 6310 (5399225/(10:ℝ)^10) ((2772588722241:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 22 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b5 : T 80 (1 - 5399225/(10:ℝ)^10) 6 3755 ≤ ((28201914041:ℝ)/100000000) :=
    term_le 80 6 3755 (5399225/(10:ℝ)^10) ((2590267165447:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b6 : T 80 (1 - 5399225/(10:ℝ)^10) 7 2170 ≤ ((190124909609:ℝ)/1000000000) :=
    term_le 80 7 2170 (5399225/(10:ℝ)^10) ((121805824281:ℝ)/50000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 21 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b7 : T 80 (1 - 5399225/(10:ℝ)^10) 8 1115 ≤ ((55819352483:ℝ)/500000000) :=
    term_le 80 8 1115 (5399225/(10:ℝ)^10) ((575646273249:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b8 : T 80 (1 - 5399225/(10:ℝ)^10) 9 2125 ≤ ((239344670229:ℝ)/1000000000) :=
    term_le 80 9 2125 (5399225/(10:ℝ)^10) ((2184802057339:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b9 : T 80 (1 - 5399225/(10:ℝ)^10) 10 6175 ≤ ((772742099567:ℝ)/1000000000) :=
    term_le 80 10 6175 (5399225/(10:ℝ)^10) ((2079441541681:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 20 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b10 : T 80 (1 - 5399225/(10:ℝ)^10) 11 10055 ≤ ((173005550169:ℝ)/125000000) :=
    term_le 80 11 10055 (5399225/(10:ℝ)^10) ((1984131361877:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b11 : T 80 (1 - 5399225/(10:ℝ)^10) 12 2990 ≤ ((89791926587:ℝ)/200000000) :=
    term_le 80 12 2990 (5399225/(10:ℝ)^10) ((1897119984887:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 19 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b12 : T 80 (1 - 5399225/(10:ℝ)^10) 13 810 ≤ ((32938549537:ℝ)/250000000) :=
    term_le 80 13 810 (5399225/(10:ℝ)^10) ((908538638607:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b13 : T 80 (1 - 5399225/(10:ℝ)^10) 14 3450 ≤ ((604318437469:ℝ)/1000000000) :=
    term_le 80 14 3450 (5399225/(10:ℝ)^10) ((87148465253:ℝ)/50000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b14 : T 80 (1 - 5399225/(10:ℝ)^10) 15 1195 ≤ ((56066275793:ℝ)/250000000) :=
    term_le 80 15 1195 (5399225/(10:ℝ)^10) ((1673976433573:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b15 : T 80 (1 - 5399225/(10:ℝ)^10) 16 5 ≤ ((20017387:ℝ)/20000000) :=
    term_le 80 16 5 (5399225/(10:ℝ)^10) ((402359478109:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 18 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b16 : T 80 (1 - 5399225/(10:ℝ)^10) 30 1120 ≤ ((420222479057:ℝ)/1000000000) :=
    term_le 80 30 1120 (5399225/(10:ℝ)^10) ((980829253013:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 15 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b17 : T 80 (1 - 5399225/(10:ℝ)^10) 34 1120 ≤ ((476219959661:ℝ)/1000000000) :=
    term_le 80 34 1120 (5399225/(10:ℝ)^10) ((855666110059:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 14 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b18 : T 80 (1 - 5399225/(10:ℝ)^10) 79 1 ≤ ((987506707:ℝ)/1000000000) :=
    term_le 80 79 1 (5399225/(10:ℝ)^10) ((12283967:ℝ)/976562500) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 6 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have b19 : T 80 (1 - 5399225/(10:ℝ)^10) 1 1 ≤ ((1252961:ℝ)/100000000) :=
    term_le 80 1 1 (5399225/(10:ℝ)^10) ((175281065387:ℝ)/40000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num) (by norm_num)
  have e1 : ((2:ℝ)^40 - 1) = 1099511627775 := by norm_num
  have e2 : (2:ℝ)^40 = 1099511627776 := by norm_num
  have e3 : ((9362:ℕ):ℝ) = 9362 := by norm_num
  have e4 : T 80 (1 - 5399225/(10:ℝ)^10) (80 - 1) 1 = T 80 (1 - 5399225/(10:ℝ)^10) 79 1 := rfl
  rw [e1, e2, e3, e4, hsum]
  linarith

/-- **sharpness**: at exponent `1 - 5399227/10^10` the moment of one unit is at least its number of live roles `9362`, so the moment criterion fails for EVERY table made of copies of the unit and idle roles (`FoldRate.block_fails`).  Relative excess of the rational certificate: 1.36e-10. -/
theorem fold_B2Ke16x_sharp : ((9362:ℕ):ℝ) ≤ moment 80 (1 - 5399227/(10:ℝ)^10) blocksB2Ke16x := by
  have hsum : moment 80 (1 - 5399227/(10:ℝ)^10) blocksB2Ke16x
      = T 80 (1 - 5399227/(10:ℝ)^10) 1 51335 + (T 80 (1 - 5399227/(10:ℝ)^10) 2 65685 + (T 80 (1 - 5399227/(10:ℝ)^10) 3 14825 + (T 80 (1 - 5399227/(10:ℝ)^10) 4 16670 + (T 80 (1 - 5399227/(10:ℝ)^10) 5 6310 + (T 80 (1 - 5399227/(10:ℝ)^10) 6 3755 + (T 80 (1 - 5399227/(10:ℝ)^10) 7 2170 + (T 80 (1 - 5399227/(10:ℝ)^10) 8 1115 + (T 80 (1 - 5399227/(10:ℝ)^10) 9 2125 + (T 80 (1 - 5399227/(10:ℝ)^10) 10 6175 + (T 80 (1 - 5399227/(10:ℝ)^10) 11 10055 + (T 80 (1 - 5399227/(10:ℝ)^10) 12 2990 + (T 80 (1 - 5399227/(10:ℝ)^10) 13 810 + (T 80 (1 - 5399227/(10:ℝ)^10) 14 3450 + (T 80 (1 - 5399227/(10:ℝ)^10) 15 1195 + (T 80 (1 - 5399227/(10:ℝ)^10) 16 5 + (T 80 (1 - 5399227/(10:ℝ)^10) 30 1120 + (T 80 (1 - 5399227/(10:ℝ)^10) 34 1120 + 0))))))))))))))))) := rfl
  have c0 : ((128641500317:ℝ)/200000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 1 51335 :=
    term_ge 80 1 51335 (5399227/(10:ℝ)^10) ((273876664667:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c1 : ((822699447811:ℝ)/500000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 2 65685 :=
    term_ge 80 2 65685 (5399227/(10:ℝ)^10) ((115277482941:ℝ)/31250000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c2 : ((278461967259:ℝ)/500000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 3 14825 :=
    term_ge 80 3 14825 (5399227/(10:ℝ)^10) ((820853586501:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c3 : ((83484924701:ℝ)/100000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 4 16670 :=
    term_ge 80 4 16670 (5399227/(10:ℝ)^10) ((187233267097:ℝ)/62500000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c4 : ((98741453753:ℝ)/250000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 5 6310 :=
    term_ge 80 5 6310 (5399227/(10:ℝ)^10) ((1386294361119:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c5 : ((8813098141:ℝ)/31250000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 6 3755 :=
    term_ge 80 6 3755 (5399227/(10:ℝ)^10) ((647566791361:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c6 : ((47531227419:ℝ)/250000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 7 2170 :=
    term_ge 80 7 2170 (5399227/(10:ℝ)^10) ((2436116485617:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c7 : ((27909676251:ℝ)/250000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 8 1115 :=
    term_ge 80 8 1115 (5399227/(10:ℝ)^10) ((2302585092993:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c8 : ((239344670311:ℝ)/1000000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 9 2125 :=
    term_ge 80 9 2125 (5399227/(10:ℝ)^10) ((273100257167:ℝ)/125000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c9 : ((772742099827:ℝ)/1000000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 10 6175 :=
    term_ge 80 10 6175 (5399227/(10:ℝ)^10) ((1039720770839:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 3 10 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c10 : ((692022200903:ℝ)/500000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 11 10055 :=
    term_ge 80 11 10055 (5399227/(10:ℝ)^10) ((992065680937:ℝ)/500000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c11 : ((224479816539:ℝ)/500000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 12 2990 :=
    term_ge 80 12 2990 (5399227/(10:ℝ)^10) ((474279996221:ℝ)/250000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c12 : ((32938549547:ℝ)/250000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 13 810 :=
    term_ge 80 13 810 (5399227/(10:ℝ)^10) ((1817077277211:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c13 : ((12086368753:ℝ)/20000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 14 3450 :=
    term_ge 80 14 3450 (5399227/(10:ℝ)^10) ((1742969305057:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c14 : ((224265103237:ℝ)/1000000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 15 1195 :=
    term_ge 80 15 1195 (5399227/(10:ℝ)^10) ((167397643357:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c15 : ((1000869349:ℝ)/1000000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 16 5 :=
    term_ge 80 16 5 (5399227/(10:ℝ)^10) ((1609437912433:ℝ)/1000000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 2 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c16 : ((84044495827:ℝ)/200000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 30 1120 :=
    term_ge 80 30 1120 (5399227/(10:ℝ)^10) ((98082925301:ℝ)/100000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have c17 : ((238109979869:ℝ)/500000000) ≤ T 80 (1 - 5399227/(10:ℝ)^10) 34 1120 :=
    term_ge 80 34 1120 (5399227/(10:ℝ)^10) ((106958263757:ℝ)/125000000000) _ (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (le_log_of_expbound _ _ 1 11 (by norm_num) (by norm_num) (by norm_num)
        (by norm_num [Finset.sum_range_succ, Nat.factorial]))
      (by norm_num)
  have e3 : ((9362:ℕ):ℝ) = 9362 := by norm_num
  rw [e3, hsum]
  linarith

/-- **per-rank fact** at exponent `1 - 3155781/10^10`, fill parameter `s = 40`: the hypothesis `hnum` of `RAM.engine_program_group_perRank` (u = 80, W = 9362, D = 1035).  Relative slack: 8.94e-08. -/
theorem foldRank_B2Ke16x :
    (2:ℝ)^40 * ((9362:ℕ):ℝ) * (((80:ℕ):ℝ) - ((80:ℕ):ℝ)^(1 - 3155781/(10:ℝ)^10)) < ((2:ℝ)^40 - 1) * ((1035:ℕ):ℝ) :=
  FoldRate.rank_fact3 80 9362 1035 40 (3155781/(10:ℝ)^10) ((175281065387:ℝ)/40000000000) (by norm_num) (by norm_num) (by norm_num)
    (log_le_of_le_expsum _ _ 27 (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

/-- **per-rank sharpness**: at exponent `1 - 3155783/10^10` the deficit of one unit is at most `W (m - m^z)`, so the per-rank inequality fails for EVERY table made of copies of the unit and idle roles (`FoldRate.rank_fails`). -/
theorem foldRank_B2Ke16x_sharp :
    ((1035:ℕ):ℝ) ≤ ((9362:ℕ):ℝ) * (((80:ℕ):ℝ) - ((80:ℕ):ℝ)^(1 - 3155783/(10:ℝ)^10)) :=
  FoldRate.rank_fact_sharp 80 9362 1035 (3155783/(10:ℝ)^10) ((273876664667:ℝ)/62500000000) (by norm_num) (by norm_num) (by norm_num)
    (le_log_of_expbound _ _ 4 10 (by norm_num) (by norm_num) (by norm_num)
      (by norm_num [Finset.sum_range_succ, Nat.factorial]))
    (by norm_num) (by norm_num)

end OAI.PowerSaving.BlockAccounting

#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ke16x
#print axioms OAI.PowerSaving.BlockAccounting.fold_B2Ke16x_sharp
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ke16x
#print axioms OAI.PowerSaving.BlockAccounting.foldRank_B2Ke16x_sharp
