"""gxbind.py: THE BINDING of the generator to the Lean terms of gx-scalar / gx-labels /
gx-chain.  Everything that names somebody else's definition is in this file (tables SCAL, LAB, CHAIN)."""
import os, re, subprocess
import gxpaths
ROOT = gxpaths.OUT
GSM = gxpaths.HERE + '/gsmirror.py'

# gx-scalar (gcert-interface.md, SCALAR v1): GS.scalCheck c p lo n, GS.yCheck c p lo n, p : GS.SPar = <d, sw, ux, us, uy>
SCAL = dict(imports=['Work.GCert.Scalar.Seg'], scal='GS.scalCheck raw ⟨%(d)d, %(sw)d, %(ux)d, %(us)d, %(uy)d⟩ %(lo)d %(n)d',
            ychk='GS.yCheck raw ⟨%(d)d, %(sw)d, %(ux)d, %(us)d, %(uy)d⟩ 0 %(v)d')
# gx-labels (gcert-interface.md LABELS v1 + questions.md N1): namespace GLab; frame = code, table and states = SSC.Trie,
# GLab.Par = <h, n, d, K, tab>.  `end` = GLab.endK of Labels/EndDef.lean (questions.md N2; no obaseK: Q1 closed).
LAB = dict(imports=['Work.GCert.Labels.Def'], end_imports=['Work.GCert.Labels.EndDef'], par='⟨%(h)d, %(n)d, %(d)d, %(K)d, tab⟩', ns='GLab',
           tab='GLab.tabK %(h)d %(sub)s', seg='GLab.segK par %(gs)s st%(i)d st%(j)d %(rs)s',
           end='GLab.endK par %(v)d ports (raw.ret.map Prod.fst) st0 st%(a)d st%(f)d', noadds='GLab.noAdds fins')
# gx-chain (CHAIN v1): GX.wht_of_halves; the terms below are PLACEHOLDERS until Labels/Main and Scalar/Main compile
CHAIN = dict(imports=['Work.GCert.Chain.End', 'Work.GCert.Labels.Main'], scal='(GS.ScalOK.scal GXD.%(c)s.scalOK)',
             lab='(GXD.%(c)s.valid.lab GXD.%(c)s.scalOK)', lab_cost='GXD.%(c)s.lab_cost')


def code(h, basis):
    """gx-labels' code of a reduced echelon basis: dim + 2^8 M + 2^(8+h) P (M = pivot mask, vector of pivot p at digit p)"""
    M = P = 0
    for b in basis:
        p = b.bit_length() - 1
        M |= 1 << p
        P |= b << (h * p)
    return len(basis) + (M << 8) + (P << (8 + h))


MOD = '''import %(imports)s
/-! Kernel check (%(doc)s) of the gcert/1 certificate `GXD.%(name)s.raw`.  Source: %(src)s.
Generated by checks/wht26/gx-data/py/gxgen.py (do not edit). -/
set_option maxRecDepth 100000
namespace GXD.%(name)s
open GXD
theorem %(thm)s : %(stmt)s := by decide +kernel
end GXD.%(name)s
#print axioms GXD.%(name)s.%(thm)s
'''


def spar(D, path):
    """scalar parameters: from gx-scalar's mirror when it exists, else from my own replay (sw is then a GUESS)"""
    import gxcore as gc
    n, d = 2 * D['v'] + D['R'], 0
    while (1 << d) < n:
        d += 1
    dg = gc.digits(D)
    S = dict(d=d, sw=16, ux=dg['x'][0], us=dg['s'][0], uy=dg['y'][0], source='gx-data replay; sw = 16 is a GUESS', digits=dg)
    if os.path.exists(GSM):
        try:
            o = subprocess.run(['python3', '-B', GSM, path], capture_output=True, text=True, timeout=1800).stdout
            m = re.search(r'SPar[^\d]*(\d+)[, ]+(\d+)[, ]+(\d+)[, ]+(\d+)[, ]+(\d+)', o)
            if m:
                S.update(zip(('d', 'sw', 'ux', 'us', 'uy'), map(int, m.groups())), source='gsmirror.py')
        except Exception as e:
            S['source'] += ' (gsmirror.py failed: %r)' % (e,)
    return S


def write_checks(D, M, name, src, out, L, S, plan):
    base = out[len(ROOT):].replace('/', '.')
    raw = '%s.Gen.%s' % (base, name)
    h, v, n = D['h'], D['v'], 2 * D['v'] + D['R']
    res = []

    def mod(suffix, imports, thm, stmt, doc):
        m = '%s.Gen.%s%s' % (base, name, suffix)
        open('%s/Gen/%s%s.lean' % (out, name, suffix), 'w').write(MOD % dict(
            imports='\nimport '.join(imports), doc=doc, name=name, src=src, thm=thm, stmt=stmt))
        res.append((m, thm, stmt))
    for i, (lo, hi) in enumerate(M['scal']['batches']):
        mod('Scal%d' % i, SCAL['imports'] + [raw], 'scal%d_ok' % i, SCAL['scal'] % dict(S, lo=lo, n=hi - lo) + ' = true',
            'scalar identity E3 E5 for the sources %d .. %d' % (lo, hi - 1))
    mod('YChk', SCAL['imports'] + [raw], 'ychk_ok', SCAL['ychk'] % dict(S, v=v) + ' = true', 'the y -> y adds, E4')
    par = '%s.Gen.%sPar' % (base, name)
    open('%s/Gen/%sPar.lean' % (out, name), 'w').write(
        'import %s\nimport %s\n/-! Parameters `GLab.Par` of the label check of `GXD.%s.raw` (h, registers, trie depth, K, frame table).\n'
        'Generated by checks/wht26/gx-data/py/gxgen.py (do not edit). -/\nnamespace GXD.%s\nopen GXD\n'
        'noncomputable def par : GLab.Par := %s\nend GXD.%s\n'
        % (LAB['imports'][0], raw, name, name, LAB['par'] % dict(h=h, n=n, d=L['d'], K=L['K']), name))
    paths = [format(i, '0%db' % L['ts']) for i in range(1 << L['ts'])] if L['ts'] else ['']
    for i, pth in enumerate(paths):
        mod('Tab%d' % i, LAB['imports'] + [raw], 'tab%d_ok' % i,
            LAB['tab'] % dict(h=h, sub='tab_n' + pth if pth else 'tab') + ' = true',
            'E0: subtrie %d of %d of the frame table (codes of reduced echelon bases)' % (i, len(paths)))
    for i in range(L['nseg']):
        mod('Seg%d' % i, [par], 'seg%d_ok' % i,
            LAB['seg'] % dict(gs='seg%d' % i, i=i, j=i + 1, rs='rs%d' % i) + ' = true',
            'E1: replay of the gates %d .. %d (phase %s) and their block ranks' % (
                M['cuts'][i], M['cuts'][i + 1] - 1, 'A' if i < L['nsegA'] else 'B'))
    mod('SegF', [par], 'segF_ok', LAB['seg'] % dict(gs='fins', i=L['nseg'], j=L['nseg'] + 1, rs='rF') + ' = true',
        'E1: the final climbs and their block ranks')
    if LAB['end']:
        mod('End', LAB['end_imports'] + [par], 'end_ok', LAB['end'] % dict(v=v, a=L['nsegA'], f=L['nseg'] + 1) + ' = true',
            'E1 E2: frames at the start, at the scatter, at the end')
    return res


def nest(xs):
    return ' ++ ('.join(xs) + ')' * (len(xs) - 1) if xs else '[]'


def write_hist(D, M, name, src, out, L):
    """kernel counts of the block ranks on the EXPLICIT rank lists rA, rB, rF (no replay)"""
    base = out[len(ROOT):].replace('/', '.')
    h, rs = D['h'], M['lab']['rs']
    ph = {'A': sum(rs[:L['nsegA']], []), 'B': sum(rs[L['nsegA']:], []), 'F': M['lab']['rF']}
    top = max(max(x) if x else 0 for x in ph.values())
    cop = [M['dim'][f] for _, f in D['ret']]
    tot = {r: sum(x.count(r) for x in ph.values()) + cop.count(r) for r in range(1, max(top, max(cop)) + 1)}
    assert {r: c for r, c in tot.items() if c} == M['hist'], 'histogram of the rank lists differs from the mirror'
    lines = ['/-- block ranks of phase A / phase B, in order (the lists of the replay segments) -/',
             'noncomputable def rA : List Nat := ' + nest(['rs%d' % i for i in range(L['nsegA'])]),
             'noncomputable def rB : List Nat := ' + nest(['rs%d' % i for i in range(L['nsegA'], L['nseg'])])]
    names = []
    for X, lst in sorted(ph.items()):
        l = 'r' + X
        lines.append('theorem rankBound%s : wsumK (SSC.wGt %d) %s 0 = 0 := by decide +kernel' % (X, top, l))
        lines += ['theorem rank%s%d_ok : wsumK (SSC.wEq %d) %s 0 = %d := by decide +kernel' % (X, r, r, l, lst.count(r))
                  for r in range(top + 1)]
        names += ['rankBound' + X] + ['rank%s%d_ok' % (X, r) for r in range(top + 1)]
    txt = ('import Work.GCert.Data.Count\nimport %s.Gen.%s\n' % (base, name) +
           '/-! Kernel count of the BLOCK RANKS of the gcert/1 certificate `GXD.%s.raw` (h = %d) on the explicit rank lists\n'
           '`rA`, `rB`, `rF` (phase A, phase B, final climbs): `wsumK (SSC.wEq r) l 0` blocks of rank `r`, none above %d\n'
           '(`GXD.sum_of_wsumK` turns a count into `(l.map wt).sum` = `SSC.wsum wt l`).\n'
           'The %d scratch copies (ranks %s) are not in these lists.  Whole invocation, by rank: %s.\n'
           'Source: %s.  Generated by checks/wht26/gx-data/py/gxgen.py (do not edit). -/\n'
           'set_option maxRecDepth 100000\nnamespace GXD.%s\nopen GXD\n' % (
               name, h, top, len(cop), sorted(set(cop)), M['hist'], src, name) + '\n'.join(lines) +
           '\nend GXD.%s\n' % name + '\n'.join('#print axioms GXD.%s.%s' % (name, x) for x in names[:2]) + '\n')
    open('%s/Gen/%sHist.lean' % (out, name), 'w').write(txt)
    return '%s.Gen.%sHist' % (base, name)


def write_price(D, M, name, src, out, L):
    """Mathlib module: the price of the rank lists rA, rB, rF from the kernel counts, and of one whole invocation"""
    base = out[len(ROOT):].replace('/', '.')
    rs = M['lab']['rs']
    ph = {'A': sum(rs[:L['nsegA']], []), 'B': sum(rs[L['nsegA']:], []), 'F': M['lab']['rF']}
    top = max(max(x) if x else 0 for x in ph.values())
    cop = [M['dim'][f] for _, f in D['ret']]
    tm = lambda cnt: ' + '.join('%d * φ %d' % (n, r) for r, n in sorted(cnt.items()) if n) or '0'
    thms = ''
    for X in 'ABF':
        cnt = {r: ph[X].count(r) for r in range(1, top + 1)}
        thms += '''
/-- price of the blocks of %s, from the kernel counts -/
theorem r%s_cost (φ : ℕ → ℝ) : rcost φ r%s = %s := by
  rw [GXD.rcost_wsumK φ r%s %d rankBound%s]
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, %s]
  norm_num [bcost]
''' % ({'A': 'phase A', 'B': 'phase B', 'F': 'the final climbs'}[X], X, X, tm(cnt), X, top, X,
       ', '.join('rank%s%d_ok' % (X, r) for r in range(top + 1)))
    copies = tm({r: cop.count(r) for r in set(cop)})
    txt = '''import Work.GCert.Data.Price
import %(base)s.Gen.%(name)sHist

/-!
# (key: gx-data) gcert/1 certificate `%(name)s` (h = %(h)d): the price of one invocation

GENERATED by checks/wht26/gx-data/py/gxgen.py from %(src)s.  No `sorry`.
`rA_cost`, `rB_cost`, `rF_cost`: the price of the block rank lists of phase A, phase B and the final climbs
(lists `GXD.%(name)s.rA / rB / rF`, counted by the kernel in `Gen.%(name)sHist`);
`inv_cost`: with the %(nc)d scratch copies (%(copies)s) the blocks of ONE invocation cost
`invPrice φ` = %(terms)s;  `inv_moves`: they stand for `R h + 2 v (h - 1) + cst = %(N)d` unit moves.
-/

namespace GXD.%(name)s
open GXD OAI.PowerSaving.CB
%(thms)s
/-- price of the blocks of ONE invocation (x roles, y roles, slots, scratch copies), by rank -/
def invPrice (φ : ℕ → ℝ) : ℝ := %(terms)s

/-- **Price of ONE invocation** in the shape of `GX.Lab.cost`: phase A, the scratch copies, phase B, final climbs. -/
theorem inv_cost (φ : ℕ → ℝ) : rcost φ rA + (%(copies)s) + rcost φ rB + rcost φ rF = invPrice φ := by
  rw [rA_cost, rB_cost, rF_cost]
  unfold invPrice
  ring

theorem inv_moves : invPrice (fun r => (r:ℝ)) = %(R)d * %(h)d + 2 * %(v)d * (%(h)d - 1) + %(cst)d := by
  unfold invPrice
  norm_num

theorem inv_count : invPrice (fun _ => (1:ℝ)) = %(count)d := by
  unfold invPrice
  norm_num

end GXD.%(name)s
#print axioms GXD.%(name)s.inv_cost
#print axioms GXD.%(name)s.inv_moves
''' % dict(base=base, name=name, h=D['h'], src=src, nc=len(cop), copies=copies, terms=tm(M['hist']), N=D['N'], thms=thms,
           R=D['R'], v=D['v'], cst=D['cst'], count=sum(M['hist'].values()))
    open('%s/%sPrice.lean' % (out, name), 'w').write(txt)
    return '%s.%sPrice' % (base, name)


def write_cert(D, M, name, src, out, chk, L):
    """<Name>Cert: THE LABEL HALF (aux, valid : GLab.Valid raw aux, lab_cost, lab_price) -- compiles without the scalar half;
    <Name>ScalOK: the scalar half `scalOK : GS.ScalOK raw` (needs Work/GCert/Scalar/Main)."""
    base = out[len(ROOT):].replace('/', '.')
    bs = M['scal']['batches']
    hs = ''
    for i, (lo, hi) in enumerate(bs):
        lo_pf = 'Nat.zero_le t' if i == 0 else 'Nat.le_of_not_lt h%d' % (i - 1)
        if i + 1 < len(bs):
            hs += '    if h%d : t < %d then ⟨%d, %d, %s, h%d, GS.XRun.of_check scal%d_ok⟩ else\n' % (i, hi, lo, hi - lo, lo_pf, i, i)
        else:
            hs += '    ⟨%d, %d, %s, Nat.lt_of_lt_of_le ht (by decide), GS.XRun.of_check scal%d_ok⟩' % (lo, hi - lo, lo_pf, i)
    terms = ' + '.join('%d * φ %d' % (n, r) for r, n in M['hist'].items())
    info = dict(base=base, name=name, h=D['h'], src=src, v=D['v'], R=D['R'], nc=len(D['ret']), cst=D['cst'], N=D['N'],
                nb=len(bs), terms=terms, hs=hs)
    txt = '''import Work.GCert.Scalar.Main
import %(imps)s
/-! # (key: gx-data) gcert/1 certificate `%(name)s` (h = %(h)d): THE SCALAR HALF `scalOK : GS.ScalOK raw`
GENERATED by checks/wht26/gx-data/py/gxgen.py from %(src)s.  No `sorry`.
Kernel checks `scal<i>_ok` (%(nb)d source batches) and `ychk_ok`. -/
namespace GXD.%(name)s
open GXD
theorem scalOK : GS.ScalOK raw where
  hv := by decide
  hs := fun t ht =>
%(hs)s
  hyc := fun t ht => ⟨0, %(v)d, Nat.zero_le t, Nat.lt_of_lt_of_le ht (by decide), GS.YRun.of_check ychk_ok⟩
end GXD.%(name)s
#print axioms GXD.%(name)s.scalOK
''' % dict(info, imps='\nimport '.join(c[0] for c in chk if 'Scal' in c[0] or 'YChk' in c[0]))
    open('%s/%sScalOK.lean' % (out, name), 'w').write(txt)
    # ---- the label half
    nA, ns, ts = L['nsegA'], L['nseg'], L['ts']
    cop = sorted(set(M['dim'][f] for _, f in D['ret']))
    assert len(cop) == 1, 'scratch copies of several ranks %s: lab_cost of gxbind.py assumes one' % cop

    def tabpf(path):
        if len(path) == ts:
            return 'tab%d_ok' % (int(path, 2) if path else 0)
        return '(GLab.tabK_node _ _ _ %s %s)' % (tabpf(path + '0'), tabpf(path + '1'))

    def runpf(a, b):
        return 'GLab.Run.of_seg seg%d_ok' % a if a + 1 == b else 'GLab.Run.append (GLab.Run.of_seg seg%d_ok) (%s)' % (a, runpf(a + 1, b))

    def run(X, a, b):
        segs = ['seg%d' % i for i in range(a, b)]
        return '''theorem gates%(X)s_eq : raw.gates%(X)s = %(cat)s := by
  show List.flatten %(lst)s = _
  simp only [List.flatten_cons, List.flatten_nil, List.append_nil]
/-- the replay of phase %(X)s, composed from its kernel-checked segments -/
theorem run%(X)s : GLab.Run par st%(a)d raw.gates%(X)s st%(b)d r%(X)s := by
  rw [gates%(X)s_eq]
  exact %(pf)s
''' % dict(X=X, cat=nest(segs), lst=ll_(segs), a=a, b=b, pf=runpf(a, b))
    lab = 'valid.lab S Ro cf hMA hMAi hMB hMBi reg hCc hreg'
    txt = '''import Work.GCert.Labels.Main
import %(base)s.%(name)sPrice
import %(imps)s
/-! # (key: gx-data) gcert/1 certificate `%(name)s` (h = %(h)d): THE LABEL HALF and its price
GENERATED by checks/wht26/gx-data/py/gxgen.py from %(src)s.  No `sorry`.
`v = %(v)d` ports, `R = %(R)d` slots, %(nc)d scratch copies of rank %(c)d, copy cost `cst = %(cst)d`, `N = %(N)d` unit moves.
* `aux : GLab.Aux`, `valid : GLab.Valid raw aux`: frame table (`tab<i>_ok` composed by `tabK_node`), the replays of phase A
  and phase B (`seg<i>_ok` composed by `Run.append`), the final climbs (`segF_ok`, `fin_ok`), the ends (`end_ok`);
* `lab_cost`, `lab_price`: for ANY scalar half `S` the label half `valid.lab S ..` costs
  `rcost rA + card C * bcost %(c)d + rcost rB + rcost rF` = `invPrice φ` = %(terms)s
  (`Gen.%(name)sHist`, `%(name)sPrice`) when there are %(nc)d copies. -/
set_option maxRecDepth 100000
namespace GXD.%(name)s
open GXD OAI.PowerSaving OAI.PowerSaving.CB
theorem raw_h : raw.h = %(h)d := rfl
theorem raw_v : raw.v = %(v)d := rfl
theorem raw_R : raw.R = %(R)d := rfl
/-- what the label checks read next to `raw` -/
noncomputable def aux : GLab.Aux := ⟨par, st0, st%(a)d, st%(n)d, st%(f)d, fins, rA, rB, rF⟩
theorem fin_ok : GLab.noAdds fins = true := by decide +kernel
theorem cen_ok : (raw.ret.map Prod.fst).all (fun r => Nat.beq (GLab.cdim (par.tab.get (st%(a)d.get r))) %(c)d) = true := by
  decide +kernel
theorem tab_ok : GLab.tabK par.h par.tab = true := %(tabpf)s
%(runA)s%(runB)s/-- **the kernel-checked label facts** of the certificate -/
theorem valid : GLab.Valid raw aux where
  hn := rfl
  tab := tab_ok
  runA := runA
  runB := runB
  runF := GLab.Run.of_seg segF_ok
  fin := fin_ok
  ends := end_ok
theorem cen_dim (r : Nat) (hr : r ∈ raw.ret.map Prod.fst) : GLab.cdim (par.tab.get (st%(a)d.get r)) = %(c)d :=
  Nat.eq_of_beq_eq_true (List.all_eq_true.mp cen_ok r hr)
/-- price of the label half over ANY scalar half -/
theorem lab_cost {C : Type} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin raw.v) (Fin raw.R) C)
    {emb : CR.L3 (Fin raw.v) (Fin raw.R) → Nat} {un : Nat → CR.L3 (Fin raw.v) (Fin raw.R)}
    (Ro : GLab.Roles raw.v raw.R emb un) (cf : Co → SSC.Coef) (hMA) (hMAi) (hMB) (hMBi)
    (reg : C → Nat) (hCc) (hreg) (φ : ℕ → ℝ) :
    (%(lab)s).cost φ
      = rcost φ rA + (Fintype.card C : ℝ) * bcost φ %(c)d + rcost φ rB + rcost φ rF := by
  obtain ⟨h1, h2, h3, h4⟩ := valid.lab_ranks S Ro cf hMA hMAi hMB hMBi reg hCc hreg
  have h5 : ∀ k, bcost φ (((%(lab)s).cen k).dim) = bcost φ %(c)d :=
    fun k => by rw [h4 k]; exact congrArg (bcost φ) (cen_dim _ (hreg k))
  rw [GX.Lab.cost, h1, h2, h3, Finset.sum_congr rfl (fun k _ => h5 k), Finset.sum_const, Finset.card_univ, nsmul_eq_mul]
  rfl
/-- **the label half costs one invocation price** (`invPrice`, by rank, from the kernel counts) -/
theorem lab_price {C : Type} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin raw.v) (Fin raw.R) C)
    {emb : CR.L3 (Fin raw.v) (Fin raw.R) → Nat} {un : Nat → CR.L3 (Fin raw.v) (Fin raw.R)}
    (Ro : GLab.Roles raw.v raw.R emb un) (cf : Co → SSC.Coef) (hMA) (hMAi) (hMB) (hMBi)
    (reg : C → Nat) (hCc) (hreg) (hC : Fintype.card C = %(nc)d) (φ : ℕ → ℝ) :
    (%(lab)s).cost φ = invPrice φ := by
  rw [lab_cost S Ro cf hMA hMAi hMB hMBi reg hCc hreg φ, hC, ← inv_cost φ]
  norm_num [bcost]
end GXD.%(name)s
#print axioms GXD.%(name)s.valid
#print axioms GXD.%(name)s.lab_price
''' % dict(info, imps='\nimport '.join(c[0] for c in chk if 'Scal' not in c[0] and 'YChk' not in c[0]), c=cop[0], a=nA, n=ns,
           f=ns + 1, tabpf=tabpf(''), runA=run('A', 0, nA), runB=run('B', nA, ns), lab=lab)
    open('%s/%sCert.lean' % (out, name), 'w').write(txt)
    return ['%s.%sCert' % (base, name), '%s.%sScalOK' % (base, name)]


def ll_(xs):
    return '[' + ', '.join(xs) + ']'


def final_module(name, cname, d, dx, g, out):
    """<Inst>.lean: the final theorems OVER ANY SCALAR HALF (compiles as soon as <C>Cert does): label half, price,
    unit list, rate fact and gx-chain's `GX.wht_of_halves` are all closed; what is left is `S : GX.Scal` with its
    gate matrices = the ordered products of the adds of `raw` (gx-scalar)."""
    h, v, R, W, m, nc = g['h'], g['v'], g['R'], d['W'], d['m'], g['nc']
    X = 'GXD.%s' % cname
    args = 'S Ro cf hMA hMAi hMB hMBi reg hCc hreg'

    def thm(nm, rate, A, B, s, ux):
        return f'''
/-- **Walsh-Hadamard transform, whole-block recursion on the bridged word B_2 with the gcert/1 circuit `{cname}`**,
over any scalar half of `{X}.raw`: the statement `WHTGoal` of `WHTCheck/Challenge.lean` with `1 - 2/10^11`
replaced by `1 - {A}/10^{B}`. -/
theorem {nm} (Ro : GLab.Roles {X}.raw.v {X}.raw.R emb un)
    (hMA : S.MA = SSC.matP un (GLab.mic cf ({X}.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMAi : S.MAi = SSC.matPinv un (GLab.mic cf ({X}.raw.gatesA.flatMap GXD.Gate.adds)))
    (hMB : S.MB = SSC.matP un (GLab.mic cf ({X}.raw.gatesB.flatMap GXD.Gate.adds)))
    (hMBi : S.MBi = SSC.matPinv un (GLab.mic cf ({X}.raw.gatesB.flatMap GXD.Gate.adds)))
    (reg : C → Nat) (hCc : ∀ k (q : Fin {X}.raw.R), S.Cc k q ≠ 0 → reg k = 2 * {X}.raw.v + q.val)
    (hreg : ∀ k, reg k ∈ {X}.raw.ret.map Prod.fst) (hC : Fintype.card C = {nc}) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - {A}/(10:ℝ)^{B}) W :=
  GX.wht_of_halves S ({X}.valid.lab {args})
    (by rw [Fintype.card_fin]; decide) {m} {W} (by rw [Fintype.card_fin]; rfl)
    (by rw [Fintype.card_fin, Fintype.card_fin]; rfl) (by norm_num) BlockAccounting.blocks{rate}
    (fun φ => by
      rw [{X}.lab_price {args} hC φ, Fintype.card_fin, Fintype.card_fin]
      exact BridgeRate.{name}.unit_cost{ux} φ)
    {s} (1 - {A}/(10:ℝ)^{B}) (by norm_num) (by norm_num) BlockAccounting.fold_{rate}

/-- the same from the FIVE scalar identities of gx-scalar's matrices of `{X}.raw` (`Work/GCert/Data/Glue.lean`) -/
theorem {nm.replace('_of_scal', '_of_ids')} (hv : 0 < {X}.raw.v)
    (hAi : GS.MAi {X}.raw hv * GS.MA {X}.raw hv = 1) (hBi : GS.MBi {X}.raw hv * GS.MB {X}.raw hv = 1)
    (hx : ∀ (t : Fin {X}.raw.v) (j : GS.Rl {X}.raw), (GS.MB {X}.raw hv * CR.scatM (GS.Jrm {X}.raw * GS.Ccm {X}.raw)
      * GS.MA {X}.raw hv) (CR.lX t) j = if CR.lX t = j then 1 else 0)
    (hy : ∀ (i : GS.Rl {X}.raw) (t : Fin {X}.raw.v), (GS.MB {X}.raw hv * CR.scatM (GS.Jrm {X}.raw * GS.Ccm {X}.raw)
      * GS.MA {X}.raw hv) i (CR.lY t) = if i = CR.lY t then 1 else 0)
    (hid : ∀ S t : Fin {X}.raw.v, (GS.MB {X}.raw hv * CR.scatM (GS.Jrm {X}.raw * GS.Ccm {X}.raw)
      * GS.MA {X}.raw hv) (CR.lY S) (CR.lX t) = if S = t then 1 else 0) :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - {A}/(10:ℝ)^{B}) W :=
  {nm} (GXD.scalOf {X}.raw hv hAi hBi hx hy hid) GS.toCoef (GXD.roles {X}.raw hv)
    (GXD.scalOf_MA _ hv hAi hBi hx hy hid) (GXD.scalOf_MAi _ hv hAi hBi hx hy hid)
    (GXD.scalOf_MB _ hv hAi hBi hx hy hid) (GXD.scalOf_MBi _ hv hAi hBi hx hy hid)
    (GXD.reg {X}.raw) (GXD.reg_slot {X}.raw hv hAi hBi hx hy hid) (GXD.reg_mem {X}.raw)
    (by rw [Fintype.card_fin]; decide)
'''
    txt = f'''import Work.GCert.Chain.End
import Work.GCert.Data.Glue
import Work.GCert.Data.{cname}Cert
import Work.GCert.Data.Inst{name}

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `{cname}` (h = {h}, m = {m}): final theorems over a scalar half
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`GX.wht_of_halves` (gx-chain) on the label half `{X}.valid` (kernel checks of `Work/GCert/Data/Gen/{cname}*`), its
price `{X}.lab_price`, the unit list `BlockAccounting.blocks{name}` (`W = {W}` live roles) and the rate facts
`fold_{name}` (`1 - {d['A']}/10^{d['B']}`), `fold_{name}x` (`1 - {dx['A']}/10^{dx['B']}`).
The ONLY hypothesis left is the scalar half: `S : GX.Scal (Fin {v}) (Fin {R}) C` whose gate matrices are the ordered
products of the adds of `raw` (`hMA .. hMBi`), with `{nc}` copies read from the retained registers (`reg`, `hCc`, `hreg`, `hC`);
`wht_{name}_of_ids`, `wht_{name}x_of_ids`: the same from the five identities `hAi hBi hx hy hid` of gx-scalar's matrices
`GS.MA GS.MAi GS.MB GS.MBi GS.Jrm GS.Ccm` of `raw` (the fields of the planned `GS.ScalOK`).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT

variable {{C : Type}} [Fintype C] [DecidableEq C] (S : GX.Scal (Fin {X}.raw.v) (Fin {X}.raw.R) C)
  {{emb : CR.L3 (Fin {X}.raw.v) (Fin {X}.raw.R) → Nat}} {{un : Nat → CR.L3 (Fin {X}.raw.v) (Fin {X}.raw.R)}}
  (cf : GXD.Co → SSC.Coef)
''' + thm('wht_' + name + '_of_scal', name, d['A'], d['B'], d['s'], '') + thm('wht_' + name + 'x_of_scal', name + 'x', dx['A'], dx['B'], dx['s'], '_x') + f'''
end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_{name}_of_scal
#print axioms OAI.PowerSaving.WHT.wht_{name}x_of_scal
#print axioms OAI.PowerSaving.WHT.wht_{name}_of_ids
#print axioms OAI.PowerSaving.WHT.wht_{name}x_of_ids
'''
    open(out + '%s.lean' % name, 'w').write(txt)


def main_module(name, cname, d, dx, out):
    """<Inst>Main.lean: the CLOSED theorems (what the comparator solution cites).  WRITTEN against gx-scalar's planned
    `GS.ScalOK` (fields / theorems hv hAi hBi hx hy hid, SCALAR v2); compiles when Work/GCert/Scalar/Main.lean exists."""
    K = 'GXD.%s.scalOK' % cname

    def thm(sfx, A, B):
        return f'''
/-- **Walsh-Hadamard transform in `O(n (log n)^(1 - {A}/10^{B}))`-type time bounds: whole-block recursion on the bridged
word B_2 with the kernel-checked gcert/1 circuit `{cname}`.** -/
theorem wht_main_{name}{sfx} :
    ∃ solve W, WHTProgram solve W ∧ BlockWHT.WHTTimeBoundsAt (1 - {A}/(10:ℝ)^{B}) W :=
  wht_{name}{sfx}_of_ids {K}.hv {K}.hAi {K}.hBi {K}.hx {K}.hy {K}.hid
'''
    txt = f'''import Work.GCert.Scalar.Main
import Work.GCert.Data.{cname}ScalOK
import Work.GCert.Data.{name}

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `{cname}`: THE CLOSED THEOREMS
GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.
`wht_{name}_of_ids` (label half, price, unit list, rate fact, gx-chain's end theorem) applied to the scalar half
`{K} : GS.ScalOK GXD.{cname}.raw` (kernel checks `scal<i>_ok`, `ychk_ok`; soundness: gx-scalar).
-/

namespace OAI
namespace PowerSaving
namespace WHT
open BlockWHT
''' + thm('', d['A'], d['B']) + thm('x', dx['A'], dx['B']) + f'''
end WHT
end PowerSaving
end OAI
#print axioms OAI.PowerSaving.WHT.wht_main_{name}
#print axioms OAI.PowerSaving.WHT.wht_main_{name}x
'''
    open(out + '%sMain.lean' % name, 'w').write(txt)
