"""gxrate.py: rate, instance, final, challenge and solution modules of the bridged word
B_2 (m = 5 h, any h) for a gcert/1 certificate generated by gxgen.py.  tools/gen/crate.py with the
generalised end theorem; bridge-rate's text generators (tools/gen/foldlib.py, foldgen.py) are used READ-ONLY.

usage: gxrate.py <Inst> <Name> [rate-only] [B=8 s=13] [Bx=10 sx=40]          e.g. gxrate.py B2Gp11 P11
   reads   <GX_OUT>/logs/gen-<Name>.json   (block histogram of one invocation, from gxgen.py)
   writes  Work/GCert/Data/Rate<Inst>.lean, Rate<Inst>x.lean     rate lemmas (arithmetic only)
           Work/GCert/Data/Inst<Inst>.lean                       unit price list = block list (arithmetic only)
           Work/GCert/Data/<Inst>.lean                           final theorems through GX.wht_of_halves (gxbind.CHAIN)
           Work/GCert/Data/Challenge<Inst>x.lean, Solution<Inst>x.lean, <GX_OUT>/cmp/<Inst>x.json
           <GX_OUT>/logs/rate-<Inst>.json, rate-<Inst>x.json
"""
import sys, json
import gxpaths
import foldlib as fl
import foldgen as fg
import gxunit as gu
import gxbind as gb

ROOT = gxpaths.OUT
MY = ROOT
OUT = ROOT + 'Work/GCert/Data/'
NS = 'OAI.PowerSaving.BlockAccounting'


def rate_module(name, u, B, s, cname):
    A, Af, Ar, Arf = fl.best_units(u, B, s)
    Ae, Are = A, Ar
    while fl.plan_block(u, A, B, s) is None:
        A -= 1
    while fl.plan_rank(u, Ar, B, s) is None:
        Ar -= 1
    while fl.plan_sharp(u, Af, B) is None:
        Af += 1
    k = 0
    while fg.rank_sharp_text(name, u, Arf, B) is None and k < 20:
        Arf += 1
        k += 1
    m, W, D = u['m'], u['W'], u['D']
    doc = ('Block list `(rank, count)` of ONE unit of the bridged five-stage word B_2 with the gcert/1 circuit `%s` '
           '(h = %d, m = %d): five invocations (ALL blocks of one invocation: x roles, y roles, slots, scratch copies; '
           'the kernel-counted list `GXD.%s.hist`), and for each of the v = %d ports the idle climbs of its two twins '
           '(2 blocks each of rank h-1, 2h-2, 2h+2, 4); R = %d slots shared by the five stages.'
           % (cname, u['h'], m, cname, u['v'], u['R']))
    lst = fg.list_text(name, u, doc)
    blk, P = fg.block_text(name, u, A, B, s)
    shp, PS = fg.sharp_text(name, u, Af, B)
    rk, PR = fg.rank_text(name, u, Ar, B, s)
    rks = fg.rank_sharp_text(name, u, Arf, B)
    assert rks is not None
    head = f'''import Work.BlockAccounting.Moment
import Work.BlockAccounting.Sharp
import Work.FoldRate.RankTools

/-!
# (key: gx-data) Rate lemmas for one unit of the bridged word B_2 with the gcert/1 circuit `{cname}` (h = {u['h']})

GENERATED by checks/wht26/gx-data/py/gxrate.py with the text generators of checks/wht9/bridge-rate/py
(used read-only).  No `sorry`.  Arithmetic only.

One unit: `W = {W}` live roles, label dimension `m = {m}`, deficit `D = {D}`.

* `blocks{name}`            the block list (rank, count) of ONE unit;
* `fold_{name}`             whole-block fact at `1 - {A}/10^{B}`, fill parameter `s = {s}` (slack {P["slack_rel"]:.2e});
* `fold_{name}_sharp`       `W ≤ moment` at `1 - {Af}/10^{B}`: fails for every table (excess {PS["slack_rel"]:.2e});
* `foldRank_{name}`         per-rank fact at `1 - {Ar}/10^{B}`, `s = {s}` (slack {PR["slack_rel"]:.2e});
* `foldRank_{name}_sharp`   per-rank: fails for every table at `1 - {Arf}/10^{B}`.

That a Lean word has `G` times this list as its block histogram is NOT proved here.
-/

set_option maxRecDepth 4000

namespace {NS}
open Finset

'''
    foot = f'\nend {NS}\n\n' + '\n'.join('#print axioms %s.%s_%s' % (NS, a, b) for a, b in
                                        [('fold', name), ('fold', name + '_sharp'), ('foldRank', name),
                                         ('foldRank', name + '_sharp')]) + '\n'
    open(OUT + 'Rate%s.lean' % name, 'w').write(head + lst + '\n' + blk + '\n' + shp + '\n' + rk + '\n' + rks + foot)
    info = dict(name=name, m=m, W=W, D=D, H=u['H'], A=A, A_eval=Ae, A_fails=Af, A_rank=Ar, A_rank_eval=Are,
                A_rank_fails=Arf, B=B, s=s, slack=P['slack_rel'], excess=PS['slack_rel'], rank_slack=PR['slack_rel'],
                kind='B2', h=u['h'], R=u['R'], v=u['v'], inv=u['inv'], circuit='gcert1:' + cname)
    json.dump(info, open(MY + 'logs/rate-%s.json' % name, 'w'), indent=1)
    print('Rate%s: block %d/10^%d (evaluated %d, fails %d), rank %d (evaluated %d, fails %d), s=%d, slack %.2e, rank slack %.2e'
          % (name, A, B, Ae, Af, Ar, Are, Arf, s, P['slack_rel'], PR['slack_rel']))
    return info


def inst_module(name, cname, d, dx, u):
    """arithmetic only: 5 x (price of the kernel-counted histogram) + v x bankPrice h = listCost of the unit list"""
    h, m, W, D, v, R = d['h'], d['m'], d['W'], d['D'], d['v'], d['R']
    terms = ' + '.join('%d * φ %d' % (n, r) for r, n in sorted(u['inv'].items()))
    blk = 'blocks' + name
    txt = f'''import Work.BridgeGeom.B2
import Work.FoldRate.Group
import Work.GCert.Data.Rate{name}
import Work.GCert.Data.Rate{name}x

/-!
# (key: gx-data) Bridged word B_2 with the gcert/1 circuit `{cname}`, h = {h}: the unit price is the price of the block list

GENERATED by checks/wht26/gx-data/py/gxrate.py.  No `sorry`.  Arithmetic only (no certificate is imported).

One unit: `W = {W}` live roles (`4 v + R`, `v = {v}`, `R = {R}`), label dimension `m = {m}`, deficit `D = {D}`.
`invPrice φ` = the price of the blocks of ONE invocation (the kernel-counted list `GXD.{cname}.hist`, by rank);
`unitPrice φ = 5 * invPrice φ + v * BG.bankPrice h φ = listCost φ BlockAccounting.{blk}` (`unit_cost`).
Whole-block `1 - {d['A']}/10^{d['B']}` (fails at {d['A_fails']}), ten decimals `1 - {dx['A']}/10^{dx['B']}` (fails at {dx['A_fails']}).
-/

namespace OAI
namespace PowerSaving
namespace BridgeRate
namespace {name}
open Finset Binary Matrix RAM CB FoldRate
noncomputable section

/-- price of the blocks of ONE invocation of `{cname}` (all roles and scratch copies), by rank -/
def invPrice (φ : ℕ → ℝ) : ℝ := {terms}

/-- price of ONE unit of the bridged word B_2 -/
def unitPrice (φ : ℕ → ℝ) : ℝ := 5 * invPrice φ + (({v}:ℕ):ℝ) * BG.bankPrice {h} φ

/-- **The unit price is the price of the unit block list.** -/
theorem unit_cost (φ : ℕ → ℝ) : unitPrice φ = listCost φ BlockAccounting.{blk} := by
  unfold unitPrice invPrice
  simp only [BG.bankPrice, listCost, BlockAccounting.{blk}, List.map_cons, List.map_nil,
    List.sum_cons, List.sum_nil]
  norm_num [bcost]
  try ring

theorem blocks_x : BlockAccounting.{blk} = BlockAccounting.{blk}x := rfl

theorem unit_cost_x (φ : ℕ → ℝ) : unitPrice φ = listCost φ BlockAccounting.{blk}x := by
  rw [unit_cost, blocks_x]

/-- one unit stands for `W * m - D` unit moves -/
theorem unit_tally : unitPrice (fun r => (r:ℝ)) = (({W}:ℕ):ℝ) * (({m}:ℕ):ℝ) - (({D}:ℕ):ℝ) := by
  rw [unit_cost]
  exact BlockAccounting.{blk}_tally

end
end {name}
end BridgeRate
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.BridgeRate.{name}.unit_cost
#print axioms OAI.PowerSaving.BridgeRate.{name}.unit_tally
'''
    open(OUT + 'Inst%s.lean' % name, 'w').write(txt)


def pack(name, A, B, term, pname):
    """comparator package: Work/BridgeRate/ChallengeB2L16x.lean with theorem name and exponent changed"""
    src = open(gxpaths.GEN + '/templates/ChallengeB2L16x.lean.txt').read()
    thm = 'wht_main_block_' + name
    assert src.count('wht_main_block_B2L16x') == 2 and src.count('4059928/(10:ℝ)^10') == 2 and src.count('4059928/10^10') == 2
    sub = lambda t: t.replace('4059928/(10:ℝ)^10', '%d/(10:ℝ)^%d' % (A, B)).replace('4059928/10^10', '%d/10^%d' % (A, B))
    new = (sub(src.replace('wht_main_block_B2L16x', thm))
           .replace('Work.BridgeRate.ChallengeB2L16x', 'Work.GCert.Data.Challenge' + pname)
           .replace('Work.BridgeRate.SolutionB2L16x', 'Work.GCert.Data.Solution' + pname))
    a, b = src.split('\n'), new.split('\n')
    assert len(a) == len(b)
    code = [k for k in range(len(a)) if a[k] != b[k] and k > a.index('-/')]
    assert len(code) == 3, code                      # doc line of the theorem, theorem name, statement
    open(OUT + 'Challenge%s.lean' % pname, 'w').write(new)
    sol = open(gxpaths.GEN + '/templates/SolutionB2L16x.lean.txt').read()
    assert sol.count('wht_main_B2L16x') == 2
    sol = sub(sol.replace('wht_main_block_B2L16x', thm).replace('wht_main_B2L16x', term)
              .replace('Work.BridgeRate.B2L16x', 'Work.GCert.Data.' + (name[:-1] if name.endswith('x') else name) + 'Main')
              .replace('Work.BridgeRate.SolutionB2L16x', 'Work.GCert.Data.Solution' + pname))
    open(OUT + 'Solution%s.lean' % pname, 'w').write(sol)
    cfg = {"challenge_module": 'Work.GCert.Data.Challenge' + pname, "solution_module": 'Work.GCert.Data.Solution' + pname,
           "theorem_names": ['OAI.PowerSaving.WHT.' + thm], "definition_names": [],
           "permitted_axioms": ["propext", "Quot.sound", "Classical.choice"], "enable_nanoda": False}
    json.dump(cfg, open(MY + 'cmp/%s.json' % pname, 'w'), indent=2)
    print('packed', pname, thm, '1 - %d/10^%d' % (A, B), 'challenge code lines changed (0-based):', code)


if __name__ == '__main__':
    name, cname = sys.argv[1], sys.argv[2]
    g = json.load(open(MY + 'logs/gen-%s.json' % cname))
    u = gu.unit({int(r): n for r, n in g['hist'].items()}, g['h'], g['v'], g['R'], g['cst'])
    print('unit %s: W=%d m=%d D=%d tally=%d blocks=%s' % (name, u['W'], u['m'], u['D'], u['W'] * u['m'] - u['D'],
                                                         sorted(u['H'].items())))
    d = rate_module(name, u, 8, 13, cname)
    dx = rate_module(name + 'x', u, 10, 40, cname)
    inst_module(name, cname, d, dx, u)
    if 'rate-only' not in sys.argv:
        gb.final_module(name, cname, d, dx, g, OUT)
        gb.main_module(name, cname, d, dx, OUT)
        pack(name + 'x', dx['A'], dx['B'], 'wht_main_%sx' % name, name + 'x')
        pack(name, d['A'], d['B'], 'wht_main_%s' % name, name)
