import Work.Combine.XG

/-!
# GFrame labels, part 1 (key: eng-labels): the abstract route calculus

The label layer is written ONCE over a structure `Calc α`: what a block engine offers to the
label calculus on the label space `α`.

* `Calc α`     `Step l M N c` (one role from the frame matrix `M` to `N` at price `c`),
               `Route S T g c` (all roles, scalar map `g`), `Free A` (a matrix one role gets
               for free), and the combinators: `refl/cast/trans`, `gate` (roles with IDENTICAL
               frame matrices), `on_role`, `free`, `block` (ONE block of rank `r` along ANY
               `r` linearly independent directions);
* `xcalc α`    the OLD engine (`XStep`, `XRoute` of `Work.BlockApply.Exact`; free = shifts);
* `FMv K M N rs`  a one-role move from `M` to `N` paying blocks of ranks `rs`: generated by
               `free` (left multiplication by a free matrix), `block` (left multiplication by
               `blockMat z`) and `trans`.  This IS the frame lemma as a certificate format:
               `N = A * blockMat z * B * M` with `A`, `B` free is `FMv K M N [r]`;
* `FMv.step`   every such move is a `K.Step` of price `rcost φ rs`.

No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving.GF
open Binary Matrix Finset RAM CB
noncomputable section

/-- What a block engine offers to the label calculus on the label space `α`. -/
structure Calc (α : Type) [Fintype α] [DecidableEq α] where
  Step : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ], ρ → CMat α → CMat α → ((ℕ → ℝ) → ℝ) → Prop
  Route : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ], (ρ → CMat α) → (ρ → CMat α) →
    ((ρ → ℂ) → (ρ → ℂ)) → ((ℕ → ℝ) → ℝ) → Prop
  Free : CMat α → Prop
  step_refl : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (l : ρ) (M : CMat α),
    Step l M M (fun _ => 0)
  step_cast : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] {l : ρ} {M N : CMat α}
    {c c' : (ℕ → ℝ) → ℝ}, Step l M N c → (∀ φ, c φ = c' φ) → Step l M N c'
  step_trans : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] {l : ρ} {M N L : CMat α}
    {c c' : (ℕ → ℝ) → ℝ}, Step l M N c → Step l N L c' → Step l M L (fun φ => c φ + c' φ)
  route_refl : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (S : ρ → CMat α),
    Route S S id (fun _ => 0)
  route_cast : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] {S T : ρ → CMat α}
    {g : (ρ → ℂ) → (ρ → ℂ)} {c c' : (ℕ → ℝ) → ℝ}, Route S T g c → (∀ φ, c φ = c' φ) →
    Route S T g c'
  route_trans : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] {S T U : ρ → CMat α}
    {g h : (ρ → ℂ) → (ρ → ℂ)} {c c' : (ℕ → ℝ) → ℝ}, Route S T g c → Route T U h c' →
    Route S U (h ∘ g) (fun φ => c φ + c' φ)
  gate : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (g : Matrix ρ ρ ℚ) (S T : ρ → CMat α),
    (∀ i j, g i j ≠ 0 → T i = S j) → Route S T (actPoint g) (fun _ => 0)
  on_role : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (S : ρ → CMat α) (l : ρ) (N : CMat α)
    {c : (ℕ → ℝ) → ℝ}, Step l (S l) N c → Route S (Function.update S l N) id c
  free_one : Free 1
  free_mul : ∀ {A B : CMat α}, Free A → Free B → Free (A * B)
  free_shift : ∀ z : Space α, Free (shift z)
  free : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (l : ρ) (M : CMat α) {A : CMat α},
    Free A → Step l M (A * M) (fun _ => 0)
  block : ∀ {ρ : Type} [Fintype ρ] [DecidableEq ρ] (l : ρ) (M : CMat α) {r : ℕ}
    (z : Fin r → Space α), LinearIndependent F z → 1 ≤ r → r < Fintype.card α →
    Step l M (blockMat z * M) (fun φ => φ r)

section Old
variable {α : Type} [Fintype α] [DecidableEq α] {ρ : Type} [Fintype ρ] [DecidableEq ρ]

/-- the free one-role matrices of the OLD engine: products of shifts. -/
inductive XFree : CMat α → Prop
  | one : XFree 1
  | shift (z : Space α) : XFree (shift z)
  | mul {A B : CMat α} : XFree A → XFree B → XFree (A * B)

theorem xstep_shift (l : ρ) (M : CMat α) (z : Space α) :
    XStep l M (shift z * M) (fun _ => 0) := by
  refine ⟨[BMove.shift l z], shift z, ?_, ?_, rfl, ?_⟩
  · intro mv hmv
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hmv
    subst hmv; trivial
  · intro φ; simp [BWord.costR, BMove.costR, BMove.rk?]
  · intro f x
    rw [walk_flat_cons]; rfl

theorem xstep_block (l : ρ) (M : CMat α) {r : ℕ} (z : Fin r → Space α)
    (ind : LinearIndependent F z) (h1 : 1 ≤ r) (h2 : r < Fintype.card α) :
    XStep l M (blockMat z * M) (fun φ => φ r) := by
  refine ⟨[BMove.block l r z ind], blockMat z, ?_, ?_, rfl, ?_⟩
  · intro mv hmv
    simp only [List.mem_cons, List.not_mem_nil, or_false] at hmv
    subst hmv; exact ⟨h1, h2⟩
  · intro φ; simp [BWord.costR, BMove.costR, BMove.rk?]
  · intro f x
    rw [walk_flat_cons]; rfl

theorem xstep_free (l : ρ) {A : CMat α} (h : XFree A) (M : CMat α) :
    XStep l M (A * M) (fun _ => 0) := by
  induction h generalizing M with
  | one => rw [one_mul]; exact XStep.refl l M
  | shift z => exact xstep_shift l M z
  | mul _ _ iha ihb =>
    rw [mul_assoc]
    exact ((ihb M).trans (iha _)).cast (fun φ => by simp)

end Old

/-- **The old engine as a route calculus.** -/
def xcalc (α : Type) [Fintype α] [DecidableEq α] : Calc α where
  Step := fun l M N c => XStep l M N c
  Route := fun S T g c => XRoute S T g c
  Free := XFree
  step_refl := fun l M => XStep.refl l M
  step_cast := fun a h => a.cast h
  step_trans := fun a b => a.trans b
  route_refl := fun S => XRoute.refl
  route_cast := fun a h => a.cast h
  route_trans := fun a b => a.trans b
  gate := fun g S T h => XRoute.gate g S T h
  on_role := @fun ρ _ _ S l N c h => XRoute.on_role S l N h
  free_one := XFree.one
  free_mul := XFree.mul
  free_shift := XFree.shift
  free := @fun ρ _ _ l M A h => xstep_free l h M
  block := @fun ρ _ _ l M r z ind h1 h2 => xstep_block l M z ind h1 h2

section FMv
variable {α : Type} [Fintype α] [DecidableEq α]

/-- **A one-role move with its block ranks.**  `FMv K M N rs`: the frame matrix `M` goes to
`N` by free matrices and blocks, the blocks having ranks `rs` (in order). -/
inductive FMv (K : Calc α) : CMat α → CMat α → List ℕ → Prop
  | free {M A : CMat α} : K.Free A → FMv K M (A * M) []
  | block {M : CMat α} {r : ℕ} (z : Fin r → Space α) : LinearIndependent F z → 1 ≤ r →
      r < Fintype.card α → FMv K M (blockMat z * M) [r]
  | trans {M N L : CMat α} {a b : List ℕ} : FMv K M N a → FMv K N L b → FMv K M L (a ++ b)
  | zero {M N : CMat α} {a : List ℕ} : FMv K M N a → FMv K M N (0 :: a)

namespace FMv
variable {K : Calc α} {M N L : CMat α} {rs : List ℕ}

theorem refl (K : Calc α) (M : CMat α) : FMv K M M [] := by
  have h := FMv.free (K := K) (M := M) K.free_one
  rwa [one_mul] at h

theorem shift (K : Calc α) (M : CMat α) (z : Space α) : FMv K M (Binary.shift z * M) [] :=
  FMv.free (K.free_shift z)

/-- the certificate format of the frame lemma: `free * block * free`. -/
theorem factor {A B : CMat α} {r : ℕ} (z : Fin r → Space α) (ind : LinearIndependent F z)
    (h1 : 1 ≤ r) (h2 : r < Fintype.card α) (hA : K.Free A) (hB : K.Free B) (M : CMat α) :
    FMv K M (A * blockMat z * B * M) [r] := by
  have e : A * blockMat z * B * M = A * (blockMat z * (B * M)) := by simp only [mul_assoc]
  rw [e]
  exact ((FMv.free (M := M) hB).trans (FMv.block z ind h1 h2)).trans (FMv.free hA)

/-- **Every one-role move is a step of the engine**, price `rcost φ rs`. -/
theorem step {ρ : Type} [Fintype ρ] [DecidableEq ρ] (h : FMv K M N rs) (l : ρ) :
    K.Step l M N (fun φ => rcost φ rs) := by
  induction h with
  | free hA => exact K.step_cast (K.free l _ hA) (fun φ => (rcost_nil φ).symm)
  | block z ind h1 h2 =>
    exact K.step_cast (K.block l _ z ind h1 h2)
      (fun φ => by rw [rcost_single, bcost_pos φ (by omega)])
  | trans _ _ iha ihb =>
    exact K.step_cast (K.step_trans iha ihb) (fun φ => (rcost_append φ _ _).symm)
  | zero _ ih =>
    exact K.step_cast ih (fun φ => by rw [rcost_cons, bcost_zero, zero_add])

end FMv
end FMv

end
end PowerSaving.GF
end OAI

#print axioms OAI.PowerSaving.GF.xcalc
#print axioms OAI.PowerSaving.GF.FMv.step
#print axioms OAI.PowerSaving.GF.FMv.factor
