import Work.GCert.Chain.NetCert
import Work.GCert.Chain.WinB
import Work.BridgeGeom.B2

/-!
# (key: gx-chain) THE NETWORK LEMMA (spec statement 6): the bridged word B_2 delivers a `GCert`

GENERATED by checks/wht26/gx-chain/py/netgen.py from Work/BridgeGeom/Net.lean (section Net):
the geometry of `BG.geomBridge2`, word for word, with the windows `gwinB` (`.Xm = BG.fmapB`).

`bridge2_gcert I hH`: for every generalised invocation package, a `GCert` on
`card Γ * (4 card T + card Sl)` live roles, label dimension `5h`, unit price
`5 * I.cost φ + card T * BG.bankPrice h φ` (unchanged).  No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving
namespace GX
open Binary Matrix Finset RAM SS CB RF BR GF BG
noncomputable section

section Net
variable {H T Sl C : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C]
variable (I : GInv H T Sl C) (base : T → OBase H) (l : H)
  (hbase : ∀ t, I.tv t = (base t).v l) (hH : 1 ≤ Fintype.card H)
include hbase

lemma ggeom_x01 (g : Orth (L5 H)) (t : T) :
    PhiB g ∅ 1 = PhiB (RrB (base t) l (0 : Fin 4) g) (qS bs1 l) (tt (I.tv t)) := by
  rw [hbase t]
  exact bankT_x0 (base t) l (0 : Fin 4) g

lemma ggeom_y01 (g : Orth (L5 H)) (t : T) :
    PhiB g ∅ (1 + tt (I.tv t)) = PhiB (RrB (base t) l (0 : Fin 4) g) (qS bs1 l) 0 := by
  rw [hbase t]
  exact bankT_y0 (base t) l (0 : Fin 4) g

/-- consecutive stages `c ∈ bs`, `c' ∉ bs`: `X` leaves where it enters. -/
lemma ggeom_xx (bs : Finset (Fin 4)) (c c' : Fin 4) (hc : c ∈ bs) (hc' : c' ∉ bs)
    (g : Orth (L5 H)) (t : T) :
    PhiB (RrB (base t) l c g) (qS bs l) 1
      = PhiB (RrB (base t) l c' g) (qS (insert c' bs) l) (tt (I.tv t)) := by
  rw [hbase t]
  exact bankT_xx (base t) l bs c c' hc hc' g

/-- consecutive stages: `Y` leaves where it enters. -/
lemma ggeom_yy (bs : Finset (Fin 4)) (c c' : Fin 4) (hc : c ∈ bs) (hc' : c' ∉ bs)
    (g : Orth (L5 H)) (t : T) :
    PhiB (RrB (base t) l c g) (qS bs l) (1 + tt (I.tv t))
      = PhiB (RrB (base t) l c' g) (qS (insert c' bs) l) 0 := by
  rw [hbase t]
  exact bankT_yy (base t) l bs c c' hc hc' g

/-- terminal identity of the bank pairs of the class `(g,t)`. -/
lemma ggeom_term5 (g : Orth (L5 H)) (t : T) :
    kernel (L5 H) * PhiB g ∅ (tt (I.tv t))
      = shift ((BBB (base t) g).v (Sum.inl l))
          * frame (BBB (base t) g) (univ \ {Sum.inl l}) := by
  rw [hbase t]
  exact class_term (base t) l g

include hH

/-- pair 2 before the first gate layer, `X`: ONE block of rank `2h-2`. -/
lemma ggeom_aX2 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB g ∅ (tt (I.tv t))) (PhiB (RrB (base t) l (0 : Fin 4) g) (qS bs1 l) 1)
      (fun φ => bcost φ (2 * Fintype.card H - 2)) := by
  rw [hbase t]
  exact idle_X0 (base t) l hB4 hH (0 : Fin 4) g _ (by omega)

/-- pair 2 before the first gate layer, `Y`: ONE block of rank `2h-2`. -/
lemma ggeom_aY2 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB g ∅ 0) (PhiB (RrB (base t) l (0 : Fin 4) g) (qS bs1 l) (1 + tt (I.tv t)))
      (fun φ => bcost φ (2 * Fintype.card H - 2)) := by
  rw [hbase t]
  exact idle_Y0 (base t) l hB4 hH (0 : Fin 4) g _ (by omega)

/-- pair 1 at the end (idle in stages 3, 4, then the last four moves), `X`: ONE block `2h+2`. -/
lemma ggeom_fX1 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB (RrB (base t) l (1 : Fin 4) g) (qS bs2 l) 1) (kernel (L5 H))
      (fun φ => bcost φ (2 * Fintype.card H + 2)) :=
  idle_Xend (base t) l hB4 hH bs2 (1 : Fin 4) (Finset.mem_insert_self _ _) g _
    (by rw [card_bs2, Fintype.card_fin]; omega)

/-- pair 1 at the end, `Y`: ONE block of rank `2h+2`. -/
lemma ggeom_fY1 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB (RrB (base t) l (1 : Fin 4) g) (qS bs2 l) (1 + tt (I.tv t)))
      (frame (BBB (base t) g) (univ \ {Sum.inl l}))
      (fun φ => bcost φ (2 * Fintype.card H + 2)) := by
  rw [hbase t]
  exact idle_Yend (base t) l hB4 hH bs2 (1 : Fin 4) (Finset.mem_insert_self _ _) g _
    (by rw [card_bs2, Fintype.card_fin]; omega)

/-- pair 2 after stage 4, `X`: ONE block of rank `4`. -/
lemma ggeom_fX2 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB (RrB (base t) l (3 : Fin 4) g) (qS bs4 l) 1) (kernel (L5 H))
      (fun φ => bcost φ 4) :=
  idle_Xend (base t) l hB4 hH bs4 (3 : Fin 4) (Finset.mem_insert_self _ _) g _
    (by rw [card_bs4, Fintype.card_fin]; omega)

/-- pair 2 after stage 4, `Y`: ONE block of rank `4`. -/
lemma ggeom_fY2 (g : Orth (L5 H)) (t : T) :
    XReach (PhiB (RrB (base t) l (3 : Fin 4) g) (qS bs4 l) (1 + tt (I.tv t)))
      (frame (BBB (base t) g) (univ \ {Sum.inl l})) (fun φ => bcost φ 4) := by
  rw [hbase t]
  exact idle_Yend (base t) l hB4 hH bs4 (3 : Fin 4) (Finset.mem_insert_self _ _) g _
    (by rw [card_bs4, Fintype.card_fin]; omega)

/-- **The bridged word B_2 as a term of `BR.Bridge2`**: five stages on the label space
`H ⊕ (Fin 4 × H)`, for any invocation package whose lines are the vectors of index `l` of
orthonormal bases. -/
def ggeomBridge2 : GBridge2 H T Sl C (L5 H) (Orth (L5 H)) where
  I := I
  G0 := fun g => gwinB hB4 hH g ∅
  G1 := fun d => gwinB hB4 hH d (qS bs1 l)
  G2 := fun d => gwinB hB4 hH d (qS bs2 l)
  G3 := fun d => gwinB hB4 hH d (qS bs3 l)
  G4 := fun d => gwinB hB4 hH d (qS bs4 l)
  r1 := fun t => RrB (base t) l (0 : Fin 4)
  r2 := fun t => RrB (base t) l (1 : Fin 4)
  r3 := fun t => RrB (base t) l (2 : Fin 4)
  r4 := fun t => RrB (base t) l (3 : Fin 4)
  s1 := (Orth.colPerm (tauB (0 : Fin 4))).symm
  s2 := (Orth.colPerm (tauB (1 : Fin 4))).symm
  s3 := (Orth.colPerm (tauB (2 : Fin 4))).symm
  s4 := (Orth.colPerm (tauB (3 : Fin 4))).symm
  N1 := fun d => unframeM (d.1 * Matrix.fromBlocks 0 0 0 (diagI (qS bs1 l)) * d.1ᵀ)
  W1 := fun d => frameM (d.1 * diagI (JB univ ∅) * d.1ᵀ)
  N2 := fun d => unframeM (d.1 * Matrix.fromBlocks 0 0 0 (diagI (qS bs2 l)) * d.1ᵀ)
  W2 := fun d => frameM (d.1 * diagI (JB univ ∅) * d.1ᵀ)
  N3 := fun d => unframeM (d.1 * Matrix.fromBlocks 0 0 0 (diagI (qS bs3 l)) * d.1ᵀ)
  W3 := fun d => frameM (d.1 * diagI (JB univ ∅) * d.1ᵀ)
  N4 := fun d => unframeM (d.1 * Matrix.fromBlocks 0 0 0 (diagI (qS bs4 l)) * d.1ᵀ)
  W4 := fun d => frameM (d.1 * diagI (JB univ ∅) * d.1ᵀ)
  u := fun g t => (BBB (base t) g).v (Sum.inl l)
  YF := fun g t => frame (BBB (base t) g) (univ \ {Sum.inl l})
  hm := two_le_card_LB hB4 hH
  caX := fun φ => bcost φ (2 * Fintype.card H - 2)
  caY := fun φ => bcost φ (2 * Fintype.card H - 2)
  cX1 := fun φ => bcost φ (2 * Fintype.card H + 2)
  cY1 := fun φ => bcost φ (2 * Fintype.card H + 2)
  cX2 := fun φ => bcost φ 4
  cY2 := fun φ => bcost φ 4
  inv0 := fun g t => ⟨unframeM (g.1 * Matrix.fromBlocks (tt (I.tv t)) 0 0 (diagI ∅) * g.1ᵀ),
    frameM_unframeM _⟩
  z0 := fun g => PhiB_zero_empty g
  hN1 := fun d => frameM_unframeM _
  hW1 := fun d => PhiB_one d (qS bs1 l)
  hN2 := fun d => frameM_unframeM _
  hW2 := fun d => PhiB_one d (qS bs2 l)
  hN3 := fun d => frameM_unframeM _
  hW3 := fun d => PhiB_one d (qS bs3 l)
  hN4 := fun d => frameM_unframeM _
  hW4 := fun d => PhiB_one d (qS bs4 l)
  x01 := fun g t => ggeom_x01 I base l hbase g t
  y01 := fun g t => ggeom_y01 I base l hbase g t
  x12 := fun g t => ggeom_xx I base l hbase bs1 0 1 (Finset.mem_singleton_self _) mem1 g t
  y12 := fun g t => ggeom_yy I base l hbase bs1 0 1 (Finset.mem_singleton_self _) mem1 g t
  x23 := fun g t => ggeom_xx I base l hbase bs2 1 2 (Finset.mem_insert_self _ _) mem2 g t
  y23 := fun g t => ggeom_yy I base l hbase bs2 1 2 (Finset.mem_insert_self _ _) mem2 g t
  x34 := fun g t => ggeom_xx I base l hbase bs3 2 3 (Finset.mem_insert_self _ _) mem3 g t
  y34 := fun g t => ggeom_yy I base l hbase bs3 2 3 (Finset.mem_insert_self _ _) mem3 g t
  sfin := fun g => helper_fin5 g
  aX2 := fun g t => ggeom_aX2 I base l hbase hH g t
  aY2 := fun g t => ggeom_aY2 I base l hbase hH g t
  fX1 := fun g t => ggeom_fX1 I base l hbase hH g t
  fY1 := fun g t => ggeom_fY1 I base l hbase hH g t
  fX2 := fun g t => ggeom_fX2 I base l hbase hH g t
  fY2 := fun g t => ggeom_fY2 I base l hbase hH g t
  term := fun g t => ggeom_term5 I base l hbase g t

end Net

section End
variable {H T Sl C : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C]

/-- an orthonormal basis through a unit vector with a zero coordinate, at any index. -/
theorem base_ex (z : Space H) (hz : dot z z = 1) (hg : ∃ p, z p = 0) (l : H) :
    ∃ A : OBase H, z = A.v l := by
  obtain ⟨p, hp⟩ := hg
  obtain ⟨A, k, hA⟩ := exists_base_one z hz p hp
  refine ⟨reindex A (Equiv.swap k l), ?_⟩
  rw [← hA]
  show A.v k = A.v (Equiv.swap k l l)
  rw [Equiv.swap_apply_right]

/-- **Generalised certificate of the bridged word B_2** for a generalised invocation package. -/
theorem bridge2_gcert (I : GInv H T Sl C) (hH : 1 ≤ Fintype.card H) :
    GCert (L5 H) (Sum.inl : BLive (Orth (L5 H)) T Sl → BRole (Orth (L5 H)) T Sl C)
      (fun φ => (Fintype.card (Orth (L5 H)) : ℝ)
        * (5 * I.cost φ + (Fintype.card T : ℝ) * bankPrice (Fintype.card H) φ)) := by
  obtain ⟨l⟩ : Nonempty H := Fintype.card_pos_iff.mp (by omega)
  have hb : ∀ t, ∃ A : OBase H, I.tv t = A.v l :=
    fun t => base_ex (I.tv t) (I.hunit t) (I.hgap t) l
  choose base hbase using hb
  exact gbridge2_certificate (ggeomBridge2 I base l hbase hH)

end End
end
end GX
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.GX.ggeomBridge2
#print axioms OAI.PowerSaving.GX.bridge2_gcert
