import Work.GCert.Chain.NetStage
import Work.GFrame.Top.Assemble

/-!
# (key: gx-chain) The bridged word B_2 on the generalised engine: the certificate `GCert`

GENERATED by checks/wht26/gx-chain/py/netgen.py from Work/Bridge/Cert.lean (section Net).
`gbridge2_certificate`: a `GCert` on the live roles `BLive Γ T Sl` with price `card Γ * N.unit φ`.
The gate layers, the idle climbs and the exchange are the old routes (`GRoute.ofX`).  No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving
namespace GX
open Binary Matrix Finset RAM SS CB RF BR GF
noncomputable section

section Net
variable {H T Sl C α Γ : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C] [Fintype α] [DecidableEq α]
  [Fintype Γ] [DecidableEq Γ]
variable (N : GBridge2 H T Sl C α Γ)

/-- gate layer A, after stage 1 and the first idle climb of pair 2: twins have equal frames. -/
lemma GBridge2.gateA : XRoute N.S3 N.S3 (gsc pAB kA) (fun _ => 0) := by
  refine gateP pAB kA N.S3 ?_
  rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩) hk
  · rfl
  · exact (hk rfl).elim
  · exact (hk rfl).elim
  · rfl
  · exact (hk rfl).elim
  · exact (hk rfl).elim

/-- gate layer B, after stage 2 and the second idle climb of pair 2. -/
lemma GBridge2.gateB : XRoute N.S5 N.S5 (gsc pAB kB) (fun _ => 0) := by
  refine gateP pAB kB N.S5 ?_
  rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩) hk
  · exact N.x23 g t
  · exact (hk rfl).elim
  · exact (hk rfl).elim
  · exact (N.y23 g t).symm
  · exact (hk rfl).elim
  · exact (hk rfl).elim

/-- gate layer C, after the final climbs. -/
lemma GBridge2.gateC : XRoute N.S8 N.S8 (gsc pC kCc) (fun _ => 0) := by
  refine gateP pC kCc N.S8 ?_
  rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩) hk
  · exact (hk rfl).elim
  · rfl
  · rfl
  · exact (hk rfl).elim
  · exact (hk rfl).elim
  · exact (hk rfl).elim

/-- the free shifts at the end. -/
def GBridge2.corr : BRole Γ T Sl C → Space α :=
  mkB (fun _ _ => 0) (fun g t => N.u g t) (fun _ _ => 0) (fun g t => N.u g t)
    (fun _ _ => 0) (fun _ _ => 0)

def GBridge2.S9 : BRole Γ T Sl C → CMat α := fun r => shift (N.corr r) * N.S8 r

/-- the whole word before the exchange: five stages, three idle-climb layers, three gate
layers. -/
lemma GBridge2.route :
    GRoute N.S0 N.S8 chain (fun φ => (Fintype.card Γ : ℝ) * N.unit φ) := by
  have R := ((((((((((N.stage0.trans N.stage1).trans (GRoute.ofX N.climbA)).trans
    (GRoute.ofX N.gateA)).trans N.stage2).trans (GRoute.ofX N.climbB)).trans
    (GRoute.ofX N.gateB)).trans N.stage3).trans N.stage4).trans
    (GRoute.ofX N.fin)).trans (GRoute.ofX N.gateC))
  refine (R.castg ?_).cast (fun φ => ?_)
  · rfl
  · simp only [GBridge2.unit]
    ring

/-- **The scratch certificate of the bridged five-stage network with shared helper sets**,
in whole blocks, with its exact price for every price list. -/
theorem gbridge2_certificate :
    GCert α (Sum.inl : BLive Γ T Sl → BRole Γ T Sl C)
      (fun φ => (Fintype.card Γ : ℝ) * N.unit φ) := by
  have R2 : GRoute N.S8 N.S9 id (fun _ => 0) := GRoute.shifts N.hm N.S8 N.corr
  have R3 : GRoute N.S9 (fun r => N.S9 (bpull r)) (actPoint brecM) (fun _ => 0) :=
    GRoute.gate brecM N.S9 _ (fun i j h => by
      have hj : j = bpull i := by
        by_contra hne
        exact h (by simp [brecM, hne])
      rw [hj])
  have Rt := ((N.route.trans R2).trans R3).cast (c' := fun φ => (Fintype.card Γ : ℝ) * N.unit φ)
    (fun φ => by first | ring | simp)
  have hSinv : ∀ r, ∃ M, N.S0 r * M = 1 := by
    rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
    · exact N.inv0 g t
    · refine ⟨1, ?_⟩
      show (N.G0 g).Xm.Φ 0 * 1 = 1
      rw [N.z0, Matrix.mul_one]
    · exact N.inv0 g t
    · refine ⟨1, ?_⟩
      show (N.G0 g).Xm.Φ 0 * 1 = 1
      rw [N.z0, Matrix.mul_one]
    · exact ⟨1, Matrix.mul_one _⟩
    · exact ⟨1, Matrix.mul_one _⟩
  have hT : ∀ l : BLive Γ T Sl, N.S9 (bpull (Sum.inl l)) = kernel α * N.S0 (Sum.inl l) := by
    rintro (((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)
    · show shift (N.u g t) * N.YF g t = kernel α * (N.G0 g).Xm.Φ (tt (N.I.tv t))
      exact (N.term g t).symm
    · show shift (0 : Space α) * kernel α = kernel α * (N.G0 g).Xm.Φ 0
      rw [shift_zero, Matrix.one_mul, N.z0, Matrix.mul_one]
    · show shift (N.u g t) * N.YF g t = kernel α * (N.G0 g).Xm.Φ (tt (N.I.tv t))
      exact (N.term g t).symm
    · show shift (0 : Space α) * kernel α = kernel α * (N.G0 g).Xm.Φ 0
      rw [shift_zero, Matrix.one_mul, N.z0, Matrix.mul_one]
    · show shift (0 : Space α) * kernel α = kernel α * 1
      rw [shift_zero, Matrix.one_mul, Matrix.mul_one]
  have hg : ∀ x : BRole Γ T Sl C → ℂ,
      (∀ s, (∀ l : BLive Γ T Sl, (Sum.inl l : BRole Γ T Sl C) ≠ s) → x s = 0) →
      ∀ l : BLive Γ T Sl,
        (actPoint brecM ∘ (id ∘ chain)) x (Sum.inl l) = x (Sum.inl l) := by
    intro x _ l
    change actPoint brecM (chain x) (Sum.inl l) = _
    rw [actPoint_brecM]
    rcases l with (((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)
    · show ((1:ℚ):ℂ) * chain x (Sum.inl (Sum.inl (Sum.inl (Sum.inr (g,t))))) = _
      rw [chain_eq]
      show ((1:ℚ):ℂ) * x (kX1 (g,t)) = x (kX1 (g,t))
      first | (push_cast; ring) | simp
    · show ((-1:ℚ):ℂ) * chain x (Sum.inl (Sum.inl (Sum.inl (Sum.inl (g,t))))) = _
      rw [chain_eq]
      show ((-1:ℚ):ℂ) * (-x (kY1 (g,t))) = x (kY1 (g,t))
      first | (push_cast; ring) | simp
    · show ((1:ℚ):ℂ) * chain x (Sum.inl (Sum.inl (Sum.inr (Sum.inr (g,t))))) = _
      rw [chain_eq]
      show ((1:ℚ):ℂ) * x (kX2 (g,t)) = x (kX2 (g,t))
      first | (push_cast; ring) | simp
    · show ((-1:ℚ):ℂ) * chain x (Sum.inl (Sum.inl (Sum.inr (Sum.inl (g,t))))) = _
      rw [chain_eq]
      show ((-1:ℚ):ℂ) * (-x (kY2 (g,t))) = x (kY2 (g,t))
      first | (push_cast; ring) | simp
    · show ((1:ℚ):ℂ) * chain x (Sum.inl (Sum.inr (g,q))) = _
      rw [chain_eq]
      show ((1:ℚ):ℂ) * x (kS (g,q)) = x (kS (g,q))
      first | (push_cast; ring) | simp
  exact gcert_of_groute (Sum.inl : BLive Γ T Sl → BRole Γ T Sl C) N.S0
    (fun r => N.S9 (bpull r)) _ _ Rt hSinv hg hT

end Net

end
end GX
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.GX.GBridge2.route
#print axioms OAI.PowerSaving.GX.gbridge2_certificate
