import Work.GCert.Chain.Stage

/-!
# (key: gx-chain) The bridged five-stage word B_2 on the generalised engine: data and frames

GENERATED by checks/wht26/gx-chain/py/netgen.py from Work/Bridge/Net.lean (`BR.Bridge2`): the
invocation is a `GInv`, the frame maps of the stages are windows `GWin` (`G0 .. G4`; the old
frame map of a window is `.Xm`).  Everything else word for word.  No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving
namespace GX
open Binary Matrix Finset RAM SS CB RF BR GF
noncomputable section

/-- See the file header.  Fields in the style of `RF.Fold3S`; stages are numbered 0 to 4. -/
structure GBridge2 (H T Sl C α Γ : Type) [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
    [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C] [Fintype α] [DecidableEq α] where
  /-- the invocation (for a block circuit `X`: `X.inv`). -/
  I : GInv H T Sl C
  /-- frame maps of the invocations of the five stages. -/
  G0 : Γ → GWin H α
  G1 : Γ → GWin H α
  G2 : Γ → GWin H α
  G3 : Γ → GWin H α
  G4 : Γ → GWin H α
  /-- the class `(g,t)` is served by the invocation `g` in stage 0 and `r_l t g` in stage `l`. -/
  r1 : T → Γ ≃ Γ
  r2 : T → Γ ≃ Γ
  r3 : T → Γ ≃ Γ
  r4 : T → Γ ≃ Γ
  /-- the invocation `d` of stage `l` uses the helper set (and the copies) `s_l d`. -/
  s1 : Γ ≃ Γ
  s2 : Γ ≃ Γ
  s3 : Γ ≃ Γ
  s4 : Γ ≃ Γ
  /-- inverse of the frame of the base, and frame of the window, of every invocation. -/
  N1 : Γ → CMat α
  W1 : Γ → CMat α
  N2 : Γ → CMat α
  W2 : Γ → CMat α
  N3 : Γ → CMat α
  W3 : Γ → CMat α
  N4 : Γ → CMat α
  W4 : Γ → CMat α
  u : Γ → T → Space α
  YF : Γ → T → CMat α
  hm : 2 ≤ Fintype.card α
  /-- prices of the idle climbs, for every price list.  B_2 with merged climbs:
  `caX = caY = fun φ => bcost φ (2h-2)`, `cX1 = cY1 = fun φ => bcost φ (2h+2)`,
  `cX2 = cY2 = fun φ => bcost φ 4`. -/
  caX : (ℕ → ℝ) → ℝ
  caY : (ℕ → ℝ) → ℝ
  cX1 : (ℕ → ℝ) → ℝ
  cY1 : (ℕ → ℝ) → ℝ
  cX2 : (ℕ → ℝ) → ℝ
  cY2 : (ℕ → ℝ) → ℝ
  inv0 : ∀ g t, ∃ N : CMat α, (G0 g).Xm.Φ (tt (I.tv t)) * N = 1
  z0 : ∀ g, (G0 g).Xm.Φ 0 = 1
  hN1 : ∀ d, (G1 d).Xm.Φ 0 * N1 d = 1
  hW1 : ∀ d, (G1 d).Xm.Φ 1 = W1 d * (G1 d).Xm.Φ 0
  hN2 : ∀ d, (G2 d).Xm.Φ 0 * N2 d = 1
  hW2 : ∀ d, (G2 d).Xm.Φ 1 = W2 d * (G2 d).Xm.Φ 0
  hN3 : ∀ d, (G3 d).Xm.Φ 0 * N3 d = 1
  hW3 : ∀ d, (G3 d).Xm.Φ 1 = W3 d * (G3 d).Xm.Φ 0
  hN4 : ∀ d, (G4 d).Xm.Φ 0 * N4 d = 1
  hW4 : ∀ d, (G4 d).Xm.Φ 1 = W4 d * (G4 d).Xm.Φ 0
  /-- the bank frames a stage leaves are the bank frames the next stage starts from. -/
  x01 : ∀ g t, (G0 g).Xm.Φ 1 = (G1 (r1 t g)).Xm.Φ (tt (I.tv t))
  y01 : ∀ g t, (G0 g).Xm.Φ (1 + tt (I.tv t)) = (G1 (r1 t g)).Xm.Φ 0
  x12 : ∀ g t, (G1 (r1 t g)).Xm.Φ 1 = (G2 (r2 t g)).Xm.Φ (tt (I.tv t))
  y12 : ∀ g t, (G1 (r1 t g)).Xm.Φ (1 + tt (I.tv t)) = (G2 (r2 t g)).Xm.Φ 0
  x23 : ∀ g t, (G2 (r2 t g)).Xm.Φ 1 = (G3 (r3 t g)).Xm.Φ (tt (I.tv t))
  y23 : ∀ g t, (G2 (r2 t g)).Xm.Φ (1 + tt (I.tv t)) = (G3 (r3 t g)).Xm.Φ 0
  x34 : ∀ g t, (G3 (r3 t g)).Xm.Φ 1 = (G4 (r4 t g)).Xm.Φ (tt (I.tv t))
  y34 : ∀ g t, (G3 (r3 t g)).Xm.Φ (1 + tt (I.tv t)) = (G4 (r4 t g)).Xm.Φ 0
  /-- the five windows of a helper set make up the kernel. -/
  sfin : ∀ g, W4 (s4.symm g) * (W3 (s3.symm g) * (W2 (s2.symm g) *
    (W1 (s1.symm g) * (G0 g).Xm.Φ 1))) = kernel α
  /-- pair 2, idle in stages 0 and 1: ONE block from its start frame to the frame of its
  twin after stage 1. -/
  aX2 : ∀ g t, XReach ((G0 g).Xm.Φ (tt (I.tv t))) ((G1 (r1 t g)).Xm.Φ 1) caX
  aY2 : ∀ g t, XReach ((G0 g).Xm.Φ 0) ((G1 (r1 t g)).Xm.Φ (1 + tt (I.tv t))) caY
  /-- pair 1, idle in stages 3 and 4: ONE block from its frame after stage 2 to the end. -/
  fX1 : ∀ g t, XReach ((G2 (r2 t g)).Xm.Φ 1) (kernel α) cX1
  fY1 : ∀ g t, XReach ((G2 (r2 t g)).Xm.Φ (1 + tt (I.tv t))) (YF g t) cY1
  /-- pair 2 after stage 4: ONE final block. -/
  fX2 : ∀ g t, XReach ((G4 (r4 t g)).Xm.Φ 1) (kernel α) cX2
  fY2 : ∀ g t, XReach ((G4 (r4 t g)).Xm.Φ (1 + tt (I.tv t))) (YF g t) cY2
  term : ∀ g t, kernel α * (G0 g).Xm.Φ (tt (I.tv t)) = shift (u g t) * YF g t

section Net
variable {H T Sl C α Γ : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C] [Fintype α] [DecidableEq α]
  [Fintype Γ] [DecidableEq Γ]
variable (N : GBridge2 H T Sl C α Γ)

/-- price of the blocks of one unit (one element of `Γ`): five invocations and the idle
climbs of the four bank roles of every class. -/
def GBridge2.unit (φ : ℕ → ℝ) : ℝ :=
  5 * N.I.cost φ + (Fintype.card T : ℝ) * ((N.caX φ + N.caY φ)
    + 2 * bcost φ (Fintype.card H - 1)
    + (N.cX1 φ + N.cY1 φ) + (N.cX2 φ + N.cY2 φ))

/-- the bank index of stage 0: the class `(g,t)` belongs to the invocation `g`. -/
abbrev bid (Γ T : Type) : T → Γ ≃ Γ := fun _ => Equiv.refl Γ

/-! bank frames of the class `(g,t)`: `xi l`, `yi l` at the START of stage `l`; `xo l`,
`yo l` at the END of stage `l` (only where no next stage follows on that pair). -/
def GBridge2.xi0 (g : Γ) (t : T) : CMat α := (N.G0 g).Xm.Φ (tt (N.I.tv t))
def GBridge2.yi0 (g : Γ) (t : T) : CMat α := (N.G0 g).Xm.Φ 0
def GBridge2.xi1 (g : Γ) (t : T) : CMat α := (N.G1 (N.r1 t g)).Xm.Φ (tt (N.I.tv t))
def GBridge2.yi1 (g : Γ) (t : T) : CMat α := (N.G1 (N.r1 t g)).Xm.Φ 0
def GBridge2.xi2 (g : Γ) (t : T) : CMat α := (N.G2 (N.r2 t g)).Xm.Φ (tt (N.I.tv t))
def GBridge2.yi2 (g : Γ) (t : T) : CMat α := (N.G2 (N.r2 t g)).Xm.Φ 0
def GBridge2.xo2 (g : Γ) (t : T) : CMat α := (N.G2 (N.r2 t g)).Xm.Φ 1
def GBridge2.yo2 (g : Γ) (t : T) : CMat α := (N.G2 (N.r2 t g)).Xm.Φ (1 + tt (N.I.tv t))
def GBridge2.xi3 (g : Γ) (t : T) : CMat α := (N.G3 (N.r3 t g)).Xm.Φ (tt (N.I.tv t))
def GBridge2.yi3 (g : Γ) (t : T) : CMat α := (N.G3 (N.r3 t g)).Xm.Φ 0
def GBridge2.xi4 (g : Γ) (t : T) : CMat α := (N.G4 (N.r4 t g)).Xm.Φ (tt (N.I.tv t))
def GBridge2.yi4 (g : Γ) (t : T) : CMat α := (N.G4 (N.r4 t g)).Xm.Φ 0
def GBridge2.xo4 (g : Γ) (t : T) : CMat α := (N.G4 (N.r4 t g)).Xm.Φ 1
def GBridge2.yo4 (g : Γ) (t : T) : CMat α := (N.G4 (N.r4 t g)).Xm.Φ (1 + tt (N.I.tv t))

/-- helper slots after the stages 0, 1, 2, 3, 4 (at the start: `cOne Γ Sl α`). -/
def GBridge2.Z1 : Γ → Sl → CMat α := fun g _ => (N.G0 g).Xm.Φ 1
def GBridge2.Z2 : Γ → Sl → CMat α := fun g q => N.W1 (N.s1.symm g) * N.Z1 g q
def GBridge2.Z3 : Γ → Sl → CMat α := fun g q => N.W2 (N.s2.symm g) * N.Z2 g q
def GBridge2.Z4 : Γ → Sl → CMat α := fun g q => N.W3 (N.s3.symm g) * N.Z3 g q
def GBridge2.Z5 : Γ → Sl → CMat α := fun g q => N.W4 (N.s4.symm g) * N.Z4 g q

/-- frames: at the start; after stage 0; after stage 1; after the first idle climb of pair 2
(first gate layer here); after stage 2; after the second idle climb of pair 2 (second gate
layer here); after stage 3; after stage 4; after the final climbs (third gate layer here). -/
def GBridge2.S0 : BRole Γ T Sl C → CMat α := mkB N.xi0 N.yi0 N.xi0 N.yi0 (cOne Γ Sl α) (cOne Γ C α)
def GBridge2.S1 : BRole Γ T Sl C → CMat α := mkB N.xi1 N.yi1 N.xi0 N.yi0 N.Z1 (cOne Γ C α)
def GBridge2.S2 : BRole Γ T Sl C → CMat α := mkB N.xi2 N.yi2 N.xi0 N.yi0 N.Z2 (cOne Γ C α)
def GBridge2.S3 : BRole Γ T Sl C → CMat α := mkB N.xi2 N.yi2 N.xi2 N.yi2 N.Z2 (cOne Γ C α)
def GBridge2.S4 : BRole Γ T Sl C → CMat α := mkB N.xo2 N.yo2 N.xi2 N.yi2 N.Z3 (cOne Γ C α)
def GBridge2.S5 : BRole Γ T Sl C → CMat α := mkB N.xo2 N.yo2 N.xi3 N.yi3 N.Z3 (cOne Γ C α)
def GBridge2.S6 : BRole Γ T Sl C → CMat α := mkB N.xo2 N.yo2 N.xi4 N.yi4 N.Z4 (cOne Γ C α)
def GBridge2.S7 : BRole Γ T Sl C → CMat α := mkB N.xo2 N.yo2 N.xo4 N.yo4 N.Z5 (cOne Γ C α)
def GBridge2.S8 : BRole Γ T Sl C → CMat α :=
  mkB (fun _ _ => kernel α) N.YF (fun _ _ => kernel α) N.YF (fun _ _ => kernel α) (cOne Γ C α)


end Net
end
end GX
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.GX.GBridge2.unit
