import Work.GCert.Chain.NetDef

/-!
# (key: gx-chain) The bridged word B_2 on the generalised engine: the five stages and the idle climbs

GENERATED by checks/wht26/gx-chain/py/netgen.py from Work/Bridge/Net.lean.  The stages are
`GRoute`s (`gistage_fwd` / `gistage_bwd`, `gblift1` / `gblift2`); the idle climbs of the bank
roles are the OLD block routes, unchanged.  No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving
namespace GX
open Binary Matrix Finset RAM SS CB RF BR GF
noncomputable section

section Net
variable {H T Sl C α Γ : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C] [Fintype α] [DecidableEq α]
  [Fintype Γ] [DecidableEq Γ]
variable (N : GBridge2 H T Sl C α Γ)

/-- stage 0: forward on pair 1, every helper set starts at the matrix `1`. -/
lemma GBridge2.stage0 :
    GRoute N.S0 N.S1 (lift1 GF) (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
  have h := gistage_fwd N.I (bid Γ T) (Equiv.refl Γ) N.G0 (fun _ => 1) (fun g => (N.G0 g).Xm.Φ 1)
    (fun d => by rw [N.z0, Matrix.mul_one]) (fun d => by rw [N.z0, Matrix.mul_one])
    (cOne Γ Sl α) (cOne Γ C α) (cOne Γ C α)
  have e : bOut N.I.tv (bid Γ T) (fun d => (N.G0 d).Xm)
      (fun g (q : Sl) => (N.G0 ((Equiv.refl Γ).symm g)).Xm.Φ 1 * cOne Γ Sl α g q) (cOne Γ C α)
      = mkS N.xi1 N.yi1 N.Z1 (cOne Γ C α) := by
    funext r
    rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩)
    · exact N.x01 g t
    · exact N.y01 g t
    · show (N.G0 g).Xm.Φ 1 * 1 = (N.G0 g).Xm.Φ 1
      rw [Matrix.mul_one]
    · rfl
  have h' : GRoute (bIn N.I.tv (bid Γ T) (fun d => (N.G0 d).Xm) (cOne Γ Sl α) (cOne Γ C α))
      (mkS N.xi1 N.yi1 N.Z1 (cOne Γ C α)) GF (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
    rw [← e]
    exact h
  exact gblift1 N.xi0 N.yi0 h'

/-- stage 1: backward on pair 1; the helper set `g` serves the invocation `s1⁻¹ g`. -/
lemma GBridge2.stage1 :
    GRoute N.S1 N.S2 (lift1 GB) (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
  have h := gistage_bwd N.I N.r1 N.s1 N.G1 N.N1 N.W1 N.hN1 N.hW1 N.Z1 (cOne Γ C α) (cOne Γ C α)
  have e : bOut N.I.tv N.r1 (fun d => (N.G1 d).Xm) (fun g q => N.W1 (N.s1.symm g) * N.Z1 g q) (cOne Γ C α)
      = mkS N.xi2 N.yi2 N.Z2 (cOne Γ C α) := by
    funext r
    rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩)
    · exact N.x12 g t
    · exact N.y12 g t
    · rfl
    · rfl
  have h' : GRoute (bIn N.I.tv N.r1 (fun d => (N.G1 d).Xm) N.Z1 (cOne Γ C α))
      (mkS N.xi2 N.yi2 N.Z2 (cOne Γ C α)) GB (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
    rw [← e]
    exact h
  exact gblift1 N.xi0 N.yi0 h'

/-- stage 2: forward on pair 1. -/
lemma GBridge2.stage2 :
    GRoute N.S3 N.S4 (lift1 GF) (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) :=
  gblift1 N.xi2 N.yi2
    (gistage_fwd N.I N.r2 N.s2 N.G2 N.N2 N.W2 N.hN2 N.hW2 N.Z2 (cOne Γ C α) (cOne Γ C α))

/-- stage 3: backward on pair 2. -/
lemma GBridge2.stage3 :
    GRoute N.S5 N.S6 (lift2 GB) (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
  have h := gistage_bwd N.I N.r3 N.s3 N.G3 N.N3 N.W3 N.hN3 N.hW3 N.Z3 (cOne Γ C α) (cOne Γ C α)
  have e : bOut N.I.tv N.r3 (fun d => (N.G3 d).Xm) (fun g q => N.W3 (N.s3.symm g) * N.Z3 g q) (cOne Γ C α)
      = mkS N.xi4 N.yi4 N.Z4 (cOne Γ C α) := by
    funext r
    rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩)
    · exact N.x34 g t
    · exact N.y34 g t
    · rfl
    · rfl
  have h' : GRoute (bIn N.I.tv N.r3 (fun d => (N.G3 d).Xm) N.Z3 (cOne Γ C α))
      (mkS N.xi4 N.yi4 N.Z4 (cOne Γ C α)) GB (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) := by
    rw [← e]
    exact h
  exact gblift2 N.xo2 N.yo2 h'

/-- stage 4: forward on pair 2. -/
lemma GBridge2.stage4 :
    GRoute N.S6 N.S7 (lift2 GF) (fun φ => (Fintype.card Γ : ℝ) * N.I.cost φ) :=
  gblift2 N.xo2 N.yo2
    (gistage_fwd N.I N.r4 N.s4 N.G4 N.N4 N.W4 N.hN4 N.hW4 N.Z4 (cOne Γ C α) (cOne Γ C α))

/-- first idle climb of pair 2 (stages 0 and 1 in ONE block per role), to the frames of
pair 1 after stage 1. -/
lemma GBridge2.climbA :
    XRoute N.S2 N.S3 id (fun φ => (Fintype.card Γ : ℝ) *
      ((Fintype.card T : ℝ) * (N.caX φ + N.caY φ))) := by
  have H1 := XRoute.reach_all N.S2 N.S3
    (mkB (fun _ _ _ => 0) (fun _ _ _ => 0) (fun _ _ => N.caX)
      (fun _ _ => N.caY) (fun _ _ _ => 0) (fun _ _ _ => 0)) (by
      rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
      · exact XReach.refl _
      · exact XReach.refl _
      · show XReach ((N.G0 g).Xm.Φ (tt (N.I.tv t))) ((N.G2 (N.r2 t g)).Xm.Φ (tt (N.I.tv t))) N.caX
        rw [← N.x12 g t]
        exact N.aX2 g t
      · show XReach ((N.G0 g).Xm.Φ 0) ((N.G2 (N.r2 t g)).Xm.Φ 0) N.caY
        rw [← N.y12 g t]
        exact N.aY2 g t
      · exact XReach.refl _
      · exact XReach.refl _)
  refine H1.cast (fun φ => ?_)
  simp_rw [mkB_map (fun c : (ℕ → ℝ) → ℝ => c φ)]
  rw [sum_mkB]
  simp only [sum_const, card_univ, nsmul_eq_mul, mul_zero, add_zero, zero_add]
  ring

/-- second idle climb of pair 2: the window of stage 2, ONE block of rank `card H - 1` per
role, to the frames of pair 1 after stage 2. -/
lemma GBridge2.climbB :
    XRoute N.S4 N.S5 id (fun φ => (Fintype.card Γ : ℝ) *
      ((Fintype.card T : ℝ) * (2 * bcost φ (Fintype.card H - 1)))) := by
  have H1 := XRoute.reach_all N.S4 N.S5
    (mkB (fun _ _ _ => 0) (fun _ _ _ => 0) (fun _ _ φ => bcost φ (Fintype.card H - 1))
      (fun _ _ φ => bcost φ (Fintype.card H - 1)) (fun _ _ _ => 0) (fun _ _ _ => 0)) (by
      rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
      · exact XReach.refl _
      · exact XReach.refl _
      · show XReach ((N.G2 (N.r2 t g)).Xm.Φ (tt (N.I.tv t))) ((N.G3 (N.r3 t g)).Xm.Φ (tt (N.I.tv t)))
          (fun φ => bcost φ (Fintype.card H - 1))
        rw [← N.x23 g t]
        exact N.I.climbX (N.G2 (N.r2 t g)).Xm t
      · show XReach ((N.G2 (N.r2 t g)).Xm.Φ 0) ((N.G3 (N.r3 t g)).Xm.Φ 0)
          (fun φ => bcost φ (Fintype.card H - 1))
        rw [← N.y23 g t]
        exact N.I.climbY (N.G2 (N.r2 t g)).Xm t
      · exact XReach.refl _
      · exact XReach.refl _)
  refine H1.cast (fun φ => ?_)
  simp_rw [mkB_map (fun c : (ℕ → ℝ) → ℝ => c φ)]
  rw [sum_mkB]
  simp only [sum_const, card_univ, nsmul_eq_mul, mul_zero, add_zero, zero_add]
  ring

/-- the final climbs: pair 1 from its frames after stage 2 (ONE block per role for the
stages 3, 4 and the rest), pair 2 from its frames after stage 4; the helper slots are
already at the kernel. -/
lemma GBridge2.fin :
    XRoute N.S7 N.S8 id (fun φ => (Fintype.card Γ : ℝ) *
      ((Fintype.card T : ℝ) * ((N.cX1 φ + N.cY1 φ) + (N.cX2 φ + N.cY2 φ)))) := by
  have H1 := XRoute.reach_all N.S7 N.S8
    (mkB (fun _ _ => N.cX1) (fun _ _ => N.cY1) (fun _ _ => N.cX2) (fun _ _ => N.cY2)
      (fun _ _ _ => 0) (fun _ _ _ => 0)) (by
      rintro ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
      · exact N.fX1 g t
      · exact N.fY1 g t
      · exact N.fX2 g t
      · exact N.fY2 g t
      · show XReach (N.W4 (N.s4.symm g) * (N.W3 (N.s3.symm g) * (N.W2 (N.s2.symm g) *
          (N.W1 (N.s1.symm g) * (N.G0 g).Xm.Φ 1)))) (kernel α) (fun _ => 0)
        rw [N.sfin g]
        exact XReach.refl _
      · exact XReach.refl _)
  refine H1.cast (fun φ => ?_)
  simp_rw [mkB_map (fun c : (ℕ → ℝ) → ℝ => c φ)]
  rw [sum_mkB]
  simp only [sum_const, card_univ, nsmul_eq_mul, mul_zero, add_zero, zero_add]
  ring

end Net
end
end GX
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.GX.GBridge2.stage0
#print axioms OAI.PowerSaving.GX.GBridge2.stage1
#print axioms OAI.PowerSaving.GX.GBridge2.stage2
#print axioms OAI.PowerSaving.GX.GBridge2.stage3
#print axioms OAI.PowerSaving.GX.GBridge2.stage4
#print axioms OAI.PowerSaving.GX.GBridge2.climbA
#print axioms OAI.PowerSaving.GX.GBridge2.climbB
#print axioms OAI.PowerSaving.GX.GBridge2.fin
