import Work.GCert.Chain.InvThm
import Work.Bridge.Cert
import Work.GFrame.Top.Stage

/-!
# (key: gx-chain) Network combinators on `GRoute`, and a stage of generalised invocations

GENERATED by checks/wht26/gx-chain/py/netgen.py from Work/Bridge/Roles.lean (`blift1`, `blift2`)
and Work/Bridge/Inv.lean (`Inv.climbX`, `Inv.climbY`, `istage_fwd`, `istage_bwd`).  No `sorry`.
-/

set_option linter.unusedSectionVars false
set_option linter.unusedVariables false

namespace OAI
namespace PowerSaving
namespace GX
open Binary Matrix Finset RAM SS CB RF BR GF
noncomputable section

section Lift
variable {Γ T Sl C α : Type} [Fintype α] [DecidableEq α]
  [Fintype Γ] [DecidableEq Γ] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C]

/-- **A route on pair 1.**  A route on the one-pair roles, run on the pairs `(X1,Y1)`, the
helper sets and the copies; the pairs `(X2,Y2)` keep their matrices `PX`, `PY` and their
contents. -/
theorem gblift1 {SX SY UX UY : Γ → T → CMat α} (PX PY : Γ → T → CMat α)
    {SS US : Γ → Sl → CMat α} {SC UC : Γ → C → CMat α}
    {h : (SRole Γ T Sl C → ℂ) → (SRole Γ T Sl C → ℂ)} {c : (ℕ → ℝ) → ℝ}
    (q : GRoute (mkS SX SY SS SC) (mkS UX UY US UC) h c) :
    GRoute (mkB SX SY PX PY SS SC) (mkB UX UY PX PY US UC) (lift1 h) c := by
  refine GRoute.lift (em1 (Γ := Γ) (T := T) (Sl := Sl) (C := C)) (h := h) ?_
    (fun x => ?_) (fun x i hi => ?_) (fun i hi => ?_)
  · have e1 : mkB SX SY PX PY SS SC ∘ (em1 (Γ := Γ) (T := T) (Sl := Sl) (C := C))
        = mkS SX SY SS SC := by
      funext r
      rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
    have e2 : mkB UX UY PX PY US UC ∘ (em1 (Γ := Γ) (T := T) (Sl := Sl) (C := C))
        = mkS UX UY US UC := by
      funext r
      rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
    rw [e1, e2]
    exact q
  · funext r
    rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
  · rcases i with ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
    · exact absurd ((cover_iff _ _).mpr ⟨jX (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jY (g,t), rfl⟩) hi
    · rfl
    · rfl
    · exact absurd ((cover_iff _ _).mpr ⟨jS (g,q), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jC (g,c), rfl⟩) hi
  · rcases i with ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
    · exact absurd ((cover_iff _ _).mpr ⟨jX (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jY (g,t), rfl⟩) hi
    · rfl
    · rfl
    · exact absurd ((cover_iff _ _).mpr ⟨jS (g,q), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jC (g,c), rfl⟩) hi

/-- **A route on pair 2**; the pairs `(X1,Y1)` keep their matrices and their contents. -/
theorem gblift2 (PX PY : Γ → T → CMat α) {SX SY UX UY : Γ → T → CMat α}
    {SS US : Γ → Sl → CMat α} {SC UC : Γ → C → CMat α}
    {h : (SRole Γ T Sl C → ℂ) → (SRole Γ T Sl C → ℂ)} {c : (ℕ → ℝ) → ℝ}
    (q : GRoute (mkS SX SY SS SC) (mkS UX UY US UC) h c) :
    GRoute (mkB PX PY SX SY SS SC) (mkB PX PY UX UY US UC) (lift2 h) c := by
  refine GRoute.lift (em2 (Γ := Γ) (T := T) (Sl := Sl) (C := C)) (h := h) ?_
    (fun x => ?_) (fun x i hi => ?_) (fun i hi => ?_)
  · have e1 : mkB PX PY SX SY SS SC ∘ (em2 (Γ := Γ) (T := T) (Sl := Sl) (C := C))
        = mkS SX SY SS SC := by
      funext r
      rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
    have e2 : mkB PX PY UX UY US UC ∘ (em2 (Γ := Γ) (T := T) (Sl := Sl) (C := C))
        = mkS UX UY US UC := by
      funext r
      rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
    rw [e1, e2]
    exact q
  · funext r
    rcases r with (((⟨g,t⟩|⟨g,t⟩)|⟨g,q⟩)|⟨g,c⟩) <;> rfl
  · rcases i with ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
    · rfl
    · rfl
    · exact absurd ((cover_iff _ _).mpr ⟨jX (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jY (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jS (g,q), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jC (g,c), rfl⟩) hi
  · rcases i with ((((⟨g,t⟩|⟨g,t⟩)|(⟨g,t⟩|⟨g,t⟩))|⟨g,q⟩)|⟨g,c⟩)
    · rfl
    · rfl
    · exact absurd ((cover_iff _ _).mpr ⟨jX (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jY (g,t), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jS (g,q), rfl⟩) hi
    · exact absurd ((cover_iff _ _).mpr ⟨jC (g,c), rfl⟩) hi

end Lift

section Pkg
variable {H T Sl C α Γ : Type} [Fintype H] [DecidableEq H] [Fintype T] [DecidableEq T]
  [Fintype Sl] [DecidableEq Sl] [Fintype C] [DecidableEq C] [Fintype α] [DecidableEq α]
  [Fintype Γ] [DecidableEq Γ]
variable (I : GInv H T Sl C)

/-- the idle climb of an x bank role across one window: ONE block of rank `card H - 1`. -/
lemma GInv.climbX (Xm : XMap H α) (t : T) :
    XReach (Xm.Φ (tt (I.tv t))) (Xm.Φ 1) (fun φ => bcost φ (Fintype.card H - 1)) := by
  obtain ⟨p, hp⟩ := I.hgap t
  obtain ⟨A, k, hA⟩ := exists_base_one (I.tv t) (I.hunit t) p hp
  have h := Xm.up A {k} univ (Finset.subset_univ _)
  rw [mat_single, OBase.mat_univ, hA] at h
  refine h.cast (fun φ => ?_)
  rw [Finset.card_sdiff_of_subset (Finset.subset_univ _), Finset.card_univ,
    Finset.card_singleton]

lemma GInv.climbY (Xm : XMap H α) (t : T) :
    XReach (Xm.Φ 0) (Xm.Φ (1 + tt (I.tv t))) (fun φ => bcost φ (Fintype.card H - 1)) := by
  obtain ⟨p, hp⟩ := I.hgap t
  obtain ⟨A, k, hA⟩ := exists_base_one (I.tv t) (I.hunit t) p hp
  have h := Xm.up A ∅ (univ \ {k}) (Finset.empty_subset _)
  rw [mat_empty, mat_compl_single, hA] at h
  refine h.cast (fun φ => ?_)
  rw [Finset.sdiff_empty, Finset.card_sdiff_of_subset (Finset.subset_univ _), Finset.card_univ,
    Finset.card_singleton]

/-- **A forward stage of generalised invocations on shared helper sets** (as `BR.istage_fwd`). -/
theorem gistage_fwd (εX : T → Γ ≃ Γ) (εS : Γ ≃ Γ) (M : Γ → GWin H α) (N0 Wn : Γ → CMat α)
    (hN : ∀ d, (M d).Xm.Φ 0 * N0 d = 1) (hW : ∀ d, (M d).Xm.Φ 1 = Wn d * (M d).Xm.Φ 0)
    (Z : Γ → Sl → CMat α) (c0 c1 : Γ → C → CMat α) :
    GRoute (bIn I.tv εX (fun d => (M d).Xm) Z c0)
      (bOut I.tv εX (fun d => (M d).Xm) (fun g q => Wn (εS.symm g) * Z g q) c1)
      GF (fun φ => (Fintype.card Γ : ℝ) * I.cost φ) := by
  refine gsstage εX εS (h := shearF) (cost := I.cost) (fun d => ?_) (fun d x => ?_)
  · rw [bIn_sem, bOut_sem]
    exact I.fwd (M d) (N0 d) (Wn (εS.symm (εS d))) (hN d)
      (by rw [Equiv.symm_apply_apply]; exact hW d) _ _ _
  · funext b
    rcases b with ((t|t)|(q|k)) <;> rfl

/-- **A backward stage of generalised invocations on shared helper sets.** -/
theorem gistage_bwd (εX : T → Γ ≃ Γ) (εS : Γ ≃ Γ) (M : Γ → GWin H α) (N0 Wn : Γ → CMat α)
    (hN : ∀ d, (M d).Xm.Φ 0 * N0 d = 1) (hW : ∀ d, (M d).Xm.Φ 1 = Wn d * (M d).Xm.Φ 0)
    (Z : Γ → Sl → CMat α) (c0 c1 : Γ → C → CMat α) :
    GRoute (bIn I.tv εX (fun d => (M d).Xm) Z c0)
      (bOut I.tv εX (fun d => (M d).Xm) (fun g q => Wn (εS.symm g) * Z g q) c1)
      GB (fun φ => (Fintype.card Γ : ℝ) * I.cost φ) := by
  refine gsstage εX εS (h := shearB) (cost := I.cost) (fun d => ?_) (fun d x => ?_)
  · rw [bIn_sem, bOut_sem]
    exact I.bwd (M d) (N0 d) (Wn (εS.symm (εS d))) (hN d)
      (by rw [Equiv.symm_apply_apply]; exact hW d) _ _ _
  · funext b
    rcases b with ((t|t)|(q|k)) <;> rfl

end Pkg
end
end GX
end PowerSaving
end OAI

#print axioms OAI.PowerSaving.GX.gblift1
#print axioms OAI.PowerSaving.GX.gblift2
#print axioms OAI.PowerSaving.GX.gistage_fwd
#print axioms OAI.PowerSaving.GX.gistage_bwd
