#!/usr/bin/env python3
"""gram.py -- (1) grammar(): greedy hierarchical sharing of partial sums ('Re-Pair' on the 120 need lists),
optionally applied by whole orbits of a group; (2) compile(): the grammar -> e8.Design with register allocation;
(3) evaluate with e8.quick.  Standard library only."""
import sys
sys.dont_write_bytecode = True
from lib import *
from collections import Counter, defaultdict

# ---------------------------------------------------------------------------------------------- symmetry on symbols
def lift(f):
    """label map f (preserving ports and 'knows') -> (perm on port indices, sign eta) with
    G[p[s]][p[t]] = eta[s] eta[t] G[s][t]"""
    p = as_perm(f)
    assert p is not None
    eta = [0] * V; eta[0] = 1; todo = [0]
    while todo:
        s = todo.pop()
        for t in range(V):
            if G[s][t] and s != t:
                e = eta[s] * G[p[s]][p[t]] * G[s][t]
                if eta[t] == 0:
                    eta[t] = e; todo.append(t)
                else:
                    assert eta[t] == e, "not a symmetry of the Gram matrix"
    return p, eta

def key_of(content):
    """canonical key of a symbol up to a global sign"""
    items = sorted(content.items())
    if items[0][1] < 0:
        items = [(t, -c) for t, c in items]
    return tuple(items)

# ---------------------------------------------------------------------------------------------- grammar
class Grammar:
    def __init__(self):
        self.content = [{T: Fr(1)} for T in range(V)]          # symbol -> {T: coef}
        self.frame = [e8.line(T) for T in range(V)]
        self.kids = [None] * V                                 # (u, v, r): w = u + r v
        self.key = {key_of(c): i for i, c in enumerate(self.content)}
        self.need = [dict(need(S)) for S in range(V)]          # target -> {symbol: coef}

    def counts(self):
        cnt = Counter()
        for S in range(len(self.need)):
            it = sorted(self.need[S].items())
            for i in range(len(it)):
                u, cu = it[i]
                for j in range(i + 1, len(it)):
                    v, cv = it[j]
                    cnt[(u, v, cv / cu)] += 1
        return cnt

    def count1(self, u, v, r):
        return sum(1 for S in range(len(self.need)) if u in self.need[S] and v in self.need[S] and self.need[S][v] == r * self.need[S][u])

    def merge(self, u, v, r):
        """new symbol w = u + r v, replacing (u, v) in every target that holds them in ratio r.  Returns count."""
        tg = [S for S in range(len(self.need)) if u in self.need[S] and v in self.need[S] and self.need[S][v] == r * self.need[S][u]]
        if len(tg) < 1:
            return 0
        c = dict(self.content[u])
        for T, x in self.content[v].items():
            assert T not in c
            c[T] = r * x
        k = key_of(c)
        if k in self.key:
            w = self.key[k]
            sgn = 1 if self.content[w][next(iter(c))] == c[next(iter(c))] else -1
        else:
            w = len(self.content); sgn = 1
            self.content.append(c); self.frame.append(e8.join(self.frame[u], self.frame[v])); self.kids.append((u, v, r))
            self.key[k] = w
        for S in tg:
            cu = self.need[S].pop(u); self.need[S].pop(v)
            assert w not in self.need[S]
            self.need[S][w] = cu * sgn
        self.last = w
        return len(tg)

    def image(self, sym, p, eta):
        """the symbol that is the image of sym under (p, eta), with sign; None if it does not exist yet"""
        c = {p[T]: eta[T] * x for T, x in self.content[sym].items()}
        k = key_of(c)
        w = self.key.get(k)
        if w is None:
            return None, 0
        t0 = next(iter(c))
        return w, (1 if self.content[w][t0] == c[t0] else -1)

    def orbit(self, u, v, r, gens):
        """images of the digram (u, v, r) under the group generated by gens (BFS); digrams as (u', v', r') u' < v'"""
        def norm(a, b, rr):
            return (a, b, rr) if a < b else (b, a, 1 / rr)
        seen = {norm(u, v, r)}; todo = [norm(u, v, r)]
        while todo:
            a, b, rr = todo.pop()
            for p, eta in gens:
                a2, sa = self.image(a, p, eta); b2, sb = self.image(b, p, eta)
                if a2 is None or b2 is None:
                    continue
                d = norm(a2, b2, rr * sb * sa)
                if d not in seen:
                    seen.add(d); todo.append(d)
        return sorted(seen)

    def run(self, gens=(), min_count=2, log=None, floor_ratio=1.0, prefer=None):
        rounds = 0
        while True:
            cnt = self.counts()
            if not cnt:
                break
            best = max(cnt.values())
            if best < min_count:
                break
            cands = [d for d, n in cnt.items() if n == best]
            if prefer:
                cands.sort(key=lambda d: prefer(self, d))
            else:
                cands.sort(key=lambda d: (len(e8.join(self.frame[d[0]], self.frame[d[1]])), d[0], d[1]))
            d0 = cands[0]
            orb = self.orbit(*d0, gens) if gens else [d0]
            done = 0; tot = 0
            for (a, b, rr) in orb:
                n = self.count1(a, b, rr)
                if n >= max(min_count, floor_ratio * best):
                    tot += self.merge(a, b, rr); done += 1
            rounds += 1
            if log is not None:
                log.append((best, len(orb), done, tot, len(self.frame[self.key[key_of(self._c(d0))]]) if False else 0))
            if done == 0:      # should not happen; avoid an endless loop
                self.merge(*d0)
        return rounds

    def _c(self, d):
        return {}

    def run_bf(self, gens=(), rnd=None, batch=True, floor=0.0, tie='dim'):
        """butterfly-aware greedy.  For a pair (u, v) let c+ and c- be the numbers of lists that hold it with ratio +r
        and -r.  Forming BOTH u + r v and u - r v in place on the two registers saves c+ + c- registers; forming one
        saves c - 1.  Each round applies every pair (or the orbit of the first pair) that still has the best saving."""
        self.twin = getattr(self, "twin", {})
        def score(dd):
            cs = sorted(dd.values(), reverse=True)
            return cs[0] + cs[1] if len(cs) >= 2 else cs[0] - 1
        def now(u, v):
            dd = {}
            for S in range(len(self.need)):
                nd = self.need[S]
                if u in nd and v in nd:
                    r = nd[v] / nd[u]; dd[r] = dd.get(r, 0) + 1
            return dd
        def apply(u, v, dd):
            rs = sorted(dd, key=lambda r: (-dd[r], r))[:2]
            ws = []
            for r in rs:
                if dd[r] >= 1 and (len(rs) == 2 or dd[r] >= 2):
                    self.merge(u, v, r); ws.append(self.last)
            if len(ws) == 2 and ws[0] >= V and ws[1] >= V and self.kids[ws[0]][:2] == self.kids[ws[1]][:2]:
                self.twin[ws[0]] = ws[1]; self.twin[ws[1]] = ws[0]
        rounds = 0
        while True:
            cnt = self.counts()
            pair = {}
            for (u, v, r), c in cnt.items():
                pair.setdefault((u, v), {})[r] = c
            if not pair: break
            best = max(score(dd) for dd in pair.values())
            if best < 1: break
            cands = [k for k, dd in pair.items() if score(dd) == best]
            if rnd is None:
                if tie == 'dim':
                    cands.sort(key=lambda k: (len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'size':
                    cands.sort(key=lambda k: (len(self.content[k[0]]) + len(self.content[k[1]]), len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'big':
                    cands.sort(key=lambda k: (-len(self.content[k[0]]) - len(self.content[k[1]]), len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'bigneg':
                    cands.sort(key=lambda k: (-len(self.content[k[0]]) - len(self.content[k[1]]), -len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'bigbal':
                    cands.sort(key=lambda k: (-len(self.content[k[0]]) - len(self.content[k[1]]), abs(len(self.content[k[0]]) - len(self.content[k[1]])), len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'bigmax':
                    cands.sort(key=lambda k: (-max(len(self.content[k[0]]), len(self.content[k[1]])), -len(self.content[k[0]]) - len(self.content[k[1]]), len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie.startswith('bigr'):
                    import random as _r
                    rr = _r.Random(int(tie[4:]) * 1000 + rounds)
                    cands.sort(); rr.shuffle(cands)
                    cands.sort(key=lambda k: -len(self.content[k[0]]) - len(self.content[k[1]]))
                elif tie == 'negdim':
                    cands.sort(key=lambda k: (-len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
                elif tie == 'bal':
                    cands.sort(key=lambda k: (abs(len(self.content[k[0]]) - len(self.content[k[1]])), len(e8.join(self.frame[k[0]], self.frame[k[1]])), k))
            else:
                cands.sort(); rnd.shuffle(cands)
            if gens:
                u, v = cands[0]
                r0 = next(iter(pair[(u, v)]))
                todo = sorted(set((a, b) for a, b, _ in self.orbit(u, v, r0, gens)))
                if (u, v) in todo:
                    todo.remove((u, v))
                todo.insert(0, (u, v))
                done = 0
                for a, b in todo:
                    dd = now(a, b)
                    if dd and score(dd) >= max(1, floor * best):
                        apply(a, b, dd); done += 1
                assert done
            else:
                for u, v in (cands if batch else cands[:1]):
                    dd = now(u, v)
                    if dd and score(dd) == best:
                        apply(u, v, dd)
            rounds += 1
        return rounds

    def stats(self):
        nrules = len(self.content) - V
        reads = sum(len(n) for n in self.need)
        return dict(rules=nrules, reads=reads, lens=Counter(len(n) for n in self.need))

    def check(self):
        for S in range(V):
            tot = defaultdict(Fr)
            for u, c in self.need[S].items():
                for T, x in self.content[u].items():
                    tot[T] += c * x
            assert {T: x for T, x in tot.items() if x} == need(S), S
            for u in self.need[S]:
                assert all(not par(P[S] & w) for w in self.frame[u])
        return True

if __name__ == "__main__":
    import time
    t0 = time.time()
    g = Grammar()
    log = []
    g.run(log=log)
    g.check()
    print("plain greedy:", g.stats(), "rounds", len(log), "%.1fs" % (time.time() - t0))
    print("first rounds (best count, orbit, applied, replaced):", log[:12])
    dims = Counter(len(g.frame[w]) for w in range(V, len(g.content)))
    print("rule frames by dimension:", sorted(dims.items()))
    size = Counter(len(g.content[w]) for w in range(V, len(g.content)))
    print("rule sizes (sources):", sorted(size.items()))
