import OAI.Computability.FourierTransform.Goal

/-
Modified copy of five definitions of lean/OAI/Computability/FourierTransform/Goal.lean of
github.com/openai/math (commit fd4aeeb, Apache-2.0; lines 30, 35, 75-78, 80, 82), generated by
`tools/fourier/mkchain.py`. Changed for this repository:
  * the exponent `1 - 1/(10^(13:ℕ))` is replaced by `1 - 7474546/(10^(10:ℕ))`;
  * the five names have the suffix `Z` (OpenAI's own definitions keep their names and values).
Everything else they mention (`paperTime`, `nlogn`, `DFTProgram`, `ConvProgram`) is OpenAI's own,
imported unmodified.
-/

namespace OAI

namespace PowerSaving
noncomputable section
open RAM RAM.Ty Filter Asymptotics

def decimalExponentZ : ℝ := 1 - 7474546/(10^(10:ℕ))

def decimalTimeZ (n : ℕ) : ℝ := (n:ℝ) * (Real.log (n:ℝ)) ^ decimalExponentZ

/-- Thm 1 (intro main) and decimal corollary estimates. -/
def TimeBoundsZ (W : ℕ → ℕ) : Prop :=
  let W' := fun n : ℕ => (W n : ℝ)
  W' =O[atTop] paperTime ∧ W' =O[atTop] decimalTimeZ ∧ W' =o[atTop] nlogn

def DFTGoalZ : Prop := ∃ order solve W, DFTProgram order solve W ∧ TimeBoundsZ W

def ConvGoalZ : Prop := ∃ order solve W, ConvProgram order solve W ∧ TimeBoundsZ W

end
end PowerSaving

end OAI
