import Work.Fourier.ConvolutionProgram

/-
Modified copy of lean/OAI/Computability/FourierTransform/UniformBounds.lean of github.com/openai/math
(commit fd4aeeb, Apache-2.0), generated by `tools/fourier/mkchain.py`. OpenAI's file itself is
unmodified in this repository and still imported. Changed for this repository, all mechanically:
  * every declaration of this file (and of the other 10 copied files) has the suffix `Z`
    on its name, so that it does not collide with OpenAI's original;
  * OpenAI's exponent `alpha = 1 - 2/10^11` and envelope `hills` are replaced by
    `alphaZ = 1 - 7474547/10^10` and `hillsZ` (Work/Fourier/Seam.lean), and the single use of
    OpenAI's `hills_program` by `hillsZ_program`;
  * `decimalExponent`, `decimalTime`, `TimeBounds`, `DFTGoal`, `ConvGoal` are replaced by their
    `Z` versions from Work/Fourier/Goal.lean (exponent `1 - 7474546/10^10`);
  * imports point to the copies.
Comments and docstrings below are OpenAI's and describe OpenAI's network, not ours.
-/

namespace OAI

/- Static allowance to programs. -/
namespace PowerSaving
open RAM Ty Selection Spectral Slant
noncomputable section

namespace RAM.Bench
universe U
variable {ι : Type U} {κ : Type*} {m : Bool} {b : Bench m ι}
  {n : ι→ℕ} {t : Ty}

lemma fairwind_smallZ (N : ι→ℕ) (hn : ∀ i,0<N i) (d : ℕ) :
    Small N fun i => fairwindZ d (N i) := by
  have H := Small.self N
  have hX i := barge_spec (N i) (hn i)
  have h4 := (Small.const _ 4).mul H
  have hu := h4.mono (fun (i : ι) => stack_le (N i) (hn i))
  have hk : Small N fun i => harvestN (N i) :=
    (((Small.const _ 16).mul (hu.add (Small.const _ 4))).pow 2)
  have hh := ((Small.const _ 8).mul hk).mono
    (fun i => Nat.lt_two_pow_self.le.trans (orderE_small (N i)))
  have hi := ((((Small.const _ 20000000).mul ((hh.add (Small.const _ 1)).pow 2)).add
    (Small.const _ 7))).mono (fun i => score_le (orderE (N i)))
  have hp : Small N fun i => hillsZ (barge (N i)).l :=
    (hu.add (Small.const _ 1)).mono fun i => (hillsZ_le _).trans
      (Nat.add_le_add_right (hX i).count _)
  have hj := (hi.add (Small.const _ 1)).mul
    ((h4.mono fun i => (hX i).upper.le).mul hp)
  have hl := H.add hj |>.add ((hu.add (Small.const _ 2)).pow d)
  exact hl.add (((H.add (Small.const _ 2)).pow d).mono fun i => by split <;> omega)

-- package extracted charges
abbrev SizesZ := {n : ℕ // 0<n}
abbrev entryZ : SizesZ→ℕ := Subtype.val

structure RationZ where
  d : ℕ
  c : ℕ
  p : ℕ
def calorieZ (a : RationZ) (n : ℕ) := a.c*(fairwindZ a.d n+1)

lemma BreezyZ.ration {x : ι→T t} (h : b.BreezyZ n t x) :
    ∃ (s : Prog m b.tray t) (a : RationZ), ∀ i,
      (run s (b.env i)).OK (x i) (calorieZ a (n i)) ((b.size i+2)^a.p) := by
  obtain ⟨d,hd⟩ := h
  obtain ⟨s,c,p,hc⟩ := Can.unfold_bound hd
  exact ⟨s,⟨d,c,p⟩,hc⟩

def lunchZ (a b : RationZ) (N : ℕ→ℕ) (n : ℕ) :=
  calorieZ a (N n)+1+calorieZ b (N n)

lemma storehouseZ (N : ℕ→ℕ) (h : ∀ n,0<n → 0<N n) (g : Small entryZ (fun i => N (entryZ i)))
    (a b : RationZ) : ∃ c : ℕ, ∀ n : ℕ, 0<n →
    let cap := (n+2)^c
    lunchZ a b N n + 10*(n+2) ≤ cap ∧ (n+2)^a.p ≤ cap ∧ (n+2)^b.p ≤ cap ∧
    receipt (N n) ≤ cap := by
  let M i := N (entryZ i)
  have H (a : RationZ) : Small entryZ (fun i => calorieZ a (M i)) :=
    (Small.const _ a.c).mul (((fairwind_smallZ M (fun i => h _ i.property) a.d).trans g).add
      (Small.const _ 1))
  have hu := (Small.self entryZ).add (Small.const _ 2)
  have hh := (Small.const _ 10).mul hu
  have hp := ((Small.const _ 8).mul (g.pow 3)).mono
    (fun i => (receipt_bound _ (h _ i.property)).2.le)
  have ht := ((((H a).add (Small.const _ 1)).add (H b)).add hh)
  obtain ⟨c,hc⟩ := (((ht.max (hu.pow a.p)).max (hu.pow b.p)).max hp)
  refine ⟨c,fun n hn => ?_⟩
  specialize hc (⟨n,hn⟩:SizesZ)
  have hx :
      max (max (max (lunchZ a b N n + 10*(n+2)) ((n+2)^a.p)) ((n+2)^b.p)) (receipt (N n)) ≤
        (n+2)^c := hc
  have h1 := max_le_iff.mp hx
  have h2 := max_le_iff.mp h1.1
  have h3 := max_le_iff.mp h2.1
  exact ⟨h3.1,h3.2,h2.2,h1.2⟩

-- order environments
def onlyLengthZ : Bench false SizesZ := ⟨entryZ,w,entryZ⟩
lemma onlyLength_numZ : onlyLengthZ.Nick entryZ := ⟨Can.id,Small.self _⟩

lemma orders1Z : ∃ (s : Prog false w w) (a : RationZ), ∀ n,0<n →
    (run s n).OK (receipt n) (calorieZ a n) ((n+2)^a.p) := by
  obtain ⟨s,a,ha⟩ := (onlyLength_numZ.landOrderZ (fun i => i.property)).ration
  exact ⟨s,a,fun i hi => ha ⟨i,hi⟩⟩
lemma orders2Z : ∃ (s : Prog false w w) (a : RationZ), ∀ n,0<n →
    (run s n).OK (receipt (stretchZ n)) (calorieZ a (stretchZ n)) ((n+2)^a.p) := by
  have H : onlyLengthZ.Nick fun i => stretchZ (entryZ i) :=
    ((Nick.wc 2).mul onlyLength_numZ).sub (Nick.wc 1)
  obtain ⟨s,a,ha⟩ := (H.landOrderZ (fun i => stretch_posZ i.property)).ration
  exact ⟨s,a,fun i hi => ha ⟨i,hi⟩⟩

def towerOneZ : Bench false (SizesZ×Line) :=
  ⟨fun i => entryZ i.1,dftInKind,fun i =>
    (entryZ i.1, root (receipt (entryZ i.1)),Tape.tab (entryZ i.1) i.2)⟩

lemma executeOneZ : ∃ (s : Prog false dftInKind dftOutKind) (a : RationZ),
    ∀ (n : ℕ),0<n → ∀ x : Vec n,
    (run s (n, root (receipt n), (⟨n,x⟩ : Tape ℂ))).OK
      (⟨n, dft n x⟩ : Tape ℂ) (calorieZ a n) ((n+2)^a.p) := by
  let K := towerOneZ
  have ht : K.Moves (fun _ => 0) dftInKind K.env := envNow K
  let n (i : SizesZ × Line) := entryZ i.1
  have hk : K.Nick n := ⟨ht.fst,Small.self _⟩
  have H := hk.landZ (fun i => i.1.property) (ht.snd.fst) false (x:=Prod.snd) (cl:=Paint.left)
    (ht.snd.snd)
  obtain ⟨s,a,ha⟩ := H.ration
  refine ⟨s,a,fun n hn x => ?_⟩
  specialize ha ((⟨n,hn⟩:SizesZ),extendLine x)
  change (run s (n,root (receipt n),(⟨n,front n (extendLine x)⟩:Tape ℂ))).OK
    (⟨n,front n (freq n (pr false n) (extendLine x))⟩ : Tape ℂ) _ _ at ha
  rw [← dft_front n,front_exact] at ha
  exact ha

def towerBothZ : Bench true (SizesZ×Line×Line) :=
  ⟨fun i => entryZ i.1,convInKind,fun i =>
    (entryZ i.1, root (receipt (stretchZ (entryZ i.1))),Tape.tab (entryZ i.1) i.2.1,
      Tape.tab (entryZ i.1) i.2.2)⟩

lemma executeBothZ : ∃ (s : Prog true convInKind convOutKind) (a : RationZ),
    ∀ (n : ℕ),0<n → ∀ x y : Vec n,
    (run s (n, root (receipt (stretchZ n)), (⟨n,x⟩ : Tape ℂ),(⟨n,y⟩ : Tape ℂ))).OK
      (⟨stretchZ n, conv n x y⟩ : Tape ℂ) (calorieZ a (stretchZ n)) ((n+2)^a.p) := by
  let K := towerBothZ
  have ht : K.Moves (fun _ => 0) convInKind K.env := envNow K
  let n (i : SizesZ × Line×Line) := entryZ i.1
  have hk : K.Nick n := ⟨ht.fst,Small.self _⟩
  have H := fusingZ hk (fun i => i.1.property) (x:=fun i => i.2.1) (y:=fun i => i.2.2)
    ht.snd.snd.fst ht.snd.snd.snd ht.snd.fst
  obtain ⟨s,a,ha⟩ := H.ration
  refine ⟨s,a,fun n hn x y => ?_⟩
  specialize ha ((⟨n,hn⟩:SizesZ),extendLine x,extendLine y)
  change (run s (n,root (receipt (stretchZ n)),
    (⟨n,front n (extendLine x)⟩:Tape ℂ),(⟨n,front n (extendLine y)⟩:Tape ℂ))).OK
    (⟨2*n-1,front (2*n-1)
      (cyclic (2*n-1) (padline n (extendLine y)) (padline n (extendLine x)))⟩ : Tape ℂ) _ _ at ha
  rw [cyclic_pad_front,front_exact,front_exact] at ha
  exact ha

theorem flagshipOneZ : ∃ order solve a b,
    DFTProgram order solve (lunchZ a b id) ∧
    ∀ n, 0<n → (run order n).val = receipt n := by
  obtain ⟨o,a,ho⟩ := orders1Z
  obtain ⟨s,b,hs⟩ := executeOneZ
  obtain ⟨c,hc⟩ := storehouseZ id (fun _ h => h) (Small.self entryZ) a b
  refine ⟨o,s,a,b,⟨c,fun n hn => ?_⟩,fun n hn => (ho n hn).result⟩
  obtain ⟨hu,hA,hB,hR⟩ := hc n hn
  have H := ho n hn
  have HH := receipt_bound n hn
  have he := H.result
  refine ⟨hu,H.bound.trans hA,H.valid,he.symm ▸ HH.1,he.symm ▸ ?_,he.symm ▸ hR,fun x => ?_⟩
  · exact HH.2.trans_le (by omega)
  dsimp only
  rw [he]
  have hj := hs n hn x
  exact ⟨hj.valid,hj.bound.trans hB,add_le_add (add_le_add_left H.time 1) hj.time,hj.result⟩

theorem flagshipBothZ : ∃ order solve a b,
    ConvProgram order solve (lunchZ a b stretchZ) ∧
    ∀ n, 0<n → (run order n).val = receipt (stretchZ n) := by
  obtain ⟨o,a,ho⟩ := orders2Z
  obtain ⟨s,b,hs⟩ := executeBothZ
  obtain ⟨c,hc⟩ := storehouseZ stretchZ (fun _ h => stretch_posZ h)
    (((Small.const _ 2).mul (Small.self entryZ)).sub (Q:=fun _ => 1)) a b
  refine ⟨o,s,a,b,⟨c,fun n hn => ?_⟩,fun n hn => (ho n hn).result⟩
  obtain ⟨hu,hA,hB,hR⟩ := hc n hn
  have H := ho n hn
  have HH := receipt_bound _ (stretch_posZ hn)
  have he := H.result
  refine ⟨hu,H.bound.trans hA,H.valid,he.symm ▸ HH.1,he.symm ▸ ?_,he.symm ▸ hR,fun x y => ?_⟩
  · exact HH.2.trans_le (by unfold stretchZ; omega)
  dsimp only
  rw [he]
  have hj := hs n hn x y
  exact ⟨hj.valid,hj.bound.trans hB,add_le_add (add_le_add_left H.time 1) hj.time,hj.result⟩

end RAM.Bench
end
end PowerSaving

end OAI
